//
// This map contains the request string of the old page and where the visitor
// should be redirected to in case he visits an old documentation URL
//
// If you want to add an entry you must use this format:
// "<old page>" : "<new anchor>",
// Note: the last entry must never end with a comma!
//
// Examples
// "/display/PTD/CIMB+Clicks": "#CIMB-Clicks",
// "/pages/viewpage.action?pageId=3704226" : "#WPPSecurity-MerchantsIntegratedwithNVP",
//

var redirectMap = {
  "/display/PTD/API+merchant+specification" : "RestApi.html",
  "/display/PTD/Appendix+K:+Test+Access+Data+and+Credentials" : "AppendixK.html",
  "/display/PTD/Wirecard+Payment+Page" : "PPv2.html",
  "/display/PTD/Credit+Card+with+WPP" : "PPv2.html#PPv2_CC",
  "/display/PTD/Seamless+Mode" : "PPv2.html#WPP_Seamless",
  "/display/PTD/REST+API" : "RestApi.html",
  "/display/PTD/3-D+Secure+2" : "CreditCard.html#CreditCard_3DS2",
  "/display/PTD/Credit+Card" : "PaymentMethods.html",
  "/display/PTD/General+Platform+Features" : "GeneralPlatformFeatures.html",
  "/display/PTD/HPP+Integration" : "PPv2.html#PaymentPageSolutions_WPP_HPP",
  "/display/PTD/PayPal" : "API_PaymentMethods_PayPal.html",
  "/display/PTD/Return+Codes+and+Transaction+Statuses" : "StatusCodes.html",
  "/display/PTD/Embedded+Payment+Page" : "PPv2.html#PaymentPageSolutions_WPP_EPP",
  "/display/PTD/Hosted+Payment+Page" : "PPv2.html#PaymentPageSolutions_WPP_HPP",
  "/display/PTD/Shop+Systems" : "ShopSystems.html",
  "/display/PTD/Transaction+Types" : "CreditCard.html#CreditCard_TransactionTypes",
  "/display/PTD/EPP+Integration" : "PPv2.html#PaymentPageSolutions_PPv2_EPP_Integration",
  "/display/PTD/Payment+Page" : "PPv2.html",
  "/display/PTD/CIMB+Clicks" : "CIMBClicks.html",
  "/API_AlipayCrossBorder.html" : "AlipayCrossBorder_Main.html",
  "/API_AlipayDomestic.html" : "AlipayDomestic_Main.html",
  "/API_MasterPass.html" : "Masterpass_Main.html",
  "/API_Masterpass.html" : "Masterpass_Main.html",
  "/API_POIPIA.html" : "POIPIA_Main.html",
  "/API_PayPal_Fields_Payment.html" : "PayPal_Main.html#API_PayPal_Fields",
  "/API_PayPal_Fields_Payment_AccountHolder_Address.html" : "PayPal_Main.html#API_PayPal_Fields_Payment_AccountHolder_Address",
  "/API_PayPal_Fields_Payment_Shipping.html" : "PayPal_Main.html#API_PayPal_Fields_Payment_Shipping",
  "/API_PayPal_Fields_Payment_Shipping_Address.html" : "PayPal_Main.html#API_PayPal_Fields_Payment_Shipping_Address",
  "/API_PayPal_Fields_Payment_accountHolder.html" : "PayPal_Main.html#API_PayPal_Fields_Payment_accountHolder",
  "/API_PayPal_Fields_Payment_customfields.html" : "PayPal_Main.html#API_PayPal_Fields_Payment_customfields",
  "/API_PayPal_Fields_Payment_notifications.html" : "PayPal_Main.html#API_PayPal_Fields_Payment_notifications",
  "/API_PayPal_Fields_Payment_paymentmethods.html" : "PayPal_Main.html#API_PayPal_Fields_Payment_paymentmethods",
  "/API_PayPal_Fields_Payment_periodic.html" : "PayPal_Main.html#API_PayPal_Fields_Payment_periodic",
  "/API_PayPal_Fields_Payment_statuses.html" : "PayPal_Main.html#API_PayPal_Fields_Payment_statuses_status",
  "/API_PayPal_Fields_Payment_statuses_status.html" : "PayPal_Main.html#API_PayPal_Fields_Payment_statuses_status",
  "/API_PayPal_Fields_Payment_wallet.html" : "PayPal_Main.html#API_PayPal_Fields_Payment_wallet",
  "/API_PaybyBankapp.html" : "PayByBankApp_Main.html",
  "/API_PaymentMethods_PayPal.html" : "PayPal_Main.html",
  "/API_WeChatQRPay.html" : "WeChat_Main.html",
  "/AppendixD.html" : "CC_Main.html#AppendixD",
  "/AppendixF.html" : "CreditCard_3DS2.html#AppendixF",
  "/AppendixI.html" : "AppendixI_FAQ.html",
  "/AppendixI_FAQ.html" : "AppendixI_FAQ.html",
  "/ApplePay.html" : "ApplePay_Main.html",
  "/Bancontact.html" : "Bancontact_Main.html",
  "/BancontactMisterCash.html" : "Bancontact_Main.html",
  "/BatchProcessingApi_FieldNameMapping.html" : "BatchProcessingApi_Integration.html#BatchProcessingApi_FieldNameMapping",
  "/BatchProcessingApi_Fields.html" : "BatchProcessingApi_Integration.html#BatchProcessingApi_Fields",
  "/BatchProcessingApi_Files.html" : "BatchProcessingApi_Integration.html#BatchProcessingApi_Files",
  "/BatchProcessingApi_Introduction.html" : "BatchProcessingApi.html",
  "/BatchProcessingApi_PGP.html" : "BatchProcessingApi_Integration.html#BatchProcessingApi_PGP",
  "/BatchProcessingApi_SFTPforBatchProcessing.html" : "BatchProcessingApi_Integration.html#BatchProcessingApi_SFTPforBatchProcessing",
  "/BatchProcessingApi_TestCredentials.html" : "BatchProcessingApi_Integration.html#BatchProcessingApi_TestCredentials",
  "/BatchProcessingApi_UploadDownload.html" : "BatchProcessingApi_Integration.html#BatchProcessingApi_UploadDownload",
  "/BatchProcessingApi_WPGvsSepaConversionService.html" : "BatchProcessingApi.html",
  "/BatchProcessingApi_Workflow.html" : "BatchProcessingApi_Integration.html#BatchProcessingApi_Workflow",
  "/Boleto.html" : "Boleto_Main.html",
  "/CIMBClicks.html" : "CIMBClicks_Main.html",
  "/CarrierBilling.html" : "CarrierBilling_Main.html",
  "/CreditCard.html" : "CC_Main.html",
  "/FPX.html" : "FPX_Main.html",
  "/GeneralIntegrationOptions_Batch.html" : "BatchProcessingApi.html",
  "/GeneralIntegrationOptions_PP.html" : "PaymentPageSolutions.html",
  "/GeneralIntegrationOptions_RestApi.html" : "RestApi.html",
  "/GeneralIntegrationOptions_SDK.html" : "MobilePaymentSDK.html",
  "/GeneralPlatformFeatures_CrossMerchant.html" : "GeneralPlatformFeatures.html#GeneralPlatformFeatures_CrossMerchant",
  "/GeneralPlatformFeatures_CrossPayment.html" : "GeneralPlatformFeatures.html#GeneralPlatformFeatures_CrossPayment",
  "/GeneralPlatformFeatures_CrossRef.html" : "GeneralPlatformFeatures.html#GeneralPlatformFeatures_CrossRef",
  "/GeneralPlatformFeatures_IPN.html" : "GeneralPlatformFeatures.html#GeneralPlatformFeatures_IPN",
  "/GeneralPlatformFeatures_IPP.html" : "GeneralPlatformFeatures.html#GeneralPlatformFeatures_IPP",
  "/GeneralPlatformFeatures_InstrumentCountryBounceback.html" : "GeneralPlatformFeatures.html#GeneralPlatformFeatures_InstrumentCountryBounceback",
  "/GeneralPlatformFeatures_IpValidation.html" : "GeneralPlatformFeatures.html#GeneralPlatformFeatures_IpValidation",
  "/GeneralPlatformFeatures_MerchantAccountResolving.html" : "GeneralPlatformFeatures.html#GeneralPlatformFeatures_MerchantAccountResolving",
  "/GeneralPlatformFeatures_RedirectURL.html" : "GeneralPlatformFeatures.html#GeneralPlatformFeatures_RedirectURL",
  "/GeneralPlatformFeatures_ServerAvailability.html" : "GeneralPlatformFeatures.html#GeneralPlatformFeatures_ServerAvailability",
  "/GeneralPlatformFeatures_Surcharging.html" : "GeneralPlatformFeatures.html#GeneralPlatformFeatures_Surcharging",
  "/GeneralPlatformFeatures_Transactions.html" : "GeneralPlatformFeatures.html#GeneralPlatformFeatures_Transactions",
  "/GooglePay.html" : "GooglePay_Main.html",
  "/GuaranteedDirectDebit.html" : "GuaranteedDirectDebit_Main.html",
  "/GuaranteedInvoice.html" : "GuaranteedInvoice_Main.html",
  "/Interac.html" : "Interac_Main.html",
  "/Klarna.html" : "Klarna_Main.html",
  "/KlarnaV2.html" : "KlarnaV2_Main.html",
  "/MOLPay.html" : "MOLPay_Main.html",
  "/Maybank2u.html" : "Maybank2U_Main.html",
  "/MobilePaymentSDK.html" : "MobilePaymentSDK_IntegrationGuides.html",
  "/MobilePaymentSDK_Android.html" : "MobilePaymentSDK_IntegrationGuides.html#MobilePaymentSDK_Android",
  "/MobilePaymentSDK_BasicSetup.html" : "MobilePaymentSDK_IntegrationGuides.html#MobilePaymentSDK_BasicSetup",
  "/MobilePaymentSDK_FirstSteps.html" : "MobilePaymentSDK_IntegrationGuides.html#MobilePaymentSDK_FirstSteps",
  "/MobilePaymentSDK_Introduction.html" : "MobilePaymentSDK_IntegrationGuides.html",
  "/MobilePaymentSDK_PaymentMethods.html" : "MobilePaymentSDK_IntegrationGuides.html",
  "/MobilePaymentSDK_iOS.html" : "MobilePaymentSDK_IntegrationGuides.html#MobilePaymentSDK_iOS",
  "/MoipPagamentos.html" : "moip_Main.html",
  "/MultiPaymentApi.html" : "MultiPaymentApi_Integration.html",
  "/MultiPaymentApi_GoingonProduction.html" : "MultiPaymentApi_Integration.html#MultiPaymentApi_GoingonProduction",
  "/MultiPaymentApi_Overview.html" : "MultiPaymentApi_Integration.html",
  "/MultiPaymentApi_RetrieveMultiPayments.html" : "MultiPaymentApi_Integration.html#MultiPaymentApi_RetrieveMultiPayments",
  "/MultiPaymentApi_Samples.html" : "MultiPaymentApi_Integration.html#MultiPaymentApi_Samples",
  "/MultiPaymentApi_TransactionTypes.html" : "MultiPaymentApi_Integration.html#MultiPaymentApi_TransactionTypes",
  "/MultiPaymentApi_Workflow.html" : "MultiPaymentApi_Integration.html#MultiPaymentApi_Workflow",
  "/POLi.html" : "POLi_Main.html",
  "/PP.html" : "PaymentPageSolutions.html#PP",
  "/PPv2.html" : "PaymentPageSolutions.html#PPv2",
  "/Paylib.html" : "Paylib_Main.html",
  "/Przelewy24.html" : "Przelewy24_Main.html",
  "/RestApi_GoingOnProduction.html" : "RestApi.html#RestApi_GoingOnProduction",
  "/RestApi_Payment.html" : "RestApi.html#RestApi_Payment",
  "/RestApi_Samples.html" : "RestApi.html#RestApi_Samples",
  "/RestApi_Security.html" : "RestApi.html#RestApi_Security",
  "/RestApi_Simulations.html" : "RestApi.html#RestApi_Simulations",
  "/ShopSystems_ContactUs.html" : "ContactUs.html",
  "/ShopSystems_Myths.html" : "ShopSystems.html#ShopSystems_Myths",
  "/ShopSystems_TermsOfUse.html" : "ShopSystems.html#ShopSystems_TermsOfUse",
  "/SkrillDigitalWallet.html" : "Skrill_Main.html",
  "/Sofort.html" : "Sofort_Main.html",
  "/StatusCodes_Categorizations.html" : "StatusCodes.html#StatusCodes_Categorizations",
  "/StatusCodes_InDetail.html" : "StatusCodes.html#StatusCodes_InDetail",
  "/StatusCodes_Test.html" : "CC_Main.html#API_CC_TestCards",
  "/TrustPay.html" : "TrustPay_Main.html",
  "/Trustly.html" : "Trustly_Main.html",
  "/VISACheckout.html" : "VISACheckout_Main.html",
  "/WPP.html" : "IntegrationGuides_WPP_v2.html",
  "/WirecardVoucher.html" : "Voucher_Main.html",
  "/eNETS.html" : "eNets_Main.html",
  "/eps.html" : "epsUberweisung_Main.html",
  "/giropay.html" : "giropay_Main.html",
  "/iDEAL.html" : "iDEAL_Main.html",
  "/mobicred.html" : "Mobicred_Main.html",
  "/monetaRu.html" : "moneta_Main.html",
  "/paydirekt.html" : "Paydirekt_Main.html",
  "/payolution.html" : "payolution_Main.html",
  "/paysafecard.html" : "paysafecard_Main.html",
  "last entry" : "do not change"
};
