
.*check-enrollment* 

This is the initial request in a 3D Secure 2 payment flow. It initiates the payment session and checks if the consumer's card is enrolled in the 3D Secure 2 program.

New 3D Secure 2 fields can be found in the <<CreditCard_3DS2_Fields, 3D Secure 2 field table>>. +
ifdef::env-wirecard[]
ifndef::env-nova[]
They are also included in the <<Appendix_Xml, REST API payment XSD>>.
endif::[]
endif::[]

CAUTION: For 3D Secure 2 transactions, include the new field ``three-d/version`` and set its value to ``2.1``. 

As a result of the check-enrollment, you receive the *PAReq* with the ACS URL.

See the <<CreditCard_Samples_CheckEnrollment_3DS2, XML request/response samples for check-enrollment>>.

._Redirect the consumer to the ACS URL_

Send an HTTPS POST request including the ACS URL, the *<PAReq>*, the *<TermUrl>* and *<MD>*.

* The *<TermUrl>* is the web address of your server to receive the *PARes* (Payment Authentication response).
* The *<MD>* is a hidden field reserved for specific merchant data. The *<MD>* may be useful for retrieving transaction data from the database or recalling a transaction.

+
NOTE: The *<MD>* field is _mandatory_. Make sure to include it in the request. You do not need to enter a value. +
If you omit this field, an authentication error occurs and the payment process is aborted. 
+
.Example: Auto Submission POST Request
[source,html]
----
<html>
   <head>
      <meta HTTP-EQUIV="Content-Type" content="text/html; charset=UTF-8" />
      <meta HTTP-EQUIV="Cache-Control" CONTENT="no cache" />
      <meta HTTP-EQUIV="Pragma" CONTENT="no cache" />
      <meta HTTP-EQUIV="Expires" CONTENT="0" />
   </head>
   <body OnLoad="AutoSubmitForm();">
      <form name="downloadForm" action="AcsUrl" method="POST">
         <input type="hidden" name="PaReq" value="PaReq" />
         <input type="hidden" name="TermUrl" value="TermUrl" />
         <input type="hidden" name="MD" value="optionalValue" />
         <SCRIPT LANGUAGE="Javascript">
            <!--function AutoSubmitForm() { document.downloadForm.submit();}//-->
         </SCRIPT>
         <input type="submit" name="continue" value="Continue" />
      </form>
   </body>
</html>
----

Once the consumer has been redirected, they receive an authentication prompt. The consumer enters their data. After successful authentication, the SSL-encrypted and digitally signed *PARes* (Payment Authentication Response) is posted to the *TermURL* via the consumer's browser. 

.*check-payer-response* (optional)

Use this request to receive, analyze and store authentication values or use your connection to the {payment-gateway} for the "MPI Only" option. The *check-payer-response* provides/returns the authentication values needed later on in the *purchase.* It is executed _after_ you receive the *check-enrollment* response and the *PARes*. 

The *check-payer-response* must contain the following fields:

 * ``three-d/pares``: This is the digitally signed, base64-encoded authentication response message containing ARes/CRes received from the issuer.
 * ``parent-transaction-id``: Use the value returned in the ``transaction-id`` field of the *check-enrollment* response.
