ifndef::env-nova[] 
[#API_CC_3DS2_UseCases_StoringCCDetails]
=== Storing Credit Card Details

For card-on-file transactions, merchants store the consumer's card data (as a token) for future transactions. Thus, when the consumer returns to the merchant's shop, they do not need to re-enter their data.

WARNING: Before storing credentials on file, consumers must be clearly informed how the credentials will be used in the future. Obtain the consumers' consent.

[NOTE]
====
Authentication required: Yes +
Card-on-file flagging required: Yes
====
endif::[]


ifndef::env-nova[]
[#API_CC_3DS2_UseCases_AddingCardOnFile_IndependentOfPurchase]
==== Option 1: Storing Credit Card Details - Independent of Purchase

pass:[<a href="<resources/3-d-secure-2/usecase_pm-collection/adding-card-onfile.postman_collection.json>" target="_blank" rel="noreferrer noopener" download>Download a Postman collection of this use case here.</a>] 
// Include working link here

The 3D Secure 2 fields can be found in the <<CC_3DS2_fields, 3D Secure 2 field table>>. 
ifdef::env-wirecard[]
They are also included in the <<Appendix_Xml, REST API payment XSD>>.
endif::[]

. *Check-enrollment* (zero amount) +
include::{root}/include/3-d-secure/3-d-secure-2-check-enrollment.adoc[]
+
CAUTION: For 3D Secure 2 consumer-initiated one-click checkout, include the field ``three-d/version`` and set its value to ``2.1``. Set ``challenge-indicator`` to ``04``. Set the ``periodic-type`` to ``ci`` (consumer-initiated) and the ``sequence-type`` to ``first``.
+
As a result of the check-enrollment, you receive the ``PAReq`` with the ACS URL.
+

. *Redirect the consumer to the ACS URL* +
include::{root}/include/3-d-secure/3-d-secure-2-acs-url-redirect.adoc[]
+

. *Check-payer-response* (optional) +
include::{root}/include/3-d-secure/3-d-secure-2-check-payer-response.adoc[]
+
NOTE: It is not required to include the fields ``periodic-type`` and ``sequence-type`` in the check-payer-response. 
+

. *Authorization-only* (zero amount) + 
include::{root}/include/3-d-secure/3-d-secure-2-authorization.adoc[]
+
CAUTION: Set the ``periodic-type`` to ``ci`` (consumer-initiated) and the ``sequence-type`` to ``first``.
endif::[]


ifndef::env-nova[]
[#API_CC_3DS2_UseCases_AddingCardOnFile_DuringPurchase]
==== Option 2: Storing Credit Card Details - During Purchase

The 3D Secure 2 fields can be found in the <<CC_3DS2_fields, 3D Secure 2 field table>>. 
ifdef::env-wirecard[]
They are also included in the <<Appendix_Xml, REST API payment XSD>>.
endif::[]

. *Check-enrollment* (payment amount) +
include::{root}/include/3-d-secure/3-d-secure-2-check-enrollment.adoc[]
+
CAUTION: For 3D Secure 2 consumer-initiated one-click checkout, include the field ``three-d/version`` and set its value to ``2.1``. Set ``challenge-indicator`` to ``04``. Set the ``periodic-type`` to ``ci`` (consumer-initiated) and the ``sequence-type`` to ``first``.
+
As a result of the check-enrollment, you receive the ``PAReq`` with the ACS URL.
+
NOTE: This is a transaction used to sign a card-on-file agreement. Therefore, Strong Customer Authentication is required. Exemptions do not apply.
+

. *Redirect the consumer to the ACS URL* +
include::{root}/include/3-d-secure/3-d-secure-2-acs-url-redirect.adoc[]
+

. *Check-payer-response* (optional) +
include::{root}/include/3-d-secure/3-d-secure-2-check-payer-response.adoc[]
+
NOTE: It is not required to include the fields ``periodic-type`` and ``sequence-type`` in the check-payer-response. 
+

. *Authorization* (payment amount) + 
include::{root}/include/3-d-secure/3-d-secure-2-authorization.adoc[]
+
CAUTION: Set the ``periodic-type`` to ``ci`` (consumer-initiated) and the ``sequence-type`` to ``first``.
+

. *Capture-authorization* (payment amount) +
include::{root}/include/3-d-secure/3-d-secure-2-capture-authorization.adoc[]
+
CAUTION: For subsequent transactions that use stored card details, set the ``periodic-type`` to ``ci`` (consumer-initiated) and the ``sequence-type`` to ``recurring``.


'''
endif::[]