ifndef::env-nova[] 
[#API_CC_3DS2_UseCases_StoringCCDetails]
== Consumer-Initiated (CI) One-Click Checkout
// == Consumer-Initiated Card-On-File Transactions

For card-on-file transactions, merchants store the consumer's card details (as a token) for future transactions. Thus, when the consumer returns to the merchant's shop, they do not need to re-enter their details.

For example, a consumer creates an account with an online shop and provides their credit card details upon registration. At the moment of registration, no money is transferred. If the consumer wants to buy goods at a later point in time, they can do so by using the one-click checkout feature. Re-entering their card details is not necessary.

WARNING: Before storing credentials on file, consumers must be clearly informed how the credentials will be used in the future. Obtain the consumers' consent.

[NOTE]
====
Authentication required: Yes +
Card-on-file flagging required: Yes
====
endif::[]


ifndef::env-nova[]
[#API_CC_3DS2_UseCases_AddingCardOnFile_IndependentOfPayment]
=== Option 1: Storing Card Details - Independent of Payment

pass:[<a href="resources/3-d-secure-2/usecase_pm-collection/adding-card-on-file.postman_collection.json" target="_blank" rel="noreferrer noopener" download>Download a Postman collection for this use case here.</a>] 

The 3D Secure 2 fields can be found in the <<3DS2_Fields, 3D Secure 2 field table>>. 
ifdef::env-wirecard[]
They are also included in the <<Appendix_Xml, REST API payment XSD>>.
endif::[]

. *Check-enrollment* (zero amount) +
include::{root}/include/3-d-secure/3-d-secure-2-authentication-transactions-check-enrollment.adoc[]
+
CAUTION: For 3D Secure 2 consumer-initiated one-click checkout:
--
- Include the field ``three-d/version`` and set its value to ``2.1``.
- Set the ``challenge-indicator`` to ``04``.
- Set the ``periodic-type`` to ``ci`` (consumer-initiated) and the ``sequence-type`` to ``first``. 
- Include the field ``merchant-tokenization-flag`` and set its value to ``true``.
--
+
include::{root}/include/3-d-secure/3-d-secure-2-authentication-transactions-check-enrollment-response.adoc[]
+

. *Redirect the consumer to the ACS URL* +
include::{root}/include/3-d-secure/3-d-secure-2-authentication-transactions-acs-url-redirect.adoc[]
+

. *Check-payer-response* (optional) +
include::{root}/include/3-d-secure/3-d-secure-2-authentication-transactions-check-payer-response.adoc[]
+
NOTE: It is not required to include the fields ``periodic-type`` and ``sequence-type`` in the check-payer-response. 
+

. *Authorization-only* (zero amount) +
include::{root}/include/3-d-secure/3-d-secure-2-authorization-transaction.adoc[]
+
CAUTION: Set the ``periodic-type`` to ``ci`` (consumer-initiated) and the ``sequence-type`` to ``first``. Include the field ``merchant-tokenization-flag`` and set its value to ``true``. 
endif::[]


ifndef::env-nova[]
[#API_CC_3DS2_UseCases_AddingCardOnFile_DuringPayment]
=== Option 2: Storing Card Details - During Payment

The 3D Secure 2 fields can be found in the <<3DS2_Fields, 3D Secure 2 field table>>. 
ifdef::env-wirecard[]
They are also included in the <<Appendix_Xml, REST API payment XSD>>.
endif::[]

. *Check-enrollment* (payment amount) +
include::{root}/include/3-d-secure/3-d-secure-2-authentication-transactions-check-enrollment.adoc[]
+
CAUTION: For 3D Secure 2 consumer-initiated one-click checkout:
--
- Include the field ``three-d/version`` and set its value to ``2.1``.
- Set the ``challenge-indicator`` to ``04``.
- Set the ``periodic-type`` to ``ci`` (consumer-initiated) and the ``sequence-type`` to ``first``. 
- Include the field ``merchant-tokenization-flag`` and set its value to ``true``.
--
+
include::{root}/include/3-d-secure/3-d-secure-2-authentication-transactions-check-enrollment-response.adoc[]
+
NOTE: This is a transaction used to sign a card-on-file agreement. Therefore, Strong Customer Authentication is required. Exemptions do not apply.
+

. *Redirect the consumer to the ACS URL* +
include::{root}/include/3-d-secure/3-d-secure-2-authentication-transactions-acs-url-redirect.adoc[]
+

. *Check-payer-response* (optional) +
include::{root}/include/3-d-secure/3-d-secure-2-authentication-transactions-check-payer-response.adoc[]
+
NOTE: It is not required to include the fields ``periodic-type`` and ``sequence-type`` in the check-payer-response. 
+

. *Authorization* (payment amount) +
include::{root}/include/3-d-secure/3-d-secure-2-authorization-transaction.adoc[]
+
CAUTION: Set the ``periodic-type`` to ``ci`` (consumer-initiated) and the ``sequence-type`` to ``first``. Include the field ``merchant-tokenization-flag`` and set its value to ``true``. 
+

. *Capture-authorization* (payment amount) +
include::{root}/include/3-d-secure/3-d-secure-2-capture-authorization-transaction.adoc[]
+
CAUTION: For subsequent transactions that use stored card details, set the ``periodic-type`` to ``ci`` (consumer-initiated) and the ``sequence-type`` to ``recurring``.
// +
// ====
// For subsequent transactions that use stored card details, set the ``periodic-type`` to ``ci`` (consumer-initiated) and the ``sequence-type`` to ``recurring``.

// The merchant-tokenization-flag=true should be present in the Authorization of the Subsequent transaction.

// ====

endif::[]

//-