[#API_CC_3DS2_UseCases_General_MultiParty_Commerce]
== General Multi-Party Commerce

In general multi-party commerce, a consumer buys a product or service from a merchant. At the time of purchase, the consumer acquires an additional product or service provided by a different merchant. This merchant charges for the additional product or service. For example, a consumer purchases a washing machine and, in addition, a breakdown and repair insurance.

[NOTE]
====
Authentication required: Yes + 
Card-on-file flagging required: Yes/No
====

pass:[<a href="<resources/3-d-secure-2/usecase_pm-collection/general-multi-party-commerce.postman_collection.json>" target="_blank" rel="noreferrer noopener" download>Download Postman collection here.</a>]

The 3D Secure 2 fields can be found in the <<CC_3DS2_fields, 3D Secure 2 field table>>. 
ifndef::env-nova[]
They are also included in the <<Appendix_Xml, REST API payment XSD>>.
endif::[]

. *check-enrollment* 
+
--
include::{root}/include/3-d-secure/3-d-secure-2-authentication-transactions-check-enrollment.adoc[] 
--
+
. _Redirect the consumer to the ACS URL_
+
--
include::{root}/include/3-d-secure/3-d-secure-2-authentication-transactions-redirect.adoc[] 
--
+
. *check-payer-response* (optional)
+
--
include::{root}/include/3-d-secure/3-d-secure-2-authentication-transactions-check-payer-response.adoc[] 
--
+
. *authorization*
+
--
include::{root}/include/3-d-secure/3-d-secure-2-authorization-transaction.adoc[] 
--
+
. *capture-authorization*
+
--
include::{root}/include/3-d-secure/3-d-secure-2-capture-authorization-transaction.adoc[] 
--
+
. *authorization*
+
--
new include file containing info on this type of auth. 
--
+
NOTE: This step authorizes the remaining amount due for/(to the merchant providing) the additional product or service.
+
. *capture-authorization*
+
--
include::{root}/include/3-d-secure/3-d-secure-2-capture-authorization-transaction.adoc[] 
--
+
NOTE: This step captures the remaining amount due for/(to the merchant providing) the additional product or service.


//-





