[#API_CC_3DS2_UseCases_General_MultiParty_Commerce]
== General Multi-Party Commerce

In general multi-party commerce, a consumer buys a product or service from a primary, consumer-facing merchant. At the time of purchase, the consumer acquires an additional product or service provided by a secondary, non-consumer facing merchant. This merchant charges for the additional product or service. +
For example, a consumer purchases a washing machine (from the primary merchant) and a breakdown and repair insurance (from the secondary merchant).


[NOTE]
====
Authentication required: Yes 
====

pass:[<a href="resources/3-d-secure-2/usecase_pm-collection/general-multi-party-commerce.postman_collection.json" target="_blank" rel="noreferrer noopener" download>Download Postman collection here.</a>]

The 3D Secure 2 fields can be found in the <<CC_3DS2_fields, 3D Secure 2 field table>>. 
ifndef::env-nova[]
They are also included in the <<Appendix_Xml, REST API payment XSD>>.
endif::[]

. *check-enrollment* 
+
include::{root}/include/3-d-secure/3-d-secure-2-authentication-transactions-check-enrollment.adoc[] 
+
include::{root}/include/3-d-secure/3-d-secure-2-authentication-transactions-check-enrollment-response.adoc[] 
+
NOTE: Only the primary merchant must perform the authentication, for the full amount.

. _Redirect the consumer to the ACS URL_
+
include::{root}/include/3-d-secure/3-d-secure-2-authentication-transactions-acs-url-redirect.adoc[] 

. *check-payer-response* (optional)
+
include::{root}/include/3-d-secure/3-d-secure-2-authentication-transactions-check-payer-response.adoc[] 

. *authorization*
+
include::{root}/include/3-d-secure/3-d-secure-2-authorization-transaction.adoc[] 
+
NOTE: This step authorizes the amount due for the primary product or service (e.g. the washing machine).

. *capture-authorization*
+
include::{root}/include/3-d-secure/3-d-secure-2-capture-authorization-transaction.adoc[] 
+
NOTE: This step captures the amount due for the primary product or service (e.g. the washing machine).

. *authorization*
+
NOTE: This step authorizes the remaining amount due for the additional product or service (e.g. the breakdown and repair insurance). +
The check-enrollment is not required prior to this request, as merchant-initiated transactions are out of scope for SCA. To mark this transaction as merchant-initiated, set the ``authorization-reason`` request field to ``reauthorization``.

. *capture-authorization*
+
NOTE: This step captures the remaining amount due for the additional product or service (e.g. the breakdown and repair insurance).

//-





