ifndef::env-nova[] 
[#API_CC_3DS2_UseCases_CIOneClickCheckout]
== One-Click Checkout

For one-click checkout transactions, merchants store the consumer's card details (as a token) for future transactions. If the consumer wants to buy goods at a later point in time, they can do so without having to re-enter their card details.

Card details can be either stored <<API_CC_3DS2_UseCases_CIOneClickCheckout_IndependentOfPayment, independently of a payment>> or <<API_CC_3DS2_UseCases_CIOneClickCheckout_DuringPayment, during a payment>>.

. **Independent of payment:** A consumer creates an account with an online shop and provides their credit card details upon registration. At the moment of registration, no money is transferred.
. **During payment:** The credit card details are stored during the consumer's first checkout.

//-

// For one-click checkout transactions, merchants store the consumer's card details (as a token) for future transactions. Thus, when the consumer returns to the merchant's shop, they do not need to re-enter their details.

// If the consumer wants to buy goods at a later point in time, they can do so by using the one-click checkout feature. Re-entering their card details is not necessary.

WARNING: Before storing card details on file, consumers must be clearly informed how they will be used in the future. Obtain the consumers' consent.

[NOTE]
====
Authentication required: Yes +
Card-on-file flagging required: Yes
====
endif::[]

ifndef::env-nova[]
[#API_CC_3DS2_UseCases_CIOneClickCheckout_IndependentOfPayment]
=== Option 1: One-Click Checkout - Independent of Payment
//=== Option 1: Storing Card Details - Independent of Payment

pass:[<a href="resources/3-d-secure-2/usecase_pm-collection/one-click-checkout_independend_of_payment.postman_collection.json" target="_blank" rel="noreferrer noopener" download>Download a Postman collection for this option here.</a>] 

The 3D Secure 2 fields can be found in the <<3DS2_Fields, 3D Secure 2 field table>>. 
ifdef::env-wirecard[]
They are also included in the <<Appendix_Xml, REST API payment XSD>>.
endif::[]

. *Check-enrollment* (initial transaction, zero amount) +
include::{root}/include/3-d-secure/3-d-secure-2-authentication-transactions-check-enrollment.adoc[]
+
[CAUTION]
====
- Include the field ``three-d/version`` and set its value to ``2.1``.
- Set the ``challenge-indicator`` to ``04``.
- Set the ``periodic-type`` to ``ci`` (consumer-initiated) and the ``sequence-type`` to ``first``. 
- Include the field ``merchant-tokenization-flag`` and set its value to ``true``.
====
+
include::{root}/include/3-d-secure/3-d-secure-2-authentication-transactions-check-enrollment-response.adoc[]
+

. *Redirect the consumer to the ACS URL* +
include::{root}/include/3-d-secure/3-d-secure-2-authentication-transactions-acs-url-redirect.adoc[]
+

. *Check-payer-response* (optional) +
include::{root}/include/3-d-secure/3-d-secure-2-authentication-transactions-check-payer-response.adoc[]
+
NOTE: It is not required to include the fields ``periodic-type`` and ``sequence-type`` in the check-payer-response. 
+

. *Authorization-only* (zero amount) +
include::{root}/include/3-d-secure/3-d-secure-2-authorization-transaction.adoc[]
+
[CAUTION]
====
- Set the ``periodic-type`` to ``ci`` (consumer-initiated) and the ``sequence-type`` to ``first``. 
- Include the field ``merchant-tokenization-flag`` and set its value to ``true``.
====
+

. *Check-enrollment* (subsequent transaction, payment amount) +
include::{root}/include/3-d-secure/3-d-secure-2-authentication-transactions-check-enrollment.adoc[]
+
[CAUTION]
====
- Include the field ``three-d/version`` and set its value to ``2.1``.
- Set the ``periodic-type`` to ``ci`` (consumer-initiated) and the ``sequence-type`` to ``recurring``. 
- Include the field ``merchant-tokenization-flag`` and set its value to ``true``.
====
+
NOTE: It is not required to set the ``challenge-indicator`` to ``04``.
+
include::{root}/include/3-d-secure/3-d-secure-2-authentication-transactions-check-enrollment-response.adoc[]
+

. *Redirect the consumer to the ACS URL* +
include::{root}/include/3-d-secure/3-d-secure-2-authentication-transactions-acs-url-redirect.adoc[]
+

. *Check-payer-response* (optional) +
include::{root}/include/3-d-secure/3-d-secure-2-authentication-transactions-check-payer-response.adoc[]
+
NOTE: It is not required to include the fields ``periodic-type`` and ``sequence-type`` in the check-payer-response. 
+

. *Authorization* (payment amount) +
include::{root}/include/3-d-secure/3-d-secure-2-authorization-transaction.adoc[]
+
[CAUTION]
====
- Set the ``periodic-type`` to ``ci`` (consumer-initiated) and the ``sequence-type`` to ``recurring``. 
- Include the field ``merchant-tokenization-flag`` and set its value to ``true``.
====
+

. *Capture-authorization* (payment amount) +
include::{root}/include/3-d-secure/3-d-secure-2-capture-authorization-transaction.adoc[]
+
NOTE: It is not required to include the fields ``periodic-type`` and ``sequence-type`` in the capture-authorization.
endif::[]


ifndef::env-nova[]
[#API_CC_3DS2_UseCases_CIOneClickCheckout_DuringPayment]
=== Option 2: One-Click Checkout - During Payment
//=== Option 1: Storing Card Details - During Payment

pass:[<a href="resources/3-d-secure-2/usecase_pm-collection/one-click-checkout_during_payment.postman_collection.json" target="_blank" rel="noreferrer noopener" download>Download a Postman collection for this option here.</a>] 

The 3D Secure 2 fields can be found in the <<3DS2_Fields, 3D Secure 2 field table>>. 
ifdef::env-wirecard[]
They are also included in the <<Appendix_Xml, REST API payment XSD>>.
endif::[]

. *Check-enrollment* (initial transaction, payment amount) +
include::{root}/include/3-d-secure/3-d-secure-2-authentication-transactions-check-enrollment.adoc[]
+
[CAUTION]
====
- Include the field ``three-d/version`` and set its value to ``2.1``.
- Set the ``challenge-indicator`` to ``04``.
- Set the ``periodic-type`` to ``ci`` (consumer-initiated) and the ``sequence-type`` to ``first``. 
- Include the field ``merchant-tokenization-flag`` and set its value to ``true``.
====
+
include::{root}/include/3-d-secure/3-d-secure-2-authentication-transactions-check-enrollment-response.adoc[]
+
NOTE: This is a transaction used to sign a card-on-file agreement. Therefore, Strong Customer Authentication is required. Exemptions do not apply.
+

. *Redirect the consumer to the ACS URL* +
include::{root}/include/3-d-secure/3-d-secure-2-authentication-transactions-acs-url-redirect.adoc[]
+

. *Check-payer-response* (optional) +
include::{root}/include/3-d-secure/3-d-secure-2-authentication-transactions-check-payer-response.adoc[]
+
NOTE: It is not required to include the fields ``periodic-type`` and ``sequence-type`` in the check-payer-response. 
+

. *Authorization* (payment amount) +
include::{root}/include/3-d-secure/3-d-secure-2-authorization-transaction.adoc[]
+
[CAUTION]
====
- Set the ``periodic-type`` to ``ci`` (consumer-initiated) and the ``sequence-type`` to ``first``. 
- Include the field ``merchant-tokenization-flag`` and set its value to ``true``.
====
+

. *Capture-authorization* (payment amount) +
include::{root}/include/3-d-secure/3-d-secure-2-capture-authorization-transaction.adoc[]
+
NOTE: It is not required to include the fields ``periodic-type`` and ``sequence-type`` in the capture-authorization.
+

. *Check-enrollment* (subsequent transaction, payment amount) +
include::{root}/include/3-d-secure/3-d-secure-2-authentication-transactions-check-enrollment.adoc[]
+
[CAUTION]
====
- Include the field ``three-d/version`` and set its value to ``2.1``.
- Set the ``periodic-type`` to ``ci`` (consumer-initiated) and the ``sequence-type`` to ``recurring``. 
- Include the field ``merchant-tokenization-flag`` and set its value to ``true``.
====
+
[NOTE]
====
- The ``token-id`` can be used instead of the ``account-number``.
- It is not required to set the ``challenge-indicator`` to ``04``.
====
+
include::{root}/include/3-d-secure/3-d-secure-2-authentication-transactions-check-enrollment-response.adoc[]
+

. *Redirect the consumer to the ACS URL* +
include::{root}/include/3-d-secure/3-d-secure-2-authentication-transactions-acs-url-redirect.adoc[]
+

. *Check-payer-response* (optional) +
include::{root}/include/3-d-secure/3-d-secure-2-authentication-transactions-check-payer-response.adoc[]
+
NOTE: It is not required to include the fields ``periodic-type`` and ``sequence-type`` in the check-payer-response. 
+

. *Authorization* (payment amount) +
include::{root}/include/3-d-secure/3-d-secure-2-authorization-transaction.adoc[]
+
[CAUTION]
====
- Set the ``periodic-type`` to ``ci`` (consumer-initiated) and the ``sequence-type`` to ``recurring``. 
- Include the field ``merchant-tokenization-flag`` and set its value to ``true``.
====
+

. *Capture-authorization* (payment amount) +
include::{root}/include/3-d-secure/3-d-secure-2-capture-authorization-transaction.adoc[]
+
NOTE: It is not required to include the fields ``periodic-type`` and ``sequence-type`` in the capture-authorization.
endif::[]

//-