
==== Datatypes

This table shall help to merge a large variety of datatypes, used in individual documentation drafts, to a minimal set of datatypes which are explained in the documentation. 

For WPG the six datatypes "Boolean", "Timestamp", "String", "Decimal", "Number" and "Enumeration" are sufficient to determine the data types in use.

.When documenting field tables for WPG, please use the datatypes given in column 1:

[cols=".^15,.^30,.^55"]
|===
h| Datatype (to be used) h|Alternative Datatypes + 
                         (not to be used in documentation) h| Additional Data Types with special context / Description

|  Boolean | "True/False" +
             "Boolean"  | 
| Timestamp | "yyyyMMddHHmmss" +
               "Timestamp" +
               "Date time"  | 
| String | "Alphabetic, Numeric and Special Characters" +
            "ASCII String" +
            "String (Cardinal Number)" +
            "xs:string" +
            "Text" +
            "String" +
            "Alphanumeric" | Contains also "String with pattern value". +
                             In individual documentation drafts it might be referred to as: +
                             "xs:token" (e.g. "card-security-code" (only 3 to 4 digits 0-9) or request-id, which is a String 1-10 characters) +
                             If there is a pattern value (mostly according to an ISO norm) please provide the pattern with the ISO norm in the description column. +
                             "0/1" +
                             "Y/N" +
                             "api-id" +
                             "uuid" +
                             "url" +
| Decimal | "Decimal" +
            "Numeric" +
            "Integer" | "Integer" maps with "Decimal", if it *allows* decimal places.
| Number | "Number" +
           "xs:short" +
           "Integer" | "Integer" maps with "Number", if it *does't allow* decimal places.
| Enumeration | "Enumeration" +
                "Enum"  | "xs:token", if used as enumeration
| Link to child table | "Complex type" | 
|===