[#Home]
== Home

[#Home_WirecardPaymentGateway]
[discrete]
=== {payment-gateway} - Documentation

Welcome to the {payment-gateway} documentation,
which offers you technical details, integration examples and
additional information for integrating and using Wirecard Payment
solutions for your e-commerce business.

[#Home_ProductDemo]
[discrete]
=== Product Demo


If you are about to choose our Wirecard solutions for your online shop,
you may want to have a look at our <<PPv2_WirecardDemoShop, Wirecard Demo Shop>> first.
Give it a try and become familiar with the wide range of features that the Wirecard solutions offer.

[#Home_ShopSystems]
[discrete]
=== Integration into Shop Systems

If you use a shop system for your online shop you can integrate our
Wirecard solutions by simply installing one of our shop extensions. We
offer these free of charge as open-source shop extensions for many shop
systems.

Please visit <<ShopSystems, Shop Systems>>
for further information on the currently existing shop
extensions.

[#Home_DirectIntegrations]
[discrete]
=== Direct Integrations

If you use a shop system and no shop extension or shop integration is
available, or if you need full flexibility and control within the payment
processes, you are able to do a so-called "direct integration" of our
payment products into your shop system. Please be aware that depending
on the product you choose, at least a little programming effort on your part is required.

[#Home_PaymentPageSolutions]
[discrete]
==== Payment Page Solutions

Hosted Payment Page (HPP) and Embedded Payment Page (EPP) excel through
their simple and easy integration into your online shop. The complete
payment process for credit card payments and many other payment methods
can be added to your shop system.

For details and information regarding the integration into your online
shop head over to <<PaymentPageSolutions, Payment Page Solutions>>.

[#Home_Seamless]
[discrete]
==== Seamless Payments for Credit Card Transactions

If you want to offer your consumers a seamless payment experience for
credit card payments, consider using the seamless payment page
integration.

For details on this product head over to <<PaymentPageSolutions, Payment Page Solutions>>.

[#Home_PaymentSDKs]
[discrete]
==== Payment SDKs

[#Home_iOSAndroid]
[discrete]
===== iOS and Android

To add payment functionality to your native apps developed for iOS or
Android, we can offer you a <<MobilePaymentSDK, mobile Payment SDK>> for payment methods like Credit Card, PayPal, Apple Pay or
SEPA Direct Debit.

[#Home_PHP]
[discrete]
===== PHP

We offer a https://github.com/wirecard/paymentSDK-php[PHP Payment SDK] to ease the integration of Seamless Payment Page (SPP) and various
payment methods including their follow-up operations for all types of
shop systems which are based on PHP.

[#Home_RESTAPI]
[discrete]
==== REST API

If you would like to implement a tight integration of our payment
gateway into your online shop, please have a look on our 
<<RestApi, REST API>> which enables you the implementation of sophisticated payment
processes and so-called back-end operations where you are able to
integrate captures, refunds or cancellations to your back-end e-commerce
systems.

[#Home_PaymentMethod]
[discrete]
=== Payment Method Details

Certain payment methods we offer require specific integration, set-up,
or configuration steps. For such payment methods, you may need to undergo
an external registration and set-up process on the website of the
corresponding financial service provider, or consider configuration-specific
requirements in terms of functionality, payment workflows, or
country-specific availability.


////
Some of the payment methods we offer require specific integration steps
or an external registration and setup process on the website of the
corresponding financial service provider.
Additionally for some payment
methods specific requirements regarding functionality, payment workflows
and country-specific availability have to be considered.
////

<<PaymentMethods, Here>> you can find all payment methods we offer.

[#Home_GeneralPlatformFeatures]
[discrete]
=== General Platform Features

Our {payment-gateway} offers you a lot of specific
features which enable you to implement sophisticated and professional
functionality within your online shop and all of your payment
processes. 

Please have a look on our overview and details regarding
these <<GeneralPlatformFeatures, General Platform Features>>.

[#Home_FraudPrevention]
[discrete]
=== Fraud Prevention

In addition to many payment methods, we can offer you services regarding
detecting and reducing fraudulent situations within your online shop.
For this purpose you are able to use our <<FraudPrevention_AVS, Address Verification System>>,
<<FraudPrevention_DeviceFingerprinting, Device Fingerprinting>> and our
<<FraudPrevention_FPS, Fraud Prevention Suite>>.

[#Home_BatchProcessing]
[discrete]
=== Batch Processing

If you require the batch processing of multiple transactions in one
step, please use our <<BatchProcessingApi, Batch Processing API>>, which is capable of processing the following payment
methods:

- Credit Card
- SEPA Direct Debit and SEPA Credit Transfer

//-

[#Home_Reporting]
[discrete]
=== Reporting

To manage, control or review your transactions in your online shop, we
can offer you <<Reporting_DataReconciliation, Data Reconciliation>> and
<<Reporting_IcFeeReport, IC Fee Reports>>.

[#Home_Glossary]
[discrete]
=== Glossary

Our <<Glossary, Glossary>> contains
definitions and explanations of the most common terms and technical
expressions used in this documentation.

[#Home_PartnerProgram]
[discrete]
=== Wirecard Partner Program

Teamwork and partnerships are the foundation of our success! We invite
you to participate in our success by becoming a partner of Wirecard. We
are looking for integration partners, project partners and sales
partners.

Please visit http://partner.wirecard.com/[partner.wirecard.com] for
further information and to get in contact with us.

[#Home_ContactInformation]
[discrete]
=== Contact Information

If you have any questions or need further assistance please do not
hesitate to <<ContactUs, contact our support and sales teams>>.

[#Home_Questions]
[discrete]
=== Do You Have any Questions or Suggestions?

If you notice any inconsistencies or ambiguities in our
documentation or you find that important information
that you need is missing here, please <<ContactUs, contact>>
our technical documentation team via sales or support. Your comments and
suggestions are greatly appreciated and will help improving our
solutions and their documentation.
