[#Home]
== Home

[discrete]
=== Document Center - Wirecard Payment Gateway

Welcome to the Document Center of our Wirecard Payment Gateway,
which offers you technical details, integration examples and
additional information for integrating and using Wirecard Payment
solutions for your e-commerce business.

[discrete]
=== Product Demo

If you are about to choose our Wirecard solutions for your online shop
you may want to first have a look at our 
<<WPP_WirecardDemoShop, Wirecard Demo Shop>>.
There you can gain a first impression and become familiar
with the product features.

[discrete]
=== Integration into Shop Systems

If you use a shop system for your online shop you can integrate our
Wirecard solutions by simply installing one of our shop plugins. We
offer these free of charge as open-source shop plugins for many shop
systems.

Please visit 
<<ShopSystems, Shop Systems>>
for further information on the currently supported shop
plugins.

[discrete]
=== Direct Integrations

If you use a shop system and no shop plugin or shop integration is
available or if you need full flexibility and control within the payment
processes you are able to do a so-called "direct integration" of our
payment products into your shop system. Please be aware that depending
on the product you need at least a little programming effort is needed.

[discrete]
==== Payment Page Solutions

Hosted Payment Page (HPP) and Embedded Payment Page (EPP) excel through
their simple and easy integration into your online shop. The complete
payment process for credit card payments and many other payment methods
can be added to your shop system with only a minimum of integration
effort.

For details and information regarding the integration into your online
shop head over to
<<PaymentPageSolutions, Payment Page Solutions>>.

[discrete]
==== Seamless Payments for Credit Card Transactions

If you want to offer your consumers a seamless payment experience for
credit card payments, consider using the seamless payment page
integration.

For details on this product head over to
<<PaymentPageSolutions, Payment Page Solutions>>.

[discrete]
==== Payment SDKs

[discrete]
===== iOS and Android

To add payment functionality to your native apps developed for iOS or
Android, we can offer you a 
<<MobilePaymentSDK, mobile Payment SDK>> for payment methods like Credit Card, PayPal, Apple Pay or
SEPA Direct Debit.

[discrete]
===== PHP

We offer a https://github.com/wirecard/paymentSDK-php[PHP Payment SDK] to ease the integration of Seamless Payment Page (SPP) and various
payment methods including their follow-up operations for all types of
shop systems which are based on PHP.

[discrete]
==== REST API

If you would like to implement a tight integration of our payment
gateway into your online shop, please have a look on our 
<<RestApi, REST API>> which enables you the implementation of sophisticated payment
processes and so-called back-end operations where you are able to
integrate captures, refunds or cancellations to your back-end e-commerce
systems.

[discrete]
=== Payment Method Details

Some of the payment methods we offer require specific integration steps
or an external registration and setup process on the website of the
corresponding financial service provider. Additionally for some payment
methods specific requirements regarding functionality, payment workflows
and country-specific availability have to be considered.

<<PaymentMethods, Here>> you can find all payment methods we offer.
//- I adapted this sentence as we do not differentiate between credit card and alterative payment methods anymore,
//- also we remove the differentiation credit/debit card


[discrete]
=== General Platform Features

Our Wirecard Payment Gateway offers you a lot of specific
features which enable you to implement sophisticated and professional
functionality within your online shop and all of your payment
processes. 

Please have a look on our overview and details regarding
these <<GeneralPlatformFeatures, General Platform Features>>.

[discrete]
=== Fraud Prevention

In addition to many payment methods, we can offer you services regarding
detecting and reducing fraudulent situations within your online shop.
For this purpose you are able to use our 
<<FraudPrevention_AVS, Address Verification System>>,
<<FraudPrevention_DeviceFingerprinting, Device Fingerprinting>> and our
<<FraudPreventions_FPS, Fraud Prevention Suite>>.

[discrete]
=== Batch Processing

If you require the batch processing of multiple transactions in one
step, please use our 
<<BatchProcessingApi, Batch Processing API>>, which is capable of processing the following payment
methods:

- Credit Card
- SEPA Direct Debit and SEPA Credit Transfer

//-

[discrete]
=== Reporting

To manage, control or review your transactions in your online shop, we
can offer you 
<<Reporting_DataReconciliation, Data Reconciliation>> and
<<Reporting_IcFeeReport, IC Fee Reports>>.

[discrete]
=== Glossary

Our 
<<Glossary, Glossary>>
contains
definitions and explanations of the most common terms and technical
expressions used in this Document Center and is arranged in alphabetical
order.

[discrete]
=== Wirecard Partner Program

Teamwork and partnerships are the foundation of our success! We invite
you to participate in our success by becoming a partner of Wirecard. We
are looking for integration partners, project partners and sales
partners.

Please visit http://partner.wirecard.com/[partner.wirecard.com] for
further information and to get in contact with us.

[discrete]
=== Contact Information

If you have any questions or need further assistance please do not
hesitate to 
<<ContactUs, contact our support and sales teams>>.

[discrete]
=== Do You Have any Questions or Suggestions?

Should you notice any inconsistencies or ambiguities in our
documentation or if you find that here is important information missing
that you need, please 
<<ContactUs, contact>>
our technical documentation team via sales or support. Your comments and
suggestions will be greatly appreciated and will help improving our
solutions and their documentation.
