[#WhatsNew]
== What's New?

[#WhatsNew_2019_03]
[discrete]
=== 2019-03

.2019-03-29
- <<Paylib, Paylib>> - New payment method available for REST API.
- <<ShopSystems, Shop Systems>> - New language: French documentation available for WooCommerce, Magento 2, PrestaShop, and Shopify.
- <<ShopSystems, Shop Systems>> - New Wirecard Shopify App available.

//-

.2019-03-27
- <<GooglePay, Google Pay>> - New payment method available for REST API.

//-

.2019-03-26
- <<ShopSystems, Shop Systems>> - New payment methods Alipay Cross-border, Guaranteed Invoice by payolution, Guaranteed Invoice by Wirecard, Masterpass, Payment In Advance, Payment On Invoice, and UnionPay International available for Magento 1.
- <<ShopSystems, Shop Systems>> - New feature One-Click Checkout for Credit Card available for Magento 1.

//-

.2019-03-22
- <<CreditCard_3DS2, Credit Card>> - Updated general information on 3-D Secure 2.
- <<WPP_CC_3DS2Fields, Credit Card with WPP>> - Added 3-D Secure 2 fields table.
- <<PaymentPageSolutions_WPP_HPP_Integration, Hosted Payment Page>> - Updated HPP Integration Guide for Wirecard Payment Page.
- <<PaymentPageSolutions_WPP_EPP_Integration, Embedded Payment Page>> - Updated EPP Integration Guide for Wirecard Payment Page.
- <<WPP_Seamless_Integration, Seamless Mode>> - Updated Seamless Integration Guide for Wirecard Payment Page.
- <<PP_3DSecure_2_Fields, Payment Page>> - Added 3-D Secure 2 fields table (NVP) for Payment Page integrations.

//-

.2019-03-18
- <<CreditCard_3DS2, Credit Card>> - Added general information on 3-D Secure 2.
- <<CreditCard_PSD2, Credit Card>> - Added general information on PSD2.
- <<CreditCard_Fields, Credit Card>> - Updated field table to include 3-D Secure 2 fields.
- <<Appendix_Xml, XML Schema Specification>> - Updated payment XSD.

//-

.2019-03-07
- <<WPP_Seamless_Integration, Seamless Mode>> - Updated Seamless Mode Integration Guide.

//-

[#WhatsNew_2019_02]
[discrete]
=== 2019-02

.2019-02-20
- <<ShopSystems, Shop Systems>> - New payment methods eps-Überweisung, giropay, iDEAL, Maestro SecureCode and Pay by Bank app available for Magento 1.

//-

.2019-02-19
- <<PaymentPageSolutions_WPP_EPP_Integration, Embedded Payment Page>> - Updated EPP Integration Guide.

//-

.2019-02-08
- <<WPP_Bancontact, Bancontact with WPP>> - New payment method available for Wirecard Payment Page.

//-

.2019-02-05
- <<CreditCard_TransactionTypes_Authorization, Credit Card>> - New description for REST API transaction type _authorization_.
- <<CreditCard_TransactionTypes_CaptureAuthorization, Credit Card>> - New description for REST API transaction type _capture-authorization_.

//-

.2019-02-04
- <<WPP_ideal, iDEAL with WPP>> - Added Handelsbanken and Moneyou to list of participating
banks.
- <<iDEAL, iDEAL>> - Added Handelsbanken and Moneyou to list of participating banks.

//-

.2019-02-01
- <<ShopSystems, Shop Systems>> - New Wirecard Magento 1 Extension available.

//-

[discrete]
[#WhatsNew_2019_01]
=== 2019-01

.2019-01-29
- <<ShopSystems, Shop Systems>> - New payment method Pay by Bank app available for WooCommerce.

//-

.2019-01-28
- <<PaymentPageSolutions, Payment Page Solutions>> - New feature responsive design for Payment Page.

//-

.2019-01-25
- <<ShopSystems, Shop Systems>> - New payment method Pay by Bank app available for Magento 2.
- <<CreditCard_TransactionTypes, Credit Card>> - Introduction to REST API transaction types.
- <<CreditCard_TransactionTypes_Purchase, Credit Card>> - New description for REST API transaction type _purchase_.

//-

.2019-01-23
- <<PaymentPageSolutions_WPP_HPP_NVP, Merchants Integrated with NVP (HPP)>> - Updated
documentation for Wirecard Payment Page.
- <<PaymentPageSolutions_WPP_EPP_NVP, Merchants Integrated with NVP (EPP)>> - Updated
documentation for Wirecard Payment Page.

//-

.2019-01-21
- <<PPSolutions_WPP_WPPSecurity, WPP Security>> - Updated documentation for Wirecard Payment Page.
- <<WPP_Features, WPP Features>> - Updated documentation for Wirecard Payment Page.
- <<WPP_paybox, paybox with WPP>> - New payment method available for Wirecard Payment Page.

//-

.2019-01-18
- <<WPP_Seamless, Seamless Mode>> - Updated documentation for Wirecard Payment Page.

//-

.2019-01-17
- <<POLi, POLi>> - Updated test credentials for REST API.
- <<AppendixK, Appendix K: Test Access Data and Credentials>> - Updated credit card expiration dates.
- <<StatusCodes_Test, Status Code Test>> - Updated credit card expiration dates.

//-

.2019-01-10
- <<PaymentMethods, Non Credit Card Payment Methods>> - Updated test credential structure of 34 Alternative Payment Methods for REST API.

//-

.2019-01-09
- <<ShopSystems, Shop Systems>> - New payment method eps-Überweisung available for WooCommerce.

//-

.2019-01-08
- <<PaymentPageSolutions_WPP_EPP, Embedded Payment Page>> - Updated documentation for Wirecard Payment Page.
- <<PaymentPageSolutions_WPP_HPP_Integration, Hosted Payment Page Integration>> - Updated documentation for Wirecard Payment Page.

//-

[#WhatsNew_2018_12]
[discrete]
=== 2018-12

.2018-12-24
- <<CreditCard_Fields_OrderItems, Credit Card field list>> - Added order-items for REST API.
- <<RestApi_Fields, REST API Field List>> - Added order-items for REST API.

//-

.2018-12-20
- <<GuaranteedInvoiceandDirectDebit, Guaranteed Invoice by Wirecard and Direct Debit>> - Removed Guaranteed Installments from REST API.

//-

.2018-12-18
- <<GuaranteedInvoiceandDirectDebit_ConsenttoGeneralTermsandConditions, Guaranteed Invoice by Wirecard and Direct Debit>> - Updated guidelines for General Terms and Conditions.
- <<PaymentPageSolutions_WPP_HPP, Hosted Payment Page>> - Updated documentation for Wirecard Payment Page.

//-

.2018-12-11
- <<Sofort, Sofort.>> - New feature Bank Name for REST API.

//-

.2018-12-10
* <<API_PayPal_Fields_Payment_customfields, PayPal>> - New features PayPal Address Check and PayPal Seller Protection for REST API.
//-

.2018-12-05
- <<ShopSystems, Shop Systems>> - New languages: Indonesian, Japanese, Korean, Simplified
Chinese, Traditional Chinese. For Magento 2, OpenCart, PrestaShop, WooCommerce.

//-

[#WhatsNew_2018_11]
[discrete]
=== 2018-11

.2018-11-30
- <<PaymentPageSolutions_WPP_HPP_Integration, HPP Integration>> - Added PHP integration demo for Wirecard Payment Page (Hosted Payment Page).
- <<PaymentPageSolutions_WPP_EPP_Integration, EPP Integration>> - Added PHP integration demo for Wirecard Payment Page (Embedded Payment Page).
- <<WPP_Seamless_Integration, Integrating WPP in Seamless Mode>> - Added PHP integration demo for Wirecard Payment Page (Seamless Mode).
- <<ShopSystems, Shop Systems>> - Updated information how to add more payment methods to
Wirecard Shop Extensions.

//-

.2018-11-29
- <<WPP_PayPal, PayPal with WPP>> - Updated documentation for Wirecard Payment Page.
- <<PPSolutions_WPP_WPPSecurity, WPP Security>> - Updated signature verification example (C#) for Wirecard
Payment Page.
- <<PP_RedirectUrlsIPNs, Redirect URLs and IPNs>> - Updated description for Payment Page.

//-

.2018-11-28
- <<ShopSystems, Shop Systems>> - New payment method giropay available for Magento 2.
- <<ShopSystems, Shop Systems>> - New payment method eps-Überweisung available for Shopware.

//-

.2018-11-27
- <<WPP_SEPADirectDebit, SEPA Direct Debit with WPP>> - Updated documentation for Wirecard Payment Page.
- <<WPP_ideal, iDEAL with WPP>> - Updated documentation for Wirecard Payment Page.
- <<ShopSystems, Shop Systems>> - Added information on Wirecard PHP Payment SDK.
- <<BatchProcessingApi_SEPATransactions, Batch Processing API>> - Added REST API credentials for SEPA test system.

//-

.2018-11-26
- <<WPP_Sofort, Sofort. with WPP>> - Updated documentation for Wirecard Payment Page.

//-

.2018-11-19
- <<Klarna_phoneNumberValidation, Klarna Guaranteed Invoice and Installments>> - Added format requirements for
phone numbers for REST API.
- <<PPSolutions_WPP_WPPSecurity, WPP Security>> - Updated signature verification example (Java) for Wirecard
Payment Page.

//-

.2018-11-18
- <<ContactUs, Contact Us>> - New page with contact information.

//-

.2018-11-05
- <<paysafecard, paysafecard>> - Updated test credentials and samples for REST API.

//-

[discrete]
[#WhatsNew_2018_10]
=== 2018-10

.2018-10-31
- <<WPP_P24, Przelewy24 with WPP>> - New payment method available for Wirecard Payment Page.
- <<CarrierBilling, Carrier Billing>> - Updated test credentials and samples for REST API.
- <<API_AlipayCrossBorder_Features_autoDebit, Alipay Cross-border>> - New feature auto-debit available on REST API.

//-

.2018-10-29
- <<WPP_paysafecard, paysafecard with WPP>> - New payment method available for Wirecard Payment Page.

//-

.2018-10-26
- <<WPP_eps, eps with WPP>> - New payment method available for Wirecard Payment Page.
- Apple Pay - Updated test credentials for REST API.

//-

.2018-10-23
- <<POLi, POLi>> - Updated XML samples for REST API.
- <<Trustly, Trustly>> - Updated test credentials and samples for REST API.
- <<StatusCodes, Status Codes and Transaction Statuses>> - Updated number format of response
codes in example for REST API.

//-

.2018-10-20
- <<WPP_Features_PaybyLink, Pay by Link>> - Updated documentation for Wirecard Payment Page.

//-

[#builddate]
.Build Date
{systemtimestamp}

//-
