[#GeneralIntegrationOptions]
== General Integration Options

There are four different integration paths available for Wirecard's
Payment Processing Gateway.

[NOTE]
====
- The integration via *Payment Page* is described under <<PP, Payment Page>>.
- For (near) real-time processing the *backend* implementation is
described under <<RestApi, REST API>>. However, the
description of payment methods, for example, is common for both Payment
Page and REST
API.                                                                                                                                                                                                     
- Processing of multiple transactions using *batches* is described under
<<BatchProcessingApi, Batch Processing API>>, available
for both SEPA Direct Debit and SEPA Credit Transfer
- Via *Payment SDK* which offers a seamless user experience by rendering
a payment form as an integral part of merchant’s mobile application. 
//-
====

[#GeneralIntegrationOptions_PP]
=== Payment Page

Wirecard's Payment Page solutions stand for secure, flexible, easy and
transparent payment processing. It provides all payment methods and
related options in one solution: Credit Card (with/without 3D
secure), SEPA, online banking payments, mobile payments, alternative
payment methods, and industry-specific solutions.

It handles the payment method selection as well as the collection
of payment details or consumer redirects to alternative payment provider
sites. With this solution, the merchant is only required to conform to a
limited PCI scope (self-questionnaire A).

Wirecard's Payment Page is available in three formats:

- Hosted Payment Page (HPP): The consumer is redirected to
Wirecard's server to finish the checkout process.
- Embedded Payment Page (EPP): The payment screen is displayed in
overlay directly on the merchant's checkout page.
- Seamless integration:  The merchant's checkout page is incorporated
into Wirecard's payment form. This solution provides a seamless shopping
experience for web-shoppers.
//-

NOTE: Only HTML knowledge is required for Payment Page integration.

[#GeneralIntegrationOptions_RestApi]
=== REST API

When using the integration option _REST API_, merchants want full
control over the checkout and payment process and they don’t mind
integration efforts and PCI compliance. Requests are constructed by the
merchant and are sent over HTTPS protocol to _Wirecard's Payment
Gateway_ end-point where the REST API is exposed.

Integration is possible by:

- XML requests sent from merchant's backend (server-to-server)
- JSON respectively
- NVP (for credit card only)
//-

NOTE: For the integration of _Wirecard's Payment Gateway_ via REST API,
advanced programming skills are required.

PCI certified merchants can use Wirecard's REST API without any
restrictions.

Non PCI certified merchants can use Wirecard's REST API only with
referenced or recurring transactions. For initial transactions they must
use a front end solution (e.g. <<PP, HPP>>).

Details to integrate _Wirecard's Payment Gateway_ via REST API are
described <<RestApi, here>>.

[#GeneralIntegrationOptions_Batch]
=== Batch Processing API

In order to process multiple transactions at the same time, Wirecard's
Batch Processing is the ideal solution for both fast and easy to
implement offline bulk transaction processing.

Batch processing is possible for the following payment methods:

- SEPA Direct Debit
- SEPA Credit Transfer
- Credit Card

//-

NOTE: Working programming knowledge is required to integrate this way.

[#GeneralIntegrationOptions_SDK]
=== SDK

The Software Development Kit (SDK) serves as a wrapper for the Wirecard
Payment Processing Gateway with a PCI V3 compliant native mobile payment
form. SDK is naturally developed for the integration into a merchant's
app as a software library where it covers sending payment requests to
the payment gateway. It uses REST requests constructed by the merchant
sent over HTTPS protocol to Wirecard Payment Gateway
end-point where the REST API is exposed.

The following payment methods are currently supported:

- Credit Card 
- PayPal
- SEPA Direct Debit
- Apple Pay
//-

Operation system interfaces:

- iOS
- Android
//-

NOTE: Working programmer knowledge is required to integrate this way.
