[#PPD_ManageThemes]
===== Managing Themes

Use the Themes Manager to edit and organize your <<, themes>> and translations.
// link to PPD (when branch 397 is available at staging).

. Open the Payment Page Designer. 
// link to PPD (when branch 397 is available at staging)
. Click *Login*.
. Use your credentials provided by Merchant Support to access the Themes Manager.

WARNING: Make sure that only one user is editing a theme. If two users edit a theme at the same time, some changes might get lost.

NOTE: A session timeout requires a relogin to the Themes Manager after 60 minutes of inactivity.

The Themes Manager is divided in two sections:

* *Translations*

In this section you can modify existing translations or add translations for other languages. 

* *Themes*

In this section you can: 

- Create new themes +
- Import themes +
- Modify themes +
- Change the default theme +
- Delete themes +

[#PPD_ManageThemes_HowTo]
====== How to Use the Themes Manager

[#PPD_ManageThemes_HowTo_ManageTranslations]
.Manage Translations

When you expand the *Translations* section, you see the *Import translations* and *Export default translations* buttons, and a list of uploaded translations.

In the *Translations* section you can: 

- Import a translation file (the translation file must be available in .json format)
- Edit the default translation file (click *Export default translations* to export the translation to a .json file)

NOTE: You cannot add other languages. You can only edit the languages available in the default translation file. You can modify the translations to meet local variations such as US-English or UK-English.

In the translations list, click the translation file to expand the translation's properties.

Now you can:

- Edit the translation file name (double-click the file name or click the *Edit* button)
- Edit the translation (*Export translation* exports the translation to a .json file)
- Delete the translation file

[#PPD_ManageThemes_HowTo_ManageThemes]
.Manage Themes

When you expand the *Themes* section, you see the *Create New Theme* and *Import Theme* buttons, and a list of saved themes.

In the *Themes* section you can:

- Create a new theme
// link to PPS (when branch 397 is available at staging)
- Import themes (the theme file must be available in .json format)

In the themes list: 

- Click the *Theme preview* button on the right of the theme name to see a preview (it is displayed as a .jpg and can be downloaded)
- Click the theme name to expand the theme's properties (active themes can be identified by the tick symbol displayed next to them)

When the properties are displayed, you can:

- Edit the theme name (double-click the theme name or click the *Edit* button).
- Select a <<PPD_ManageThemes_HowTo_ManageTranslations, translation file>> 
- Set the theme as default (the default theme will be used for payment processes if not indicated otherwise <<PPD_ManageThemes_Sample, in a request>>)
- Activate or deactivate the theme (only activated themes can be used in a request)
- Change the theme settings (click *Style it* to open the theme in the Payment Page Designer menu) 

NOTE: You can toggle between the Payment Page Designer menu and the Themes Manager. Use *MANAGE* in the Payment Page Designer to return to Themes Manager, and *BACK TO DESIGNER* to return to the Payment Page Designer menu. +
If *Style it* is unavailable in the Themes Manager, the theme is already open in the Payment Page Designer. 

- Save your changes (*Save* is available only if there are new changes)
- Export the theme to a .json file
- Delete the theme

[#PPD_ManageThemes_Field]
.Use a Theme in a Request

[%autowidth]
|===
| Field Name | Data Type | JSON Parent | Description

| theme | String | options ({ }) | The name of the PPD theme used for a specific payment process.
|===


[#PPD_ManageThemes_Sample]
.A Request Example With a Theme
//must be provided by Ronald

[source,json,subs=attributes+]
----
include::[]
----



//// 
[#PaymentPageDesigner_UsingThemes]
===== Using Themes

You can select any theme you have saved in Payment Page Designer as the default one. Each time the payment page loads, it will show that particular theme.
If you want to use a different theme for a payment (other than your default), you need to specify this in the request.

[%autowidth]
|===
| Field Name | Data Type | JSON Parent | Description

| theme | String | options ({ }) | The name of the PPD theme used for a specific payment process.
|===

[NOTE]
====
The value of `theme` is the name under which you saved the theme you want to use in Payment Page Designer.

You can access default theme settings in Payment Page Designer. If you do not send this field in the request, the default theme is used.
====

If you customize and save a theme in PPD under the name `test-theme` and then use it for a payment, the request looks like this:

.An Example Request w/ Theme

[source,json,subs=attributes+]
----
include::samples/json/PaymentPageDesignerUsingThemes_AnExampleRequestWTheme.json[]
----
////