[[page]]
[[main]]
[[main-header]]
[[breadcrumb-section]]
1.  link:index.html[API merchant specification]
2.  link:API-merchant-specification_1146901.html[API merchant
specification]
3.  link:Payment-Page-Solutions_4751423.html[Payment Page Solutions]
4.  link:Wirecard-Payment-Page_3704201.html[Wirecard Payment Page]
5.  link:Seamless-Mode_3704231.html[Seamless Mode]

[[title-heading]]
[[title-text]] API merchant specification : Merchants Integrated with
NVP (Seamless Mode)
------------------------------------------------------------------------------------------

[[content]]
Created by Volker Hauss, last modified by Bruno Tall on Jun 12, 2018

[[main-content]]
Merchants who integrated the previous payment page using NVP can also
use seamless mode, with a few changes of function names. The integration
is otherwise identical to the JSON version.

*1. Update the `paymentPageLoader` JavaScript library in
your `<head>` HTML code with the new `paymentPage.js`:*

[source,syntaxhighlighter-pre]
----
<script src="https://wpp.wirecard.com/loader/paymentPage.js" type="text/javascript"></script>
----

*2. Use the NVP version of the "render" function:*

[source,syntaxhighlighter-pre]
----
WPP.seamlessRender({
        url: {payment-redirect-url}, // this is the payment link returned in response to your initial api/payment/register request from step 1
        wrappingDivId: "seamless-form-target",
        onSuccess: function (response) {
          // called when seamless form is successfully rendered
        },
        onError: function (errResp) {
          // called if seamless form failed to render
        }
      });
----

*3. The "submit" function is the same for both types:*

[source,syntaxhighlighter-pre]
----
WPP.seamlessSubmit({
            onSuccess: function (response) {
            // called when seamless form data is successfully submitted
            },
            onError: function (response) {
            //called when data submission fails
            }
          });
----

Naturally, you do not send a backend request at the beginning with NVP,
instead you include all the payment information inside
`requestData `like in your old integration. +
 

[[footer]]
Document generated by Confluence on Mar 11, 2019 10:04

[[footer-logo]]
http://www.atlassian.com/[Atlassian]
