[#PPD_{payment-page-v2-anchor}-Manager]
===== {payment-page-v2} Manager

With the <<PPD_customize, Payment Page Designer>> you can design individual user interfaces for your {payment-page-v2}. +
You can have more than one user interface available. +
You can save each interface as a theme. +
Use the {payment-page-v2-abbr} Manager to edit and organize your themes and translations.

. Open the https://designer-test.{domain}[Payment Page Designer]. 
. Click *Login*.
. Use your credentials provided by Merchant Support to access the {payment-page-v2-abbr} Manager.

//-

WARNING: Make sure that only one user is editing a theme. If two users edit a theme at the same time, some changes might get lost.

NOTE: A session timeout requires a relogin to the {payment-page-v2-abbr} Manager after 60 minutes of inactivity.

The {payment-page-v2-abbr} Manager is divided in three sections:

* *Selected User*
* *Translations*
* *Themes*


[#PPD_{payment-page-v2-anchor}-Manager_Change_User]
.Selected User

Expand the *Selected User* section to change the user

[#PPD_{payment-page-v2-anchor}-Manager_Translations]
.Translations

Expand the *Translations* section to: 

* Import a translation file (the translation file must be available in .json format) +
* Edit the default translation file (click *Export default translations* to export the translation to a .json file) +
* Edit imported translations +
** Edit the translation file name (double-click the file name or click the *Edit* button) +
** Edit the translation (click *Export* to export the translation to a .json file) +
** Delete the translation file

//-

Here are two examples why you want to modify the translations: 

* Meet local variations such as US-English or UK-English +
* Change button names

//-

NOTE: You cannot add other languages. You can only edit the languages available in the default translation file.

[#PPD_{payment-page-v2-anchor}-Manager_Themes]
.Themes

Expand the *Themes* section to:

* Create a <<PPD_customize, new theme>> +
* Import a theme  (the theme file must be available in .json format) +
* Edit a theme +
* Change the default theme +
* Delete a theme +

//-

In the *Themes* section, you see the *Create New Theme* and *Import Theme* buttons, and a list of imported themes.

In the themes list: 

* Click the *Theme preview* button on the right of the theme name to see a preview (it is displayed as a .jpg and can be downloaded)
* Click the theme name to expand the theme's properties (active themes can be identified by the tick symbol displayed next to them)

When the properties are expanded, you can:

* Edit the theme name (double-click the theme name or click the *Edit* button).
* Select a <<PPD_{payment-page-v2-anchor}-Manager_Translations, translation file>> 
* Set the theme as default (the default theme will be used for payment processes if not indicated otherwise <<PPD_{payment-page-v2-anchor}-Manager_Sample, in a request>>)
* Activate or deactivate the theme (only activated themes can be used in a request)
* Change the theme settings (click *Style it* to open the theme in the Payment Page Designer menu) 

NOTE: You can toggle between the Payment Page Designer menu and the {payment-page-v2-abbr} Manager. Use *MANAGE* in the Payment Page Designer to return to {payment-page-v2-abbr} Manager, and *BACK TO DESIGNER* to return to the Payment Page Designer menu. +
If *Style it* is unavailable in the {payment-page-v2-abbr} Manager, the theme is already open in the Payment Page Designer. 

* Save your changes (*Save* is available only if there are new changes)
* Export the theme to a .json file
* Delete the theme

[#PPD_{payment-page-v2-anchor}-Manager_Field]
.Use a Theme in a Request

[%autowidth]
|===
| Field Name | Data Type | JSON Parent | Description

| theme | String | options ({ }) | The name of the PPD theme used for a specific payment process.
|===


[#PPD_{payment-page-v2-anchor}-Manager_Sample]
.A Request Example With a Theme

[source,json,subs=attributes+]
----
include::samples/json/PaymentPageDesignerUsingThemes_AnExampleRequestWTheme.json[]
----

//-