[#PP_EPP_Workflow]
===== Embedded Payment Page Workflow

The following image shows the Embedded Payment Page workflow.

.Embedded Payment Page workflow
[Embedded Payment Page Workflow]
[mermaid,PP_EPP_v2_Workflow,svg,subs=attributes+]
----
sequenceDiagram
    participant Consumer
    participant Payment page embedded in merchant site
    participant Payment Gateway
    participant Financial Institution
        Consumer ->> Payment page embedded in merchant site: 1
        Payment page embedded in merchant site ->> Payment Gateway: 2
        Payment Gateway -->> Payment page embedded in merchant site: 3
        Payment page embedded in merchant site ->> Payment Gateway: 4
        Payment Gateway ->> Financial Institution: 5
    	Financial Institution -->> Payment Gateway: 5
        Payment Gateway -->> Payment page embedded in merchant site: 6
        Payment page embedded in merchant site -->> Payment page embedded in merchant site: 7
        Payment page embedded in merchant site -->> Consumer: 8
----

. Consumer checks out with the purchased goods/services.
. _{payment-gateway}_ validates the signature and
returns the list of payment methods for which the merchant has been
configured with the associated redirect URL.
. The payment page displays the payment methods from which the
consumer may choose. Depending on the chosen payment method and the
respective specifics of this payment method, the payment page then
displays the relevant input fields.
+
NOTE: This payment method selection may optionally be skipped based on the
merchant's account configuration.
+
. The payment page posts the payment transaction to the _{payment-gateway}._
. The _{payment-gateway}_ processes the payment with the respective
financial institution.
. The _{payment-gateway}_ returns the final response to the payment page,
which is a digitally signed response message.
. The payment page posts the digitally signed response back to the
merchant's success or failure URL.
. Optionally, the merchant's system validates the signature, and
decodes the response message. Finally, the consumer (the consumer's
browser) is redirected to the merchant's cancel or processing page and
then onto success or failure page by the pPayment page response.

//-
