include::shortcuts.adoc[]

[#PPv2_CustomizedDisplayText]
===== Customized Display Text

_Customized Display Text_ is an optional feature available for two of our _{payment-page-v2}_ modes:

- the _Hosted Payment Page_ (HPP) and 
- the _Embedded Payment Page_ (EPP). 
//-

This feature allows you personalize your checkout process with a brief message to your consumer.

To enable _Customized Display Text_, add ``customized-display-text`` in the initial POST request and insert a short text (see <<PPv2_CustomizedDisplayText_ExampleRequest, example request>> below). 

The insterted text then appears on the payment page (for HPP) or in the iframe (EPP). 

Per default payment page and iframe displays the first four lines of your text. 

If the defined text requires more than four lines consumers click the chevrons (marked red in the screenshot) to expand the field.

Format your text with any of these three HTML formatting options: 

- <b> *bold* </bold>, 
- <i> _italic_ </i>, 
- <br> line break.
//-

NOTE: The text is limited to 1024 characters. +
_Customized Display Text_ is a single-language feature: the text will always be displayed in the same language.


[#PPv2_CustomizedDisplayText_TestCredentials]
====== Test Credentials

Test credentials for _Customized Display Text_

[cols="35h,65"]
|===
| URI (Endpoint)
|``\https://{pp-test-instance-hostname}/api/payment/register``
| Merchant Account ID (MAID)
| 7a6dd74f-06ab-4f3f-a864-adc52687270a
| Username
| 70000-APIDEMO-CARD
| Password
| ohysS0-dvfMx
|===

[#PPv2_CustomizedDisplayText_ExampleRequest]
====== Example Request

[cols="15,10,10,55"]
|===
| Field (JSON) | Data Type | JSON Parent | Description

| ``customized-display-text``
| String 
| options ({ })
| Includes a customized display text on the payment page / in the iframe. For Hosted and Embedded Payment Page.
|===

[source,json,subs=attributes+]
----
include::samples/json/PPv2_Feature_CustomizedDisplayText.json[]
----


//-