[#PPv2_Features_LimitCardBrands]
===== Limit Credit Card Brands

The _Limit Card Brand_ option allows the merchant to display only those credit card brands which he prefers to charge.

[TIP]
.An example situation:
====
The merchant wants to display only those credit card brands to the consumer which are locally popular. +
In that case the merchant can use the _Limit Card Brand_ option to provide an individual list of credit card brands on {payment-page-v2-abbr}.
====

[NOTE]
.Use the _Limit Card Brand_ option with a transaction:
====
Add the ``credit-card-brand-filter`` field to the payment request and list the credit card brands in a desired order. +
Please have a look at the supported <<AppendixD, card brands>> you can choose from.
If you use the _Limit Card Brand_ option, you must list all the card brands you want to display. The asterisk (*) cannot be used as a shortcut.
====

[cols="v,,,"]
[%autowidth]
|===
| Field | Data Type | Parent |Description

| credit-card-brand-filter | String | options (\{ }) | Displays the available credit card brands in the {payment-page-v2-abbr} in the order specified in this field.
|===

[#PPv2_Features_LimitCardBrands_Configure]
[discrete]
====== Configure the _Limit Card Brand_ option

Rules to configure the _Limit Card Brand_ option:

* The _Limit Card Brand_ option is available in JSON only
* Send the _Limit Card Brand_ option with each request
* Create a Java Script Array
** List the card brand names in the array in the desired order
** Separate the payment methods with a comma

//-

.Example Request w/ the _Limit Card Brand_ option
[source,json,subs=attributes+]
----
include::samples/json/WPP_FeaturesLimitCardbrandConfiguringLimitCardbrand_ExampleRequestLimitCardbrand.json[]
----
