[#PP_PaymentMethods]
==== Payment Methods

.Credit Card
For a short introduction see <<CreditCard_Introduction, Credit Card>>

.Alipay Cross Border
For a short introduction see <<API_AlipayCrossBorder_Introduction, Alipay Cross Border>>

.Bancontact Mister Cash
For a short introduction see <<BancontactMisterCash_Introduction, Bancontact Mister Cash>>

.CIMB clicks
For a short introduction see <<CIMBClicks_Introduction, CIMB Clicks>>

.eps-Überweisung
For a short introduction see <<eps_Introduction, eps-Überweisung>>

.FPX
For a short introduction see <<FPX, FPX>>

.giropay
For a short introduction see <<giropay_Introduction, giropay>>

.Guaranteed Direct Debit
For a short introduction see <<GuaranteedDirectDebit_Introduction, Guaranteed Direct Debit>>

.Guaranteed Invoice by Wirecard
For a short introduction see <<GuaranteedInvoice_Introduction, Guaranteed Invoice by Wirecard>>

.iDEAL
For a short introduction see <<iDEAL_Introduction, iDEAL>>

.MasterPass
For a short introduction see <<API_MasterPass_Introduction, MasterPass>>

.Maybank2u
For a short introduction see <<Maybank2u_Introduction, Maybank2u>>

.mobicred
For a short introduction see <<mobicred_Introduction, mobicred>>

.MOLPay
For a short introduction see <<MOLPay_Introduction, MOLPay>>

.moneta.ru
For a short introduction see <<monetaRu_Introduction, moneta.ru>>

.Pay by Bank app (Zapp)
For a short introduction see <<API_PaybyBankapp_Introduction, Pay by Bank app (Zapp)>>

.paybox
For a short introduction see <<paybox_Introduction, paybox>>

.paydirekt
For a short introduction see <<paydirekt_Introduction, paydirekt>>

.Payolution Invoice and Installment
For a short introduction see <<payolution_Introduction, payolution>>

.PayPal
For a short introduction see <<API_PayPal_Introduction, PayPal>>

.paysafecard
For a short introduction see <<paysafecard_Introduction, paysafecard>>

.Przelewy24
For a short introduction see <<Przelewy24_Introduction, Przelewy24>>

.SafetyPay
For a short introduction see <<SafetyPay_Introduction, SafetyPay>>

.SEPA DD (B2C)
For a short introduction see <<SEPADirectDebit, SEPA Direct Debit>>.

Look for differences between <<SEPADirectDebit_Fields_SpecificFields_B2B, B2B and B2C>>.

.Sofort.
For a short introduction see <<Sofort_Introduction, Sofort.>>

.Trustly
For a short introduction see <<Trustly_Introduction, Trustly>>

.TrustPay
For a short introduction see <<TrustPay_Introduction, TrustPay>>

.VISA Checkout
For a short introduction see <<VISACheckout_Introduction, VISA Checkout>>

.WeChat QR Pay
For a short introduction see <<API_WeChatQRPay_Introduction, WeChat QR Pay>>

.Wirecard Voucher
For a short introduction see <<WirecardVoucher_Introduction, Wirecard Voucher>>

//-
