[#PP_HPP_Workflow]
===== Hosted Payment Page Workflow

The Hosted Payment Page (HPP) provides a generic workflow available for
various payment methods.

NOTE: The following workflow mainly describes the flow of a credit card payment. For
alternative payment methods (e.g. _PayPal_), there will be an additional
re-direct to a provider.

.Hosted Payment Page: Credit card payment flow
[HPP Workflow]
[mermaid,PP_HPP_v2_Workflow,svg,subs=attributes+]
----
sequenceDiagram
    participant A as Consumer
    participant B as Merchants System
    participant C as Hosted Payment Page
    participant D as Payment Gateway
    participant E as Financial Institution
        A ->> B: 1
        B ->> C: 2
        C ->> D: 3
	    D -->> C: 4
        C ->> D: 5
        D ->> E: 6
        D -->> C: 7
        C -->> B: 8
        B -->> A: 9
----

. Consumer checks out with the purchased goods/services.
. Merchant system redirects to the Hosted Payment Page URL with a
digitally signed payment request.
. _{payment-gateway}_ validates the signature and
returns the list of payment methods for which the merchant has been
configured with the associated redirect URL.
. The Hosted Payment Page displays the payment methods from which the
consumer may choose. Depending on the chosen payment method and the
respective specifics of this payment method, the Hosted Payment Page
then displays the relevant input fields.
+
NOTE: This payment method selection may optionally be skipped based on the
merchant's account configuration.

+
. The Hosted Payment Page posts the payment transaction to the _{payment-gateway}._
. _{payment-gateway}_ processes the payment with the
respective financial institution.
. _{payment-gateway}_ returns the final response to
the payment page, which is a digitally signed response message.
. The payment page posts the digitally signed response back to the
merchant's success or failure URL.
. Optionally, the merchant's system validates the signature, and
decodes the response message.
. Finally, the consumer (the consumer's
browser) is redirected to the merchant's success or failure shop page
by the payment page response.

//-





