[#Seamless_CardFormIntegration]
===== Card Form Integration
This use-case covers the payment form displayed directly on the merchant's checkout page for a seamless user experience (no browser redirects).

[#Seamless_CardFormIntegration_RenderForm]
====== Render Form

Merchant renders the form into element on their checkout page. The
transaction details are specified in ``requestData``. The element is
identified by ``wrappingDivId`` parameter.

[source,js]
----
var requestData = {
  "request_id" : "217c3832-8575-c1d5-0e3a-2fa08003b0fd",
  "request_time_stamp" : "20190403095835",
  "merchant_account_id" : "61e8c484-dbb3-4b69-ad8f-706f13ca141b",
  "transaction_type" : "purchase",
  "requested_amount" : "2.00",
  "requested_amount_currency" : "EUR",
  "ip_address" : "127.0.0.1",
  "request_signature" : "43fd8c261a8fdad693024c7cc009239ad344f1e5716de0c3163237b5392d5700",
  "payment_method" : "creditcard"
};
WirecardPaymentPage.seamlessRenderForm({
  requestData : requestData,
  wrappingDivId : "seamless-target",
  onSuccess : processSucceededResult,
  onError : processErrorResult
});
----

NOTE: Use a unique Request ID for each request

.Transaction Data received from onSuccess callback of seamlessRenderForm()
[source,json]
----
{
  "ip_address": "127.0.0.1",
  "merchant_account_id": "61e8c484-dbb3-4b69-ad8f-706f13ca141b",
  "request_id": "217c3832-8575-c1d5-0e3a-2fa08003b0fd",
  "requested_amount": "2.00",
  "requested_amount_currency": "EUR",
  "status_code_1": "201.0000",
  "status_description_1": "The resource was successfully created.",
  "status_severity_1": "information",
  "transaction_id": "5ff1cf52-8471-11e5-95ea-005056b13376",
  "transaction_state": "success",
  "transaction_type": "check-signature"
}
----

[#Seamless_CardFormIntegration_SubmitForm]
====== Submit Form

Merchant assigns the call function to a pay button on the checkout page.
``requestData`` are optional when submitting form. They will be merged with
data from the first step. Form input is validated before the submit.

[source,js]
----
WirecardPaymentPage.seamlessSubmitForm({
  onSuccess : processSucceededResult,
  onError : processErrorResult
});
----

.Transaction Data received from onSuccess callback of seamlessSubmitForm()
[source,json]
----
{
  "api_id": "elastic-api",
  "authorization_code": "153620",
  "completion_time_stamp": "20151106103540",
  "first_name": "John",
  "ip_address": "127.0.0.1",
  "last_name": "Doe",
  "masked_account_number": "444433******1111",
  "merchant_account_id": "61e8c484-dbb3-4b69-ad8f-706f13ca141b",
  "payment_method": "creditcard",
  "provider_transaction_id_1": "8ee6e543-c96f-459a-a379-50d0e9152fd3",
  "request_id": "217c3832-8575-c1d5-0e3a-2fa08003b0fd",
  "requested_amount": "2.00",
  "requested_amount_currency": "EUR",
  "self": "https://test-api.wirecard.com:9000/engine/rest/merchants/61e8c484-dbb3-4b69-ad8f-706f13ca141b/payments/1fe8a33a-8472-11e5-95ea-005056b13376",
  "status_code_1": "201.0000",
  "status_description_1": "3d-acquirer:The resource was successfully created.",
  "status_severity_1": "information",
  "token_id": "4186409015611111",
  "transaction_id": "1fe8a33a-8472-11e5-95ea-005056b13376",
  "transaction_state": "success",
  "transaction_type": "purchase"
}
----
