[#PP_PaymentSelection]
==== Payment Selection

The payment page displays the payment method selection screen if the
field “payment_method” is left out or left empty and more than one
payment method is configured for the merchant in Wirecard´s Payment
Processing Gateway. It may be used to display all available payment
methods or the list of displayed payment methods may be narrowed down by
specifying the value of field “transaction_type” to “authorization” or
"debit".

[[PaymentSelection-Automaticpaymentmethodselection]]
===== Automatic Payment Method Selection

The payment page supports automatic selection of payment methods in
order to bypass the payment method selection screen. Simply set
“payment_method” in the initial payment request to force the selection
of a specific payment method. You can also specify several Payment
Methods in the request to offer methods to select.

[[PaymentSelection-Prepopulationofconsumerinformation]]
===== Prepopulation of Consumer Information

The payment page supports prepopulation of consumer information to
reduce or eliminate consumer data entry. Consumer information such as
name, order and address information can be sent within the initial
payment request. The payment page will use these values as default,
which can be manually overridden.

[[PaymentSelection-Creditcardtransactions]]
===== Credit Card Transactions

When processing credit card transactions via the payment page, there is
an option to avoid the rendering of the payment page. Subsequent
processing redirects such as 3-D secure are automatically handled. To
enable SilentPay processing the merchant must pass the following fields
within the initial payment request:

- account_number
- holder_last_name
- card_type
- card_security_code
- expiration_year
- expiration_month

//-

 

 

 

 

[[footer]]
Document generated by Confluence on Feb 19, 2019 13:36

[[footer-logo]]
http://www.atlassian.com/[Atlassian]
