[#PP_EPP_Workflow]
===== Embedded Payment Page Workflow

The following image shows the Embedded Payment Page workflow.

.Embedded Payment Page workflow
[Embedded Payment Page Workflow]
[mermaid,PP_EPP_Workflow,svg,subs=attributes+]
----
sequenceDiagram
    participant A as Consumer
    participant B as EPP
    participant C as {payment-gateway}
    participant D as Financial Institution
        A ->> B: 1. checks out
        B ->> C: 2.a validates signature
        C ->> B: 2.b returns list of payment methods
        C -->> B: 3. displays payment methods
        B ->> C: 4. posts payment transaction
        C ->> D: 5. processes payment
    	  D -->> C: 
        C -->> B: 6. returns final response
        B -->> B: 7. posts digitally signed response
        opt 1
        B -->> B: 8. validates signature
        B -->> B: decodes response
        end
        B -->> A: redirectes to success or failure page
----

. Consumer checks out with the purchased goods/services.
. _{payment-gateway}_ validates the signature and
returns the list of payment methods for which the merchant has been
configured with the associated redirect URL.
. The payment page displays the payment methods from which the
consumer may choose. Depending on the chosen payment method and the
respective specifics of this payment method, the payment page then
displays the relevant input fields.
+
NOTE: This payment method selection may optionally be skipped based on the
merchant's account configuration.
+
. The payment page posts the payment transaction to the _{payment-gateway}._
. The _{payment-gateway}_ processes the payment with the respective
financial institution.
. The _{payment-gateway}_ returns the final response to the payment page,
which is a digitally signed response message.
. The payment page posts the digitally signed response back to the
merchant's success or failure URL.
. Optionally, the merchant's system validates the signature, and
decodes the response message. Finally, the consumer (the consumer's
browser) is redirected to the merchant's cancel or processing page and
then onto success or failure page by the Payment page response.

//-
