[#PPv2_Features_SortFilter]
===== Sort or Filter Payment Methods

The _Sort or Filter_ option allows the merchant to sort or filter the available payment methods in an individual way.

[TIP]
.An example situation:
====
The merchant wants to guide the consumer to use a preferred payment method. +
In that case the merchant can use the _Sort or Filter_ option to provide an individual list of payment methods on {payment-page-v2-abbr}.
====

[NOTE]
.Use the _Sort or Filter_ option with a transaction:
====
Add the ``payment-method-order-and-filter`` field to the payment request and list the paymenent methods in a desired order. +
Misspellings or unavailable payment methods are ignored. {payment-page-v2-abbr} will display the full list of available payment methods instead.
====

[cols="v,,,"]
[%autowidth]
|===
| Field | Data Type | Parent |Description

| payment-method-order-and-filter | String | options (\{ }) | Displays the available payment methods in the {payment-page-v2-abbr} in the order specified in this field.
|===

[#PPv2_Features_SortFilter_Configure]
[discrete]
====== Configure the _Sort or Filter_ option

Rules to configure the _Sort or Filter_ option:

* The _Sort or Filter_ option is available in JSON only
* Send the _Sort or Filter_ option with each request
* Create a Java Script Array
** List the payment method names in the array in the desired order
** Separate the payment methods with a comma
** Use an asterisk (*) as a place holder (the asterisk will list all the available payment methods in an alphabetical order)
** Combine payment method names and an asterisk (list your most popular payment methods by name and add an asterisk for the remaining ones)

//-

.Example Request w/ the _Sort or Filter_ option
[source,json,subs=attributes+]
----
include::samples/json/WPP_FeaturesSortFilterConfiguringSortFilter_ExampleRequestSortFilter.json[]
----
