[#PPD_ManageThemes]
===== Managing Themes

With the Themes Manager you can manage your <<, themes>> and translations.
// link to PPD (when branch 397 is available at staging).

WARNING: Please make sure that only one editor is editing a theme. If two editors are editing a theme at the same time, some changes will be lost.

NOTE: A session timeout requires a relogin to the Themes Manager after 60 minutes of inactivity.

In the *Translations* section you can modify existing translations or add translations for addional languages. 

In the *Themes* section you can 

- create new themes +
- import themes +
- modify themes +
- change the default theme +
- delete themes +
//-
and much more.

[#PPD_ManageThemes_HowTo]
====== How to use the Themes Manager

. Open the Payment Page Designer. 
// link to PPD (when branch 397 is available at staging)
. Click *Login*.
. Use your access credentials, provided by Merchant Support to access the Themes Manager.

[#PPD_ManageThemes_HowTo_ManageTranslations]
.Manage Translations

You can see the buttons *Import translations* and *Export default translations* and a list of uploaded translations.

With the Translations Manager you can 

- import a translation file. The translation file must be available in json format.
- edit the default translation file. *Export default translations* exports the translation to a json file, then edit the file in a text editor and reimport it.

NOTE: You cannot add additonal languages. You can only edit the languages available in the default translation file. You can modify the translations to meet local variations such as US-English vs UK-English.

In the translations list, click the document icon to drop down the translation's properties.

Now you can

- edit the translation's name (click the notepad icon).
- edit the translation. *Export translation* exports the translation to a json file, then edit the file in a text editor and reimport it.
- delete the translation.

[#PPD_ManageThemes_HowTo_ManageThemes]
.Manage Themes

You can see the buttons *Create New Theme* and *Import Theme* and a list of saved themes.

With the Themes Manager you can

- create a new theme. You can do that in the <<, Payment Page Styler>>.
// link to PPS (when branch 397 is available at staging)
- import themes. The theme file must be available in json format.

In the themes list, 

- click the eye icon on the right of the theme name to see a preview of the theme. The preview is displayed as a jpg and can be downloaded.
- click the circle on the left of the theme name to drop down the theme's properties. Active themes show a tick in a white circle, inactive themes show an empty circle.

When the properties are opened you can

- modify the theme's name (click the notepad icon).
- select a <<PPD_ManageThemes_HowTo_ManageTranslations, translation file>>. 
- set it as the default theme. The default theme will be used for payment processes if not indicated otherwise <<PPD_ManageThemes_Sample, in a request>>.
- set its status to "Active" or "Inactive". Only "Active" themes can be used in a request.
- change the theme's settings (click *Style it*). With *Style it* you select a theme to open in the Payment Page Styler. If *Style it* is not active, the theme is already loaded into the Payment Page Styler. You can always return to the Payment Page Styler with the button *BACK TO DESIGNER*. 
- save your changes. *Save* is only active, if there are changes to save.
- export the theme to a json file.
- delete the theme

[#PPD_ManageThemes_Field]
.Use Theme in Request

[%autowidth]
|===
| Field Name | Data Type | JSON Parent | Description

| theme | String | options ({ }) | The name of the PPD theme used for a specific payment process.
|===


[#PPD_ManageThemes_Sample]
.An Example Request w/ Theme
//must be provided by Ronald

[source,json,subs=attributes+]
----
include::[]
----



//// 
[#PaymentPageDesigner_UsingThemes]
===== Using Themes

You can select any theme you have saved in Payment Page Designer as the default one. Each time the payment page loads, it will show that particular theme.
If you want to use a different theme for a payment (other than your default), you need to specify this in the request.

[%autowidth]
|===
| Field Name | Data Type | JSON Parent | Description

| theme | String | options ({ }) | The name of the PPD theme used for a specific payment process.
|===

[NOTE]
====
The value of `theme` is the name under which you saved the theme you want to use in Payment Page Designer.

You can access default theme settings in Payment Page Designer. If you do not send this field in the request, the default theme is used.
====

If you customize and save a theme in PPD under the name `test-theme` and then use it for a payment, the request looks like this:

.An Example Request w/ Theme

[source,json,subs=attributes+]
----
include::samples/json/PaymentPageDesignerUsingThemes_AnExampleRequestWTheme.json[]
----
////