[#RestApi_Samples]
=== Samples

[#RestApi_Samples_All]
==== For All Payment Methods

[#RestApi_Samples_All_Xml]
===== XML
.XML Purchase Request (Successful)
[source, xml]
----
include::src-files/xml/RestApi_Samples_All_Xml_Purchase_Request_Successful.xml[]
----

.XML Purchase Response (Successful)
[source,xml]
----
include::src-files/xml/RestApi_Samples_All_Xml_Purchase_Response_Successful.xml[]
----

[#RestApi_Samples_All_Json]
===== JSON

.JSON Purchase Request (Successful)
[source, json]
----
include::src-files/json/RestApi_Samples_All_Json_JSON_Purchase_Request_Successful.json[]
----

.JSON Purchase Response (Successful)
[source, json]
----
include::src-files/json/RestApi_Samples_All_Json_JSON_Purchase_Response_Successful.json[]
----

[#RestApi_Samples_CreditCardOnly]
==== Credit Card Only

[#RestApi_Samples_CreditCardOnly_Transaction]
===== Transaction Simulation

.XML Purchase Request (Failure)
[source,xml]
----
include::src-files/xml/RestApi_Samples_CreditCardOnly_Transaction_Purchase_Request_Failure.xml[]
----

.XML Purchase Response (Failure)
[source,xml]
----
include::src-files/xml/RestApi_Samples_CreditCardOnly_Transaction_Purchase_Response_Failure.xml[]
----

[#RestApi_Samples_CreditCardOnly_Timeout]
===== Timeout Simulation

The following request shows a transaction status simulation for a
successful credit card transaction that responded after 60,000
milliseconds.

.XML Purchase Timeout Simulation Request (Successful)
[source,xml]
----
include::src-files/xml/RestApi_Samples_CreditCardOnly_Timeout_Purchase_Timeout_Simulation_Request_Successful.xml[]
----

.XML Purchase Timeout Simulation Response (Successful)
[source,xml]
----
include::src-files/xml/RestApi_Samples_CreditCardOnly_Timeout_Purchase_Timeout_Simulation_Response_Successful.xml[]
----

[#RestApi_Samples_CreditCardOnly_ReferencedTransaction]
===== Referenced Transaction Simulation

.XML Initial Zero Dollar Authorization Request (Successful)
[source,xml]
----
include::src-files/xml/RestApi_Samples_CreditCardOnly_ReferencedTransaction_Initial_Zero_Dollar_Authorization_Request_Successful.xml[]
----

.XML Initial Zero Dollar Authorization Response (Successful)
[source,xml]
----
include::src-files/xml/RestApi_Samples_CreditCardOnly_ReferencedTransaction_Initial_Zero_Dollar_Authorization_Response_Successful.xml[]
----

.XML Following Purchase Request (Failure)
[source,xml]
----
include::src-files/xml/RestApi_Samples_CreditCardOnly_ReferencedTransaction_Following_Purchase_Request_Failure.xml[]
----

.XML Following Purchase Response (Failure)
[source,xml]
----
include::src-files/xml/RestApi_Samples_CreditCardOnly_ReferencedTransaction_Following_Purchase_Response_Failure.xml[]
----
