[#RestApi_Samples]
=== Samples

[#RestApi_Samples_All]
==== For All Payment Methods

[#RestApi_Samples_All_Xml]
===== XML
.XML Purchase Request (Successful)
[source, xml]
----
include::samples/xml/creditcard_purchase_request_success.xml[]
----

.XML Purchase Response (Successful)
[source,xml]
----
include::samples/xml/creditcard_purchase_response_success.xml[]
----

[#RestApi_Samples_All_Json]
===== JSON

.JSON Purchase Request (Successful)
[source, json]
----
include::samples/json/RestApiSamplesAllJson_JSON_PurchaseRequestSuccessful.json[]
----

.JSON Purchase Response (Successful)
[source, json]
----
include::samples/json/RestApiSamplesAllJson_JSON_PurchaseResponseSuccessful.json[]
----

[#RestApi_Samples_CreditCardOnly]
==== Credit Card Only

[#RestApi_Samples_CreditCardOnly_Transaction]
===== Transaction Simulation

.XML Purchase Request (Failure)
[source,xml]
----
include::samples/xml/creditcard_purchase_request_failure.xml[]
----

.XML Purchase Response (Failure)
[source,xml]
----
include::samples/xml/creditcard_purchase_response_failure.xml[]
----

[#RestApi_Samples_CreditCardOnly_Timeout]
===== Timeout Simulation

The following request shows a transaction status simulation for a
successful credit card transaction that responded after 60,000
milliseconds.

.XML Purchase Timeout Simulation Request (Successful)
[source,xml]
----
include::samples/xml/creditcard_purchase_request_success.xml[]
----

.XML Purchase Timeout Simulation Response (Successful)
[source,xml]
----
include::samples/xml/creditcard_purchase_response_success.xml[]
----

[#RestApi_Samples_CreditCardOnly_ReferencedTransaction]
===== Referenced Transaction Simulation

.XML Initial Zero Dollar Authorization Request (Successful)
[source,xml]
----
include::samples/xml/creditcard_authorization-only_request_success.xml[]
----

.XML Initial Zero Dollar Authorization Response (Successful)
[source,xml]
----
include::samples/xml/creditcard_authorization_response_success.xml[]
----

.XML Following Purchase Request (Failure)
[source,xml]
----
include::samples/xml/RestApiSamplesCreditCardOnlyReferencedTransaction_FollowingPurchaseRequestFailure.xml[]
----

.XML Following Purchase Response (Failure)
[source,xml]
----
include::samples/xml/creditcard_purchase_response_failure.xml[]
----
