[#ShopSystems]
== Shop Systems

video::jO_86Hj0I60[youtube, width=640, height=360]

We offer you various shop plugins which you are able to
use *free-of-charge* to add payment functionality to your online shop
system. Therefore you only need to download/install our shop plugin to
your online shop and to configure it to your needs.

Some shop systems refer to these shop plugins as "extension", as
"add-on" or as "module". However, for the purpose of better legibility,
we call all of them "shop plugins" within this documentation.

All our shop plugins require *only PCI SAQ A* certification for credit
card payments which you may achieve very easily.

You are able to *test the shop plugin* features and functionality via
pre-configured test accounts for each payment method. For going live you
need your personal credentials which you receive from Wirecard after
concluding a corresponding contract. Please contact therefore
our <<ShopSystems_ContactUs, sales and support teams>>.

All our shop plugins are developed and offered as *open source* on link:https://github.com/wirecard[GitHub]. This means you are able
to use them free-of-charge, have full access to the source code and are
able to do forks, raise issues or do contributions. You can find more
information regarding this topic in our Wirecard Blog
regarding link:https://blog.wirecard.com/simply-uncomplicated-what-is-open-payment/[Open Payment].

Please have a look on
our <<ShopSystems_TermsOfUse, Terms of Use and Legal Notice>> before you use our shop plugins in your online
shop.

.Currently we offer shop plugins for the following shop systems:
[%autowidth]
|===
|Shop System   |Supported Payment Methods |Supported Languages |Documentation

| link:https://github.com/wirecard/magento-ee/wiki[Magento 1]
  a|  - Credit Card
      - Alipay Cross-border
      - eps-Überweisung
      - giropay
      - Guaranteed Invoice by payolution
      - Guaranteed Invoice by Wirecard
      - iDEAL
      - Maestro SecureCode
      - Masterpass
      - Pay by Bank app
      - Payment In Advance
      - Payment On Invoice
      - PayPal
      - SEPA Credit Transfer
      - SEPA Direct Debit
      - Sofort.
      - UnionPay International a|  - English 
                                   - German  a|  - link:https://github.com/wirecard/magento-ee/wiki[English]
| link:https://github.com/wirecard/magento2-ee/wiki[Magento 2]
  a|  - Credit Card
      - Alipay Cross-border
      - giropay
      - Guaranteed Invoice by Wirecard
      - iDEAL
      - Maestro SecureCode
      - Masterpass
      - Pay by Bank app
      - Payment In Advance
      - Payment On Invoice
      - PayPal
      - SEPA Credit Transfer
      - SEPA Direct Debit
      - Sofort.
      - UnionPay International a| - Chinese, simplified
                                  - Chinese, traditional
                                  - English
                                  - French
                                  - German
                                  - Indonesian
                                  - Japanese
                                  - Korean  a| - link:https://github.com/wirecard/magento2-ee/wiki[English]
                                               - link:https://github.com/wirecard/magento2-ee/wiki/Accueil[French]
| link:https://github.com/wirecard/opencart-ee/wiki[OpenCart]
  a|  - Credit Card
      - Alipay Cross-border
      - Guaranteed Invoice by Wirecard
      - iDEAL
      - Maestro SecureCode
      - Masterpass
      - Payment In Advance
      - Payment On Invoice
      - PayPal
      - SEPA Credit Transfer
      - SEPA Direct Debit
      - Sofort.
      - UnionPay International a| - Chinese, simplified
                                  - Chinese, traditional
                                  - English
                                  - German
                                  - Indonesian
                                  - Japanese
                                  - Korean   a|  - link:https://github.com/wirecard/opencart-ee/wiki[English]
| link:https://github.com/wirecard/prestashop-ee/wiki[PrestaShop]
  a|  - Credit Card and Maestro SecureCode
      - Alipay Cross-border
      - Guaranteed Invoice by Wirecard
      - iDEAL
      - Masterpass
      - Payment In Advance
      - Payment On Invoice
      - PayPal
      - Przelewy24
      - SEPA Credit Transfer
      - SEPA Direct Debit
      - Sofort.
      - UnionPay International a| - Chinese, simplified
                                  - Chinese, traditional
                                  - English
                                  - French
                                  - German
                                  - Indonesian
                                  - Japanese
                                  - Korean
                                  - Polish  a| - link:https://github.com/wirecard/prestashop-ee/wiki[English]
                                               - link:https://github.com/wirecard/prestashop-ee/wiki/Accueil[French]
| link:https://github.com/wirecard/sap-commerce-ee/wiki[SAP Commerce]
  a|  - Credit Card and Maestro SecureCode
      - Alipay Cross-border
      - Guaranteed Invoice by Wirecard
      - iDEAL
      - Masterpass
      - Payment In Advance
      - Payment On Invoice
      - PayPal
      - SEPA Direct Debit
      - Sofort.
      - UnionPay International a| - English
                                  - German   a| - link:https://github.com/wirecard/sap-commerce-ee/wiki[English]
| link:https://github.com/wirecard/shopify-ee[Shopify]
  a|  - Credit Card and Maestro SecureCode
      - Pay by Bank app
      - PayPal
      - SEPA Direct Debit
      - Sofort.               a| - Chinese, simplified
                                 - Chinese, traditional
                                 - English
                                 - French
                                 - German
                                 - Indonesian
                                 - Japanese
                                 - Korean    a| - link:https://github.com/wirecard/shopify-ee/wiki[English]
                                                - link:https://github.com/wirecard/shopify-ee/wiki/Accueil[French]
| link:https://github.com/wirecard/shopware-ee/wiki[Shopware]
  a|  - Credit Card and Maestro SecureCode
      - Alipay Cross-border
      - eps-Überweisung
      - Guaranteed Invoice by Wirecard
      - iDEAL
      - Masterpass
      - Payment In Advance
      - Payment On Invoice
      - PayPal
      - SEPA Credit Transfer
      - SEPA Direct Debit
      - Sofort.
      - UnionPay International a| - English
                                  - German   a| - link:https://github.com/wirecard/shopware-ee/wiki[English]
| link:https://github.com/wirecard/woocommerce-ee/wiki[WooCommerce]
  a|  - Credit Card and Maestro SecureCode
      - Alipay Cross-border
      - eps-Überweisung
      - Guaranteed Invoice by Wirecard
      - iDEAL
      - Masterpass
      - Pay by Bank app
      - Payment In Advance
      - Payment On Invoice
      - PayPal
      - SEPA Credit Transfer
      - SEPA Direct Debit
      - Sofort.
      - UnionPay International a| - Chinese, simplified
                                  - Chinese, traditional
                                  - English
                                  - French
                                  - German
                                  - Indonesian
                                  - Japanese
                                  - Korean   a| - link:https://github.com/wirecard/woocommerce-ee/wiki[English]
                                                - link:https://github.com/wirecard/woocommerce-ee/wiki/Accueil[French]
                                                - link:https://github.com/wirecard/woocommerce-ee/wiki/Startseite[German]
|===

If you require another shop system not listed here or if you need
additional payment methods or languages,
please <<ShopSystems_ContactUs, contact our sales and support teams>>.

.Adding payment methods:

Add more payments methods with the
link:https://github.com/wirecard/paymentSDK-php[Wirecard PHP Payment SDK] or
our <<PaymentMethods, Wirecard REST API payment methods>>.

Want to contribute? Send us a pull-request on GitHub and we will get in
touch with you.


.Our shop plugins offer the following functionalities:

- *Credit card* payments based on a *seamless integration* via Seamless
Payment Page, so that your consumers have a perfectly integrated payment
experience in your online shop.
- All our shop plugins require *only PCI DSS SAQ A*, which is the
easiest possible PCI SAQ level, so that you do not need to hassle with
PCI related details.
- All *alternative payment methods* are integrated via REST API of our
Wirecard Payment Gateway to offer all features and
flexibility in integration for each payment method.
- All payment methods are integrated individually which enables you
to *configure* them separately to your specific demand.
- Post-processing operations (like *capture, refund or cancel*) for each
payment method are directly supported in the back-end of the shop
system, so that your transactions within Wirecard are synchronized to
the orders in your online shop.
- Support of *one-click-checkout for credit card* payments, so that
recurring consumers of your online shop can easily and fast do their
further payments.
- Integration of a *live-chat with our support team* within the
configuration of the shop plugin and offered features and payment
methods, so that you get a quick and interactive help when and where you
need it.
- Integration to *Wirecard Risk Management*, so that you are able to use
risk and fraud tools to reduce fraudulent transactions in your online
shop.
- Regular *updates of all of our shop plugins* to offer you
compatibility to the current versions of shop systems.

//-

.Advantages of using shop plugins developed and maintained by Wirecard

- All our shop plugins are based on the principles of *open source* development and available for free for everyone. Please have
also a look on our Blog article
regarding link:https://blog.wirecard.com/simply-uncomplicated-what-is-open-payment/[*Open Payment*].
- You are able to download, install and configure the shop plugin and do
as many *test transactions* as you want to do.
- All shop plugins are available with their complete *source code* and *history* 
of all changes, so that you are able to change the
shop plugin to your business need.
- We offer you *free support by e-mail or phone* if you have any
questions regarding the installing and configuring of our shop plugins.
- You and your integrator are able to *raise issues, make pull requests or create forks* within all functionality GitHub offers to you.
- You are able to *contribute* to improve a shop plugin, so that your
features are also available within all new versions we are releasing.

//-

Finally, feel free to take a look at <<ShopSystems_Myths, Myths regarding the usage of a shop plugin in your online shop>>.

[#ShopSystems_TermsOfUse]
=== Terms of Use

. The plugins offered are provided free of charge by Wirecard AG and
are explicitly not part of the Wirecard AG range of products and
services.
. They have been tested and approved for full functionality in the
standard configuration (status on delivery) of the corresponding shop
system. They are under General Public License Version 3 (GPLv3) and can
be used, developed and passed on to third parties under the same terms.
. However, Wirecard AG does not provide any guarantee or accept any
liability for any errors occurring when used in an enhanced, customized
shop system configuration.
. Operation in an enhanced, customized configuration is at your own
risk and requires a comprehensive test phase by the user of the plugin.
. Customers use the plugins at their own risk. Wirecard AG does not
guarantee their full functionality neither does Wirecard AG assume
liability for any disadvantages related to the use of the plugins.
Additionally, Wirecard AG does not guarantee the full functionality for
customized shop systems or installed plugins of other vendors of plugins
within the same shop system.
. Customers are responsible for testing the plugin's functionality
before starting productive operation.
. By installing the plugin into the shop system the customer agrees to
these terms of use. Please do not use the plugin if you do not agree to
these terms of use!
. Uninstalling the plugin may result in the loss of data.

//-

[#ShopSystems_LegalNotes]
==== Legal Notes

No warranty whatsoever can be granted on any alterations and/or new
implementations as well as resulting diverging usage not supported or
described within this documentation.

[#ShopSystems_Myths]
=== Myths regarding our shop plugins

====
"My payment processes have to fit perfectly to that processes offered by the
shop system, otherwise I have to adapt either the shop plugin or my processes!"
====
::
We are integrating the Wirecard Payment Gateway based on the
standards of the corresponding shop system. This enables us a very tight
integration of our interface to the default payment process offered by
the shop system. Therefore our payment processes are integrated as
intended by the shop system.
+
If you, as a merchant, require different processes than offered by the
shop system and our shop plugin you have the following possibilities:

. Re-think your decision choosing your shop system. Maybe another shop
system fits better to your processes.
. Adapt the shop system and maybe also the shop plugin to your
business needs. This is possible for nearly all shop systems, because
they offer an open source version you are allowed to modify as you want.

//-

---

====
"I will have additional costs due to changes and adoptions in the
source code of the shop plugin which have to be done by my developers or
my integrator and they are not used with the structure and source code
of the shop plugin!"
====
::
or
====
"If my processes will be required to change then I have to adopt
the shop plugin again. An integration by my own would be more flexible
for me!"
====
::
or
====
On the long run the sum of efforts to update and maintain the
shop plugin is much higher than a personalized integration. Additionally
I have to consider that it takes much time to update a shop plugin!
====
::
or
====
"I have heard from other merchants that a direct and personal
integration to my online shop is much faster and cheaper than using a
shop plugin!"
====
::
Overall seen it is always much cheaper and faster for you as merchant to
start with a full-featured and functional shop plugin tailored and
deeply integrated to your shop system. Otherwise, if you do the
integration on your own from the scratch you have to deal with all the
payment related details of the shop system and the integration details
of the payment interfaces to Wirecard.
+
Additionally a shop plugin offers following advantages:

. We are constantly maintaining and updating our shop plugins
regarding the updates of the shop system, integration of payment methods
and adding new features. If you do the integration by your own from the
scratch you have to do this solely on you own which may end in permanent
attention and effort to keep track with the shop system, regulations and
security updates.
. If your changes and adoptions are of interest also for other
integrators or developers, you may raise a pull-request on GitHub and
our developers will check your contribution. If it is fine, we will add
it to the source code of our shop plugin, so that for each new version
of our shop plugin your changes/adoptions are part of a release and you
do not need to adopt it every time we do an update.

//-
::
Even if you decide to do your own integration from the scratch please
keep in mind to use our shop plugin as a “blue print” which may help you
regarding the implementation of various features, workflows and payment
methods.

---

====
"If there is a new version of the shop plugin I have to redo all
my manual changes again!"
====
::
Within the update of a shop plugin your configuration and your already
existing transactions are also available in the new version of the shop
plugin. If you did only small changes in your shop plugin installation
you may find the differences easy via your version control system and
are able to merge them to the updated shop plugin. If there are larger
changes regarding functionality you may consider to raise a pull-request
in GitHub, so that our developers may integrate your feature to the shop
system and then this feature will also be part of each new version we
release.

---

====
"Shop plugins are not as often and as fast updated as I require it!"
====
::
If there are no substantial changes in the interface of the shop system
and the payment process our shop plugin will work out-of-the-box also
with newer versions of the shop system, especially if there are only
minor updates of the shop system itself.
+
We at Wirecard are doing our best to have our shop plugins as near as
possible to the releases of the shop vendors. But we are not able to
guarantee that we can do an update on a daily-base and in comparison to
the market we do updates very fast and consequent and have a proven
track since many years.
+
On the other hand if you do the integration on your own, you have to
check and update your own integration also.

---

====
"Shop plugins causes troubles in conjunction with other plugins I
have installed within my shop system!"
====
::
All our shop plugins are developed strictly to the rules, frameworks and
hooks of the shop system. Therefore you are able to use our shop plugins
in parallel within one shop and we do not interfere other shop plugins
you may have installed in your shop system. If there are troubles with
other shop plugins disturbing the payment process, we would like to
recommend you to disable these plugins or check for a newer and
compatible version. If this does not solve the problem, please contact
our support teams, so we can maybe find a workaround for you.

---

====
"Shop plugins only support the current version of the shop system
and therefore you have to update your shop system to use the shop
plugin!"
====
::
If you want to use an older version of our shop plugin you can find and
download all previously released versions directly from GitHub. Even we
offer this, we strongly recommend that you update your shop system
accordingly to the releases of the shop vendor, so that your online shop
is up-to-date regarding features, functions and security.
+
If you may have other or additional doubts, please do not hesitate to
contact our <<ShopSystems_ContactUs, sales and support teams>>.

[#ShopSystems_ContactUs]
=== Contact Information

If you have any questions or need further assistance please do not
hesitate to contact our *support teams*.

If you are interested in our solutions or have questions about
Wirecard do not hesitate to contact our *sales teams*.

|===
2+| GERMANY

2+| *Wirecard AG* +
Einsteinring 35 +
85609 Aschheim, Germany

| *Shop Systems Support Team*

shop-systems-support@wirecard.com

| *Sales Team*

Phone: link:tel:+498944241400[+49 89 4424-1400]

sales@wirecard.com

2+| We are glad to be of assistance from Monday to Friday from 8:00 to 19:00 (CET).
|===

|===
2+| AUSTRIA

2+| *Wirecard CEE* +
Reininghausstraße 13a +
8020 Graz, Austria

| *Shop Systems Support Team*

Phone (24/7): link:tel:+433168136811800[+43 316 813681-1800] +
Fax: link:tel:+433168136811203[+43 316 813681-1203]

shop-systems-support@wirecard.com

| *Sales Team*

Phone: link:tel:+433168136811400[+43 316 813681-1400] +
Fax: link:tel:+4331681368120[+43 316 813681-20]

office.at@wirecard.com

2+| We are glad to be of assistance from Monday to Friday from 8:00 to 16:30 (CET).
|===

|===
2+| SINGAPORE

2+| *Wirecard Singapore Pte Ltd* +
80 Pasir Panjang Road, #14-81 Mapletree Business City II, +
Singapore 117372

| *Shop Systems Support Team*

Phone: link:tel:+6568076050[+65 6807 6050]

shop-systems-support@wirecard.com

| *Sales Team*

Phone: link:tel:+6566906690[+65 6690 6690]

sales-enquiry.sg@wirecard.com

2+| We are glad to be of assistance from Monday to Friday from 9:00 to 18:00
(SGT).

|===

|===
2+| AUSTRALIA

2+| *Wirecard Australia A&I Pty Ltd* +
Level 8, 360 Collins Street, +
Melbourne Victoria 3000 

| *Shop Systems Support Team*

Phone: link:tel:+611300599991[+61 1300 599 991]

shop-systems-support@wirecard.com

| *Sales Team* 

Phone: link:tel:+611300599980[+61 1300 599 980]

sales.au@wirecard.com

2+| We are glad to be of assistance from Monday to Friday from 9:00 to 17:00
(AET).
|===
