[#PaymentMethods]
== Payment Methods

Merchants can send payments to _Wirecard Payment Gateway_ using various
payment methods. In order to be able to create a payment using a
specific payment method, the merchant has to have a valid subscription
for this payment method and needs to specify it correctly inside the
payment request. 

The following pages provide an overview over all available payment
methods, their characteristics and the required parameters for
transaction processing.

[#API_PM_CC]
=== Credit Card

As a payment service provider and bank, Wirecard offers payment processing and
card acceptance as a complete solution from a single source. Our
industry-specific end-to-end solutions can be quickly and easily incorporated
and can be used for all major credit and debit cards, as well as in all common
payout and transaction currencies.

The _Wirecard Payment Gateway_ operates according to the latest security
standards. It meets all the requirements stipulated for a card organization,
including
<<CreditCard_PaymentFeatures_Tokenization_Introduction, PCI DSS compliance>>.
It supports the processing of industry-specific supplementary data, including
the hotel, airline and car rental industries.

[#API_PM_CC_CreditDebit]
==== Credit Card and Debit Card

This section describes the difference between Credit Card and Debit Card
payments and their respective advantages.

<<API_PM_CC_PaymentMode_Debit, Debit>>

<<API_PM_CC_PaymentMode_Credit, Credit>>

[#API_PM_CC_PaymentMode_Debit]
===== Debit

A debit card (also known as a bank card or check card) is a payment card that
can be used instead of cash when making purchases. It is similar to a credit
card, but unlike a credit card, the money comes directly from the user's bank
account when performing a transaction.

Some cards may bear a stored value with which a payment is made, while most
relay a message to the cardholder's bank to withdraw funds from a payer's
designated bank account. In some cases, the primary account number is assigned
exclusively for use on the Internet and there is no physical card.

In many countries, the use of debit cards has become so widespread that their
volume has overtaken or entirely replaced cheques and, in some instances, cash
transactions. The development of debit cards, unlike credit cards and charge
cards, has generally been country specific resulting in a number of different
systems around the world, which were often incompatible. Since the mid-2000s,
a number of initiatives have allowed debit cards issued in one country to be
used in other countries and allowed their use for internet and phone purchases.

[#API_PM_CC_PaymentMode_Debit_Advantage]
====== Advantages

- A debit card immediately transfers the payment from the cardholder's designated
bank account.
- Debit cards allow instant withdrawal of cash.
- Merchants may also offer cashback facilities to customers, where a customer
can withdraw cash along with their purchase.
- A debit card requires the balance to be repaid in full each month
Debit card simply defers payment by the cardholder until a later date

[#API_PM_CC_PaymentMode_Credit]
===== Credit

A credit card is a payment card issued to a cardholder to enable the cardholder
to pay a merchant for goods and services, based on the cardholder's promise to
the card issuer to pay them for the amounts so paid plus other agreed charges.
The card issuer (usually a bank) creates a revolving account and grants a line
of credit to the cardholder, from which the cardholder can borrow money for
payment to a merchant or as a cash advance.

In the same context prepaid credit card can be used. The prepaid credit card
in opposite to the standard credit card cannot be used without enough money on
it (the referring account). These cards can be used for payments only in case
the Card Owner has enough money on his card. In this case the card holder can
perform the same actions like with standard credit card up to the limit of the
card/until no fund is left.

[#API_PM_CC_PaymentMode_Credit_Advantage]
====== Advantages

- A credit card allows continuing balance of debt, subject to interest being
charged.
- A credit card typically involves a third-party entity that pays the seller and
is reimbursed by the cardholder.

[#API_PM_APM]
=== Alternative Payment Methods

Next to Credit Card Payments, merchants can also use _Alternative Payment Methods_
(APM) in the environment of the _Wirecard Payment Gateway_ to process their
payments. APMs comprise the payment modes Bank Transfer (online and offline),
Prepaid, Voucher, Wallet.

The _Wirecard Payment Gateway_ offers a variety of online and offline
bank transfer payment methods. Each payment method can be used depending
on regulations and laws of regions and countries. For details click the
payment method's name in the table below.

Other payment modes provided by the _Wirecard Payment Gateway_ are
_Prepaid_, _Voucher, Wallet._

Also some Mobile Payment options, which are just a variety of the above
mentioned Payment Methods, fit into that scheme.

[#API_PM_APM_PaymentMode]
==== APMs grouped by Payment Mode

This section describes the APM payment modes supported by the
_Wirecard Payment Gateway_, their advantages and which payment method applies
to each of the payment modes.

<<API_PM_APM_PaymentMode_Online, Online Bank Transfer>>

<<API_PM_APM_PaymentMode_Offline, Offline Bank Transfer>>

<<API_PM_APM_PaymentMode_Prepaid, Prepaid and Voucher>>

<<API_PM_APM_PaymentMode_Wallet, Wallet>>

<<API_PM_APM_PaymentMode_Mobile, Mobile Payment>>

[#API_PM_APM_PaymentMode_Online]
===== Online Bank Transfer

Online bank transfer is a payment mode which enables shoppers to
directly do the payment when ordering the product.

Payment confirmation for this payment mode is sent in real time through
_Wirecard Payment Gateway_. 

After a successful payment, the transaction may no longer be revoked by
the consumer and the merchant can ship the ordered product or service
immediately.

[#API_PM_APM_PaymentMode_Online_Advantage]
====== Advantages

An online bank transfer offers the option to perform secure online
payments to consumers, who

- do not own a credit/debit card.
- do not want to use a credit/debit card when shopping in the internet.

With an online bank transfer consumers

- transfer money in their personal online banking environment.
- do not share personal bank account details with the merchant.

This increases the conversion rate for merchants as well as the customer
satisfaction.

[#API_PM_APM_PaymentMode_Online_PM]
====== Payment Methods

<<BancontactMisterCash, Bancontact>>

<<CarrierBilling, Carrier Billing>>

<<CIMBClicks, CIMB Clicks>>

<<eps, eps-Überweisung>>

<<giropay, giropay>>

<<iDEAL, iDEAL>>

<<Klarna, Klarna Services>>

<<Maybank2u, Maybank2u>>

<<, moip Pagamentos>>

<<API_PaybyBankapp, Pay by Bank app (Zapp)>>

<<paydirekt, paydirekt>>

<<payolution, payolution>>

<<POLi, POLi>>

<<Przelewy24, Przelewy24>>

<<SafetyPay, SafetyPay>>

<<Sofort, Sofort.>>

<<Trustly, Trustly>>

<<TrustPay, TrustPay>>



[#API_PM_APM_PaymentMode_Offline]
===== Offline Bank Transfer

Offline bank transfer is a payment mode which enables shoppers to
decouple the payment from the delivery of the product they ordered.

This means during your shopping event, wherever you do it, you order
something and you pay for it not by directly using your credit card,
your online banking, etc. You tell your merchant that you want to buy
his product and you get a kind of invoice for it.

With that invoice you can do e.g. a money transfer (SEPA Deposit).

So order/shipping and payment are decoupled.

The payment confirmation for this type of payment mode is sent in a
batch process through _Wirecard Payment Gateway_.

[#API_PM_APM_PaymentMode_Offline_Advantage]
====== Advantages

An offline bank transfer offers the option to perform secure online
payments to consumers, who

- do not own a credit/debit card
- do not want to use a credit/debit card shopping in the internet

This increases the conversion rate for merchants as well as the customer
satisfaction.

[#API_PM_APM_PaymentMode_Offline_PM]
====== Payment Methods

<<Boleto, Boleto>>

<<GuaranteedInvoiceandDirectDebit, Guaranteed Services>>

<<Klarna, Klarna Services>>

<<API_POIPIA, Payment on Invoice (POI)/Payment in Advance (PIA)>>

<<SafetyPay, SafetyPay>>

<<SEPACreditTransfer, SEPA Credit Transfer>>

<<SEPADirectDebit, SEPA Direct Debit>>

<<TrustPay, TrustPay>>



[#API_PM_APM_PaymentMode_Prepaid]
===== Prepaid or Voucher

"Pay with cash on the internet" - this slogan stands for prepaid or
voucher-based payment solutions.

With this popular payment mode consumers have the possibility to buy
prepaid-cards or vouchers at thousands of participating stores like
kiosks or gas stations.

The cash or voucher code is used to perform the payment on the
merchant´s checkout page.


[#API_PM_APM_PaymentMode_Prepaid_Advantage]
====== Advantages

For the merchant a prepaid or voucher payment is

- guaranteed and cannot be revoked by the consumer.
- very popular at kiosks or gas stations.

For consumers who do not want to provide

- credit card data
*-account data or credentials

[#API_PM_APM_PaymentMode_Voucher_PM]
====== _Prepaid_ Payment Method

<<paysafecard, paysafecard>>

[#API_PM_APM_PaymentMode_Voucher_PM]
====== _Voucher_ Payment Method

<<WirecardVoucher, Wirecard Voucher>>

[#API_PM_APM_PaymentMode_Wallet]
===== Wallet

Wallet is a payment mode which enables consumers to pay directly from
their Wallet to merchants they want to deal with. So like in online
payment mode consumers are enabled to directly do the payment when
ordering the product.

Payment confirmation for this payment mode is sent in real time through
_Wirecard Payment Gateway_.

[#API_PM_APM_PaymentMode_Wallet_Advantage]
====== Advantages

For the merchant a wallet payment

- is guaranteed by the wallet provider and cannot (in most cases) be
revoked by the consumer.
- is very popular in many countries for payment on the internet.
- provides real time feedback about transaction status (fast shipping).
It allows instant payment notification.

This increases the conversion rate for merchants as well as the customer
satisfaction.

For consumers who do not want to provide

- credit card data
- account data or credentials

In most of the cases

- it is easy to use and register at the wallet provider.
- wallet can be linked to consumer accounts or credit cards for upload.
- wallet can be linked to local popular payment methods for upload.
- only username and password is necessary.
- products can be shipped immediately.

[#API_PM_APM_PaymentMode_Wallet_PM]
====== Payment Methods

<<API_AlipayCrossBorder, Alipay Cross-border>>

<<API_AlipayDomestic, Alipay Domestic>>

<<, Alipay QR Code User Scan>>

<<API_MasterPass, MasterPass>>

<<mobicred, mobicred>>

<<monetaRu, moneta.ru>>

<<API_PaymentMethods_PayPal, PayPal>>

<<SkrillDigitalWallet, Skrill Digital Wallet>>

<<VISACheckout, Visa Checkout>>

<<API_WeChatQRPay, WeChat QRPay>>


[#API_PM_APM_PaymentMode_Mobile]
===== Mobile Payment

Some payment methods are to be used purely on the smartphone (Paybox),
other payment methods offer mobile payment as an additional variant to
their traditional payment possibilities. Therefore it is not possible to
assign mobile payment to either "Credit/Debit Card" or "Non Credit Card
Payment".

The usage of smartphones and tablets has massively assisted in the
development of mobile payments. Meanwhile, a wide-range of products
are available on the market, using different kinds of technologies.
_Wirecard Payment Gateway_ already supports several mobile payment
options.

[#API_PM_APM_PaymentMode_Mobile_Advantage]
====== Advantages

A mobile payment method is an attractive alternative to a consumer's
credit card. Some consumers enjoy the comfort to pay with a mobile
device and charge the monthly telecommunication bill.

[#API_PM_APM_PaymentMode_Mobile_PM]
====== Payment Methods

<<, paybox>>

<<, Apple Pay>>

<<, UnionPay>>

//-
