include::shortcuts.adoc[]
:date-pattern: YYYY-MM-DD
:timestamp-pattern: YYYY-MM-DDThh:mm:ssZ

[#CC_Fields]
==== Fields

This is the general field reference for _credit card_ transactions.

====
- Format: XML 
- POST requests and responses

//-
====

We provide the request and the response fields in two separate sections:

- <<CC_Fields_xmlelements_request, _Request_>> contains those fields sent in the request (and usually in the response).
- <<CC_Fields_xmlelements_response, _Response_>> contains those fields sent in the response only.

//-

The fields are ordered hierarchically and in separate tables. ``payment`` is the top parent element and all fields that are part of ``payment`` are listed <<CC_Fields_xmlelements_request_payment, in the ``payment`` table>>. 

Some fields listed in this table are _complex type_ fields, e.g. ``payment.account-holder``. _Complex type_ fields are parents to further fields. We offer separate field tables for all parent elements and their respective fields.

NOTE: The tables are sorted alphabetically. Use *Ctrl + F* if you are looking for a specific field.

For example, ``payment.account-holder`` is a parent of ``address``. Click on the link in the table to view the fields contained in a _complex type_ field.


[#CC_Fields_intro_elements]
===== Field Definitions

Each field table contains the following columns:

- <<CC_Fields_intro_elements_name, Name>>
- <<CC_Fields_intro_elements_cardinality, Cardinality>> (for request elements only)
- <<CC_Fields_intro_elements_dataType, Data Type>>
- <<CC_Fields_intro_elements_Size, Size>> (for request elements only)

// DBL: List does not contain Description" on purpose?

//-

IMPORTANT: Field definitions may vary by transaction type. Deviations from standard field definitions are given with the respective transaction type.

[#CC_Fields_intro_elements_name]
====== Name
The field name structure is based on the hierarchical relation between individual elements. +
_Example:_ ``order-items.order-item.article-number`` +

.Structure
[mermaid, CC_Fields_intro_elements_parentchild,svg]
----
graph LR
A(parent-element)-->B
B("child = parent-element")-->C
C(child)
E[order-items.]-->F
F[order-item.]-->G
G[article-number]
class E squared-rect
class F squared-rect
class G squared-rect
----

// DBL: Mermaid does not show in ** int url removed **

.XML Structure
[source, xml]
----
<payment>
    <order-items>
        <order-item>
            <article-number> </article-number>
        </order-item>
    </order-items>
</payment>
----

In the example, the parent element is ``order-items``, and its child ``order-item``. +
``order-item`` itself is also a parent element of its child ``article-number``. 
The hierarchies are separated by a dot ``.``

[#CC_Fields_intro_elements_cardinality]
====== Cardinality

_Cardinality_ indicates if the field is necessary for the request to work. A field can be either *mandatory* (M) or *optional* (O).

- If a field is *mandatory,* it must be included in all _credit card_ requests and contain a value. Without this field, _credit card_ requests fail. +
- If a field is *optional,* it can, but does not have to be, included in all _credit card_ requests. Including optional fields can have certain advantages. These are included in the respective field description.

[IMPORTANT]
====
Some optional fields can be mandatory for individual requests, depending on transaction type and payment scenario. We list them as *M/O.* See the field description for more information on the respective field's cardinality.
====

====

*Example*:``payment.periodic`` is listed as *M/O.*

- ``periodic`` fields are *optional* when you send most _credit card_ requests. 
- ``periodic`` fields are *mandatory* when you send _credit card_ requests for one-time payments with one-click checkout, recurring payments, and installment payment transactions.

//-
====
//KKS: We should try to get rid of M/O; it's just as confusing for merchants as C, which is why it was decided to remove it entirely from 3D Secure 2 documentation.

//if we talk about a "periodic-element" we should publish the table as designed in the lines 914 to 937. What do you think?
//KKS: (Y)

//-

[#CC_Fields_intro_elements_dataType]
====== Data Type

_Data Type_ defines the specific characteristics of the input values that can be used for a field. There are seven data types: _String_, _Boolean_, _Date_, _Timestamp_, _Decimal_, _Number_,  and _Enumeration_.

// DBL: As the table follows immediately, maybe this is redundant: "_String_, _Boolean_, _Date_, _Timestamp_, _Decimal_, _Number_,  and _Enumeration_.""

[cols="20,80"]
|===
|Data Type |Description

|String
|A combination of text and numbers which is arbitrary but finite in size. A subset of _String_ values can be defined according to a pattern value, such as ``api-id``. The pattern is given in the _Description_ column.

|Boolean 
|Has one of two possible values (usually either ``true`` or ``false``).

|Date 
|Value taken from a calendar (e.g. the date of birth). +
Format (according to ISO 8601): ``{date-pattern}`` +
This pattern cannot be customized.

|Timestamp
|A moment in time defined by a system. +
Format (according to ISO 8601): ``{timestamp-pattern}`` +
This pattern cannot be customized.

|Decimal
|A numeric value which has digits before and after the decimal point ``.`` +
Example: the amount of money in a specific currency (e.g. 138.53 EUR).

|Number
|A numeric value that has no decimal places, such as the expiration month of a credit card.

|Enumeration 
|_Enumeration_ is a subset of _String_. _Enumeration_ consists of a list of predefined values, e.g. the severity of a status, which can provide the predefined values ``warning``, ``error`` and ``information``.
|===


[#CC_Fields_intro_elements_Size]
====== Size
_Size_ shows how many characters can be used for this field. We provide the maximum value so you can make sure the whole amount of characters is processed.

In general, the _{payment-gateway}_ allows all characters for each field, depending on the _Data Type_. 

If other rules apply to a field, they are stated in the _Description_ column.



[#CC_Fields_xmlelements]
===== XML Elements
Click the X in the respective column for request and response fields.

Please refer to our <<Appendix_Xml, XSD>> for the structural relationship between these fields.

[cols="m,,"]
|===
| Field | Request | Response

| payment
| <<CC_Fields_xmlelements_request_payment, X>>
| <<CC_Fields_xmlelements_response_payment, X>>

| account-holder
| <<CC_Fields_xmlelements_request_accountholder, X>>
| 

| address
| <<CC_Fields_xmlelements_request_address, X>>
| 

| airline-industry
| <<CC_Fields_xmlelements_request_airlineindustry, X>>
| 

| audit
| <<CC_Fields_xmlelements_request_audit, X>>
| 

| avs
| 
| <<CC_Fields_xmlelements_response_avs, X>>

| browser
| <<CC_Fields_xmlelements_request_browser, X>>
| 

| card
| <<CC_Fields_xmlelements_request_card, X>>
|  
 
// | card-emv
// | <<CC_Fields_xmlelements_request_cardemv, X>>
// | 

// | card-pin
// | <<CC_Fields_xmlelements_request_cardpin, X>>
// | 

// |card-raw
// | <<CC_Fields_xmlelements_request_cardraw, X>>
// | 

| card-token
| <<CC_Fields_xmlelements_request_cardtoken, X>>
| 

| credit-sender-data
| <<CC_Fields_xmlelements_request_creditsenderdata, X>>
| 

| cruise-industry
| <<CC_Fields_xmlelements_request_cruiseindustry, X>>
| 

| custom-fields
| <<CC_Fields_xmlelements_request_customfield, X>>
| <<CC_Fields_xmlelements_response_customfield, X>>

| device
| <<CC_Fields_xmlelements_request_device, X>>
| 

| notifications
| <<CC_Fields_xmlelements_request_notification, X>>
| 

| order-items
| <<CC_Fields_xmlelements_request_orderitem, X>>
| 

| payment-methods
| <<CC_Fields_xmlelements_request_paymentmethod, X>>
|

| risk-info
| <<CC_Fields_xmlelements_request_riskinfo, X>>
| 

| segment
| <<CC_Fields_xmlelements_request_segment, X>>
| 

| shipping
| <<CC_Fields_xmlelements_request_shipping, X>>
| 

| status
| 
| <<CC_Fields_xmlelements_response_status, X>>

| sub-merchant-info
| <<CC_Fields_xmlelements_request_submerchantinfo, X>>
| 

| three-d
| <<CC_Fields_xmlelements_request_threed, X>>
| <<CC_Fields_xmlelements_response_threed, X>>
|===

[#CC_Fields_xmlelements_request]
====== Request

[#CC_Fields_xmlelements_request_payment]
.``payment``

Additional ``payment`` fields can be found in the
<<CC_Fields_xmlelements_response_payment, Response > ``payment``>> section.

include::include/fields/rest_cc/request/req-payment.adoc[]


[#CC_Fields_xmlelements_request_accountholder]
.account-holder

``account-holder`` is a child of
<<CC_Fields_xmlelements_request_payment, payment>>. +
With the ``account-holder`` merchants can gather detailed information about the
consumer. Please provide all the ``account-holder`` data in your request to make fraud
prevention easier.

include::include/fields/rest_cc/request/req-account-holder.adoc[]


[#CC_Fields_xmlelements_request_accountinfo]
.account-info

``account-info`` is a child of
<<CC_Fields_xmlelements_request_accountholder, account-holder>>. +
``account-info`` fields are used with 3D Secure 2. With ``account-info`` merchants can gather detailed information about the consumer. Please provide all the ``account-info`` data in your 3D Secure 2 request to make fraud prevention easier.

include::include/fields/rest_cc/request/req-account-info.adoc[]

[#CC_Fields_xmlelements_request_address]
.address

``address`` is a child of
<<CC_Fields_xmlelements_request_accountholder, account-holder>>, <<CC_Fields_xmlelements_request_shipping, shipping>>, and <<CC_Fields_xmlelements_request_airlineindustry, airline-industry>>. It is used to specify the consumer's address and can refer to

- the consumer (for ``account-holder``). The account holder's address is used as the billing address.
- the consumer's shipping address (for ``shipping``). For 3D Secure 2 transactions it is highly recommended to send ``shipping.address`` data in any case, as a complete set of ``shipping.address`` data reduces the likelihood of a challenge test.
- the ticket issuer (for ``airline-industry``).

Data can be provided optionally but it helps with fraud checks, if ``address`` is complete.

include::include/fields/rest_cc/request/req-address.adoc[]

[#CC_Fields_xmlelements_request_airlineindustry]
.airline-industry

``airline-industry`` is a child of
<<CC_Fields_xmlelements_request_payment, payment>>.

include::include/fields/rest_cc/request/req-airline-industry.adoc[]


[#CC_Fields_xmlelements_request_audit]
.audit

``audit`` is a child of
<<CC_Fields_xmlelements_request_payment, payment>>. 
Audit data is displayed in _{enterprise-portal-abbr}_ for each transaction it has been send with.

include::include/fields/rest_cc/request/req-audit.adoc[]


[#CC_Fields_xmlelements_request_browser]
.browser

``browser`` is a child of
<<CC_Fields_xmlelements_request_payment, payment>>.

include::include/fields/rest_cc/request/req-browser.adoc[]

[#CC_Fields_xmlelements_request_card]
.card

``card`` is a child of  <<CC_Fields_xmlelements_request_payment, payment>>. ``card`` details are sent only in the first transaction request when the card is used for the first time. Due to
<<CreditCard_PaymentFeatures_Tokenization_Introduction, PCI DSS>> compliance, ``card`` details are immediately replaced by a token. Beginning with the first response, this
token is used for every consecutive transaction (request and response) that is performed
with this credit card. Token data is provided with the
<<CC_Fields_xmlelements_request_cardtoken, card-token>> element.

NOTE: Only the transaction type _detokenize_ returns ``expiration-month``,
``expiration-year`` and ``card-type`` in a response. All the other transaction
types return elements of ``card-token`` in the response.

include::include/fields/rest_cc/request/req-card.adoc[]

//// 
[#CC_Fields_xmlelements_request_cardemv]
.card-emv

``card-emv`` is a child of <<CC_Fields_xmlelements_request_card, card>>. 


[#CC_Fields_xmlelements_request_cardpin]
.card-pin

``card-pin`` is a child of <<CC_Fields_xmlelements_request_card, card>>. 


[#CC_Fields_xmlelements_request_cardraw]
.card-raw

``card-raw`` is a child of
<<CC_Fields_xmlelements_request_card, card>>

KKS: insert when ready
////

[#CC_Fields_xmlelements_request_cardtoken]
.card-token

``card-token`` is a child of
<<CC_Fields_xmlelements_request_payment, payment>> and is the substitute
for <<CC_Fields_xmlelements_request_card, card>>. Due to
<<CreditCard_PaymentFeatures_Tokenization_Introduction, PCI DSS>>
compliance, ``card`` data must not be sent in payment transactions. The _{payment-gateway}_ replaces ``card`` immediately with a token in the transaction response for the first use of a credit card.

include::include/fields/rest_cc/request/req-card-token.adoc[]

[#CC_Fields_xmlelements_request_cardtype]
.card-type

``card-type`` is a child of <<CC_Fields_xmlelements_request_paymentmethod, payment-methods.card-types>>. It provides a list of all supported card types. Please refer to the <<Appendic_Xml, Payment XSD>>
for the complete list of supported card types.

[#CC_Fields_xmlelements_request_creditsenderdata]
.credit-sender-data

``credit-sender-data`` is a child of
<<CC_Fields_xmlelements_request_payment, payment>>.

``credit-sender-data`` is used in OCT non gambling payment processes only.

With this element the merchant can send money to the consumer.
This can be the case, if the merchant is

- an insurance company and has to pay out money to the consumer (insurance case).
- the government and has to pay back taxes.

//-

include::include/fields/rest_cc/request/req-credit-sender-data.adoc[]

[#CC_Fields_xmlelements_request_cruiseindustry]
.cruise-industry

``cruise-industry`` is a child of
<<CC_Fields_xmlelements_request_payment, payment>>.

include::include/fields/rest_cc/request/req-cruise-industry.adoc[]


[#CC_Fields_xmlelements_request_customfield]
.custom-field

``custom-field`` is a child of  
<<CC_Fields_xmlelements_request_payment, payment.custom-fields>>.

In the <<CC_Fields_xmlelements_response_customfield, response > custom-field>> section you can find examples for ready-to-use ``custom-field``.

include::include/fields/rest_cc/request/req-custom-field.adoc[]

[#CC_Fields_xmlelements_request_device]
.device

``device`` is a child of
<<CC_Fields_xmlelements_request_payment, payment>>.

include::include/fields/rest_cc/request/req-device.adoc[]

[#CC_Fields_xmlelements_request_notification]
.notification

``notification`` is a child of 
<<CC_Fields_xmlelements_request_payment, payment.notifications>>.

``notification`` is used to set up <<GeneralPlatformFeatures_IPN, Instant Payment Notification (IPN)>>. It is highly recommended to use IPN. IPN informs you about the outcome of the individual payment processes. By including ``notification`` in the request
you can overwrite the <<GeneralPlatformFeatures_IPN_Configuration, merchant account configuration>>.

include::include/fields/rest_cc/request/req-notification.adoc[]

[#CC_Fields_xmlelements_request_orderitem]
.order-item

``order-item`` is a child of
<<CC_Fields_xmlelements_request_payment, payment.order-items>>. This is a field
for order's items filled by the merchant. Order item amount always includes tax.
Tax can be specified either by tax-amount or by tax-rate.

include::include/fields/rest_cc/request/req-order-item.adoc[]

//// 
[#CC_Fields_xmlelements_request_payloadfield]
.payload-field

``payload-field`` is a child of
<<CC_Fields_xmlelements_request_paymentmethod, payment-methods.payload>>.

////

[#CC_Fields_xmlelements_request_paymentmethod]
.payment-method

``payment-method`` is a child of 
<<CC_Fields_xmlelements_request_payment, payment.payment-methods>>.

The element ``payment-method`` specifies the payment method used for a transaction.

include::include/fields/rest_cc/request/req-payment-method.adoc[]

//// 
vhauss: I designed this "periodic" table from information I gathered from our docu. The size for ``periodic-type`` and ``sequence-type`` must be verified!.

[#CC_Fields_xmlelements_request_periodic]
.periodic

``periodic`` is a child of
<<CC_Fields_xmlelements_request_payment, payment>>. +
``periodic`` is used, if the payment requires subsequent payments refering to each other such as payments of a subscription or an installment. 

The fields can be ignored if no recurring payment is inteded. For all recurring payments the ``periodic`` fields ``periodic-type`` and ``sequence-type`` are mandatory.

include::include/fields/rest_cc/request/req-periodic.adoc[]

////

[#CC_Fields_xmlelements_request_riskinfo]
.risk-info

``risk-info`` is a child of 
<<CC_Fields_xmlelements_request_payment, payment>>.

// Please provide a short explanation for ``risk-info``: Explicit fields for 3D Secure 2? 

include::include/fields/rest_cc/request/req-risk-info.adoc[]


[#CC_Fields_xmlelements_request_segment]
.segment

``segment`` is a child of
<<CC_Fields_xmlelements_request_airlineindustry, airline-industry.itinerary>> and <<CC_Fields_xmlelements_request_cruiseindustry, cruise-industry.itinerary>>. Itinerary segment data is used e.g. within airline industry and cruise industry to specify itineraries of the flight.

include::include/fields/rest_cc/request/req-segment.adoc[]

[#CC_Fields_xmlelements_request_shipping]
.shipping

``shipping`` is a child of
<<CC_Fields_xmlelements_request_payment, payment>>.
For 3D Secure 2 transactions it is highly recommended to send ``shipping`` data in any case, as a complete set of ``shipping`` data reduces the likelihood of a challenge.

////
vhauss: Reviewer, please check: Is the above description correct?
KKS: It also defines the shipping-method! 
////

include::include/fields/rest_cc/request/req-shipping.adoc[]


[#CC_Fields_xmlelements_request_submerchantinfo]
.sub-merchant-info

``sub-merchant-info`` is a child of
<<CC_Fields_xmlelements_request_payment, payment>>. The ``sub-merchant-info`` fields are required for the payment feature <<CreditCard_PaymentFeatures_PaymentFacilitator,Payment Facilitator>>. If you want to use ``sub-merchant-info``, all the fields in this table are mandatory in every initial step of a transaction. It is recommended to set the ``sub-merchant-info`` in all the transaction steps. Otherwise some transactions cannot be completed successfully. ``state`` behaves a little different. Look at the ``state`` _Description_ for details.

include::include/fields/rest_cc/request/req-sub-merchant-info.adoc[]


[#CC_Fields_xmlelements_request_threed]
.three-d

``three-d`` is a child of
<<CC_Fields_xmlelements_request_payment, payment>>.

Additional fields can be found in the
<<CC_Fields_xmlelements_response_threed, response > three-d>> section.

include::include/fields/rest_cc/request/req-three-d.adoc[]


[#CC_Fields_xmlelements_response]
===== Response

[#CC_Fields_xmlelements_response_payment]
.payment

Here you can find the ``payment`` element fields which are sent in the response only.

include::include/fields/rest_cc/response/res-payment.adoc[]


[#CC_Fields_xmlelements_response_avs]
.avs

``avs`` is a child of
<<CC_Fields_xmlelements_response_payment, payment>>.

The <<FraudPrevention_AVS, Address Verification System (AVS)>> is an
advanced level of credit card security that is built in to the {payment-provider-name}
credit card processing network to help thwart identity theft. When a user makes
an online purchase with a credit card their billing address is required. The
house number and postal code of the billing address the user enters is compared
to the billing address held on file by the card issuing bank. If the address
does not match then the transaction can be declined. AVS is an on-demand service
which is configured by {payment-provider-name}.

See the complete list of the
<<FraudPrevention_AVS_WirecardResponseCodes, {payment-provider-name} Response Codes>>.
//KKS: Here we need to think about white labeling > Modify ANCHOR!

include::include/fields/rest_cc/response/res-avs.adoc[]

[#CC_Fields_xmlelements_response_customfield]
.custom-field

``custom-field`` is a child of
<<CC_Fields_xmlelements_response_payment, payment.custom-fields>>.

{payment-provider-name} can configure ``custom-field`` for you.
For possible field values see the following selected examples. If you need the
values of other card products, please contact our <<ContactUs, Merchant Support>>.

NOTE: As the fields ─ shown here ─ are already defined, _Datatype_ and _Size_ information is not necessary. Please refer to <<CC_Fields_xmlelements_request_customfield, custom-field>> for details.

include::include/fields/rest_cc/response/res-custom-field.adoc[]

[#CC_Fields_xmlelements_response_status]
.status

``status`` is a child of <<CC_Fields_xmlelements_response_payment, payment.statuses>>.

``status`` informs merchants about the result of the previously sent
request. They can use this information to redirect consumers to the respective
response page (success page or failure page).

include::include/fields/rest_cc/response/res-status.adoc[]


[#CC_Fields_xmlelements_response_threed]
.three-d

``three-d`` is a child of
<<CC_Fields_xmlelements_response_payment, payment>> .

include::include/fields/rest_cc/response/res-three-d.adoc[]

//-