[#PaymentMethods]
== Payment Methods

Merchants can send payments to _Wirecard Payment Gateway_ using various
payment methods. In order to be able to create a payment using a
specific payment method, the merchant has to have a valid subscription
for this payment method and needs to specify it correctly inside the
payment request. 

The following pages provide an overview about all available payment
methods, their characteristics and the required parameters for
transaction processing.


[#PaymentMethods_NonCreditCard]
=== Non Credit Card

In the environment of the _Wirecard Payment Gateway_ a "Non Credit Card
Payment" is also called "Alternative Payment Method". It comprises the
payment modes Bank Transfer (online and offline), Prepaid, Voucher,
Wallet.

The _Wirecard Payment Gateway_ offers a variety of online and offline
bank transfer payment methods. Each payment method can be used depending
on regulations and laws of regions and countries. For details click the
payment method's name in the table below.

Other payment modes provided by the _Wirecard Payment Gateway_ are
_Prepaid_, _Voucher, Wallet._

Also some Mobile Payment options, which are just a variety of the above
mentioned Payment Methods, fit into that scheme.

.Payment Methods grouped by Payment Mode

The following table describes the non credit card payment modes
supported by the _Wirecard Payment Gateway_, their advantages and which
payment method applies to each of the payment modes:

[%autowidth]
[cols="b,a,a,a"]
|===
|Payment Mode |Description |Advantages |Payment Method

|[[PaymentMethods_PaymentMode_OnlineBankTransfer]]Online Bank Transfer
|Online bank transfer is a payment mode which enables shoppers to
directly do the payment when ordering the product. +
Payment confirmation for this payment mode is sent in real time through
_Wirecard Payment Gateway_. +
After a successful payment, the transaction may no longer be revoked by
the consumer and the merchant can ship the ordered product or service
immediately.
|An online bank transfer offers the option to perform secure online
payments to consumers, who

* do not own a credit/debit card
* do not want to use a credit/debit card when shopping in the internet

Consumers

* do an online bank transfer in their personal online banking
environment
* do not share personal bank account details with the merchant

This increases the conversion rate for merchants as well as the customer
satisfaction.
|<<BancontactMisterCash, Bancontact Mister Cash>> +
<<CarrierBilling, Carrier Billing>> +
<<CIMBClicks, CIMB Clicks>> +
<<eps, eps-Überweisung>> +
<<giropay, giropay>> +
<<ideal, iDEAL>> +
<<Klarna, Klarna Services>> +
<<Maybank2u, Maybank2u>> +
moip Pagamentos +
<<API_PaybyBankapp, Pay by Bank app (Zapp)>> +
<<paydirekt, paydirekt>> +
<<payolution, payolution>> +
<<POLi, POLi>> +
<<Przelewy24, Przelewy24>> +
<<SafetyPay, SafetyPay>> +
<<Sofort, Sofort.>> +
<<Trustly, Trustly>> +
<<TrustPay, TrustPay>> +
|[[PaymentMethods_PaymentMode_OfflineBankTransfer]]Offline Bank Transfer
|Offline bank transfer is a payment mode which enables shoppers to
decouple the payment from the delivery of the product they ordered. +
This means during your shopping event, wherever you do it, you order
something and you pay for it not by directly using your credit card,
your online banking, etc. You tell your merchant that you want to buy
his product and you get a kind of invoice for it. +
With that invoice you can do e.g. a money transfer (SEPA Deposit). +
So order/shipping and payment are decoupled. +
The payment confirmation for this type of payment mode is sent in a
batch process through _Wirecard Payment Gateway_.
|An offline bank transfer offers the option to perform secure online
payments to consumers, who

* do not own a credit/debit card
* do not want to use a credit/debit card shopping in the internet

This increases the conversion rate for merchants as well as the customer
satisfaction.
|<<Boleto, Boleto>> +
<<GuaranteedInvoiceandDirectDebit, Guaranteed Services>> +
<<Klarna, Klarna Services>> +
<<API_POIPIA, Payment on Invoice (POI)/Payment in Advance (PIA)>> +
<<SafetyPay, SafetyPay>> +
<<SEPACreditTransfer, SEPACredit Transfer>> +
<<SEPADirectDebit, SEPA Direct Debit>> +
<<TrustPay, TrustPay>>
|[[PaymentMethods_PaymentMode_Prepaid]]Prepaid
.2+|"Pay with cash on the internet" - this slogan stands for prepaid or
voucher-based payment solutions. +
With this popular payment mode consumers have the possibility to buy
prepaid-cards or vouchers at thousands of participating stores like
kiosks or gas stations. +
The cash or voucher code is used to perform the payment on the
merchant´s checkout page.
.2+|For the merchant a prepaid or voucher payment is

* guaranteed and cannot be revoked by the consumer.
* very popular at kiosks or gas stations.

For consumers who do not want to provide

* credit card data
* account data or credentials
|<<paysafecard, paysafecard>>
|[[PaymentMethods_PaymentMode_Voucher]]Voucher
|<<WirecardVoucher, Wirecard Voucher>>
|[[PaymentMethods_PaymentMode_Wallet]]Wallet
|Wallet is a payment mode which enables shoppers to pay directly from
their Wallet to merchants they want to deal with. So like in online
payment mode the shoppers are enabled to directly do the payment when
ordering the product. +
Payment confirmation for this payment mode is sent in real time through
_Wirecard Payment Gateway_.
|For the merchant, a wallet payment

* is guaranteed by the wallet provider and cannot (in most cases) be
revoked by the consumer.
* is very popular in many countries for payment on the internet.
* provides real time feedback about transaction status (fast shipping).
It allows instant payment notification.

This increases the conversion rate for merchants as well as the customer
satisfaction.

For consumers who do not want to provide

* credit card data
* account data or credentials

In most of the cases

* it is easy to use and register at the wallet provider.
* wallet can be linked to consumer accounts or credit cards for upload.
* wallet can be linked to local popular payment methods for upload.
* only username and password is necessary.
* products can be shipped immediately.
|<<API_AlipayDomestic, Alipay Domestic>> +
<<API_AlipayCrossBorder, Alipay Cross-border>> +
<<API_MasterPass, MasterPass>> +
<<mobicred, mobicred>> +
<<monetaRu, moneta.ru>> +
<<API_PaymentMethods_PayPal, PayPal>> +
<<SkrillDigitalWallet,Skrill Digital Wallet>> +
<<VISACheckout, Visa Checkout>> +
<<API_WeChatQRPay, WeChat QRPay>>
|[[PaymentMethods_PaymentMode_MobilePayment]]Mobile Payment
|Some payment methods are to be used purely on the smartphone (Paybox),
other payment methods offer mobile payment as an additional variant to
their traditional payment possibilities. Therefore it is not possible to
assign mobile payment to either "Credit/Debit Card" or "Non Credit Card
Payment". +
The usage of smartphones and tablets has massively assisted in the
development of mobile payments. Meanwhile, a wide-range of products
are available on the market, using different kinds of technologies.
_Wirecard Payment Gateway_ already supports several mobile payment
options.
|A mobile payment method is an attractive alternative to a consumer's
credit card. Some consumers enjoy the comfort to pay with a mobile
device and charge the monthly telecommunication bill.
|<<paybox, paybox>> +
ApplePay
|===
