include::shortcuts.adoc[]
:date-pattern: YYYY-MM-DD
:timestamp-pattern: YYYY-MM-DDThh:mm:ss

[#CC_Fields]
==== Fields

This is the general field reference for _Credit Card_ transactions.
====
- Format: XML 
- POST requests and responses

//-
====

We provide the request and the response fields in two separate sections:

- <<CC_Fields_xmlelements_request, _Request_>> contains those fields sent in the request (and usually in the response).
- <<CC_Fields_xmlelements_response, _Response_>> contains those fields sent in the response only.

//-

The fields are ordered hierarchically and in separate tables. ``payment`` is the top parent element and all fields that are part of ``payment`` are listed <<CC_Fields_xmlelements_request_payment, in the first table>>. 

Some fields listed in this table are _complex type_ fields, e.g. ``payment.account-holder``. _Complex type_ fields are parents to a number of further fields. We offer separate field tables for all parent elements and their respective fields.

NOTE: The tables are sorted alphabetically. Use *Ctrl + F* if you are looking for a specific field.

For example, ``payment.account-holder`` is a parent of ``address``. Click on the link in the table to view the fields contained in a _complex type_ field.


[#CC_Fields_intro_elements]
===== Field Definitions

Each field table contains the following columns:

- <<CC_Fields_intro_elements_name, Name>>
- <<CC_Fields_intro_elements_cardinality, Cardinality>> (for request elements only)
- <<CC_Fields_intro_elements_dataType, Data Type>>
- <<CC_Fields_intro_elements_Size, Size>> (for request elements only)

//-

IMPORTANT: Field definitions may vary by transaction type. Deviations from standard field definitions are given with the respective transaction type.

[#CC_Fields_intro_elements_name]
====== Name
The field name structure is based on the hierarchical relation between individual elements. +
_Example:_ ``order-items.order-item.article-number`` +

.Structure
[mermaid, CC_Fields_intro_elements_parentchild,svg]
----
graph LR
A(parent-element)-->B
B("child = parent-element")-->C
C(child)
E[order-items.]-->F
F[order-item.]-->G
G[article-number]
class E squared-rect
class F squared-rect
class G squared-rect
----

.XML Structure
[source, xml]
----
<payment>
    <account-holder>
        <address>
----

// Follow up task: With the corresponding excerpt of the XSD we can show the structure of the xml elements.

In the example, the parent element is ``order-items``, and its child ``order-item``. +
``order-item`` itself is also a parent element of its child ``article-number``. 
The hierarchies are sparated by a dot ``.``

[#CC_Fields_intro_elements_cardinality]
====== Cardinality

_Cardinality_ indicates if the field is necessary for the request to work. A field can be either mandatory (M) or optional (O).

- If a field is _mandatory_, it must be included in the request and contain a value. Without this field, the request will fail. +
- If a field is _optional_, it does not have to be included in the request. Including optional fields can have certain advantages. These are included in the respective field description.

[IMPORTANT]
====
Cardinality can depend on the context. In those cases, fields will be marked with "M/O". The _Description_ will explain under which conditions the field is mandatory.

*Example*:``payment.periodic`` 

- ``periodic`` fields are *optional* when you send a request for a one-time payment transaction.
- ``periodic`` fields are *mandatory* when you send a request for one-time payments with one-click checkout, recurring payments, and installment payment transactions.

//-
====

//if we talk about a "periodic-element" we should publish the table as designed in the lines 914 to 937. What do you think?
//KKS: (Y)

//-

[#CC_Fields_intro_elements_dataType]
====== Data Type

_Data Type_ defines the specific characteristics of the input values that can be used for a field. There are seven data types: _String_, _Boolean_, _Date_, _Timestamp_, _Decimal_, _Number_,  and _Enumeration_.

[cols="20,80"]
|===
|Data Type |Description

|String
|A combination of text and numbers which is arbitrary but finite in size. A subset of _String_ values can be defined according to a pattern value, such as ``api-id``. The pattern will be given in the _Description_ column.

|Boolean 
|Has one of two possible values (usually either ``true`` or ``false``).

|Date 
a|Value taken from a calendar (e.g. the date of birth). Format: ``{date-pattern}`` This pattern cannot be customized.

|Timestamp
a|A moment in time defined by a system. Format: ``{timestamp-pattern}`` This pattern cannot be customized.

|Decimal
|A numeric value which has digits before and after the decimal point ``.`` +
Example: the amount of money in a specific currency (e.g. 138.53 EUR).

|Number
|A numeric value that has no decimal places, such as the expiration month of a credit card.

|Enumeration 
|A list of predefined values, e.g. the severity of a status, which can provide the predefined values ``warning``, ``error`` and ``information``.
|===


[#CC_Fields_intro_elements_Size]
====== Size
_Size_ shows how many characters can be used for this field. We provide the maximum value so you can make sure the whole amount of characters will be processed.

In general, the _{payment-gateway}_ allows all characters for each field, depending on the _Data Type_. 

If other rules apply to a field, they will be stated in the _Description_ column of that field.



[#CC_Fields_xmlelements]
===== XML Elements
Click the X in the respective column for request and response fields.

Please refer to our <<Appendix_Xml, XSD>> for the structural relationship between these fields.

[cols="m,,"]
|===
| Field | Request | Response

| payment
| <<CC_Fields_xmlelements_request_payment, X>>
| <<CC_Fields_xmlelements_response_payment, X>>

| account-holder
| <<CC_Fields_xmlelements_request_accountholder, X>>
| 

| address
| <<CC_Fields_xmlelements_request_address, X>>
| 

| airline-industry
| <<CC_Fields_xmlelements_request_airlineindustry, X>>
| 

| audit
| <<CC_Fields_xmlelements_request_audit, X>>
| 

| avs
| 
| <<CC_Fields_xmlelements_response_avs, X>>

| browser
| <<CC_Fields_xmlelements_request_browser, X>>
| 

| card
| <<CC_Fields_xmlelements_request_card, X>>
|  
 
// | card-emv
// | <<CC_Fields_xmlelements_request_cardemv, X>>
// | 

// | card-pin
// | <<CC_Fields_xmlelements_request_cardpin, X>>
// | 

// |card-raw
// | <<CC_Fields_xmlelements_request_cardraw, X>>
// | 

| card-token
| <<CC_Fields_xmlelements_request_cardtoken, X>>
| 

| credit-sender-data
| <<CC_Fields_xmlelements_request_creditsenderdata, X>>
| 

| cruise-industry
| <<CC_Fields_xmlelements_request_cruiseindustry, X>>
| 

| custom-fields
| <<CC_Fields_xmlelements_request_customfield, X>>
| <<CC_Fields_xmlelements_response_customfield, X>>

| device
| <<CC_Fields_xmlelements_request_device, X>>
| 

| notification
| <<CC_Fields_xmlelements_request_notification, X>>
| 

| order-items
| <<CC_Fields_xmlelements_request_orderitem, X>>
| 

| payment-method
| <<CC_Fields_xmlelements_request_paymentmethod, X>>
|

| risk-info
| <<CC_Fields_xmlelements_request_riskinfo, X>>
| 

| segment
| <<CC_Fields_xmlelements_request_segment, X>>
| 

| shipping
| <<CC_Fields_xmlelements_request_shipping, X>>
| 

| status
| 
| <<CC_Fields_xmlelements_response_status, X>>

| sub-merchant-info
| <<CC_Fields_xmlelements_request_submerchantinfo, X>>
| 

| three-d
| <<CC_Fields_xmlelements_request_threed, X>>
| <<CC_Fields_xmlelements_response_threed, X>>
|===

[#CC_Fields_xmlelements_request]
====== Request

[#CC_Fields_xmlelements_request_payment]
.``payment``

Additional ``payment`` fields can be found in the
<<CC_Fields_xmlelements_response_payment, Response > ``payment``>> section.

include::include/fields/rest_cc/payment.adoc[]


[#CC_Fields_xmlelements_request_accountholder]
.account-holder

``account-holder`` is a child of
<<CC_Fields_xmlelements_request_payment, payment>>. +
With the ``account-holder`` merchants can gather detailed information about the
consumer. Please provide all the ``account-holder`` data in your request to make fraud
prevention easier.

include::include/fields/rest_cc/account-holder.adoc[]


[#CC_Fields_xmlelements_request_accountinfo]
.account-info

``account-info`` is a child of
<<CC_Fields_xmlelements_request_accountholder, account-holder>>. +
``account-info`` fields are used with 3DS2. With ``account-info`` merchants can gather detailed information about the consumer. Please provide all the ``account-info`` data in your 3DS2 request to make fraud prevention easier.

include::include/fields/rest_cc/account-info.adoc[]

[#CC_Fields_xmlelements_request_address]
.address

``address`` is a child of
<<CC_Fields_xmlelements_request_accountholder, account-holder>>,
<<CC_Fields_xmlelements_request_airlineindustry, airline-industry>>, and
<<CC_Fields_xmlelements_request_shipping, shipping>>. It is used to
specify the consumer's address and can refer to

- the consumer (for ``account-holder``)
- the ticket issuer (for ``airline-industry``)
- the consumer's shipping address (for ``shipping``). In case of 3DS2 transactions it is highly recommended to send ``shipping.address`` data in any case, as a complete set of ``shipping.address`` data reduces the necessity of a challenge test.

Data can be provided optionally but it helps with fraud checks, if ``address`` is complete.

include::include/fields/rest_cc/address.adoc[]

[#CC_Fields_xmlelements_request_airlineindustry]
.airline-industry

``airline-industry`` is a child of
<<CC_Fields_xmlelements_request_payment, payment>>.

include::include/fields/rest_cc/airline-industry.adoc[]


[#CC_Fields_xmlelements_request_audit]
.audit

``audit`` is a child of
<<CC_Fields_xmlelements_request_payment, payment>>. 
Audit data is displayed in _{enterprise-portal-abbr}_ for each transaction it has been send with.

include::include/fields/rest_cc/audit.adoc[]


[#CC_Fields_xmlelements_request_browser]
.browser

``browser`` is a child of
<<CC_Fields_xmlelements_request_payment, payment>>.

include::include/fields/rest_cc/browser.adoc[]

[#CC_Fields_xmlelements_request_card]
.card

``card`` is a child of  <<CC_Fields_xmlelements_request_payment, payment>>. ``card`` details are sent only in the first transaction request when the card is used for the first time. Due to
<<CreditCard_PaymentFeatures_Tokenization_Introduction, PCI DSS>> compliance, ``card`` details are immediately replaced by a token. Beginning with the first response, this
token is used for every consecutive transaction (request and response) that is performed
with this credit card. Token data is provided with the
<<CC_Fields_xmlelements_request_cardtoken, card-token>> element.

NOTE: Only the transaction type _detokenize_ returns ``expiration-month``,
``expiration-year`` and ``card-type`` in a response. All the other transaction
types return elements of ``card-token`` in the response.

include::include/fields/rest_cc/card.adoc[]

//// 
[#CC_Fields_xmlelements_request_cardemv]
.card-emv

``card-emv`` is a child of <<CC_Fields_xmlelements_request_card, card>>. 


[#CC_Fields_xmlelements_request_cardpin]
.card-pin

``card-pin`` is a child of <<CC_Fields_xmlelements_request_card, card>>. 


[#CC_Fields_xmlelements_request_cardraw]
.card-raw

``card-raw`` is a child of
<<CC_Fields_xmlelements_request_card, card>>

KKS: insert when ready
////

[#CC_Fields_xmlelements_request_cardtoken]
.card-token

``card-token`` is a child of
<<CC_Fields_xmlelements_request_payment, payment>> and is the substitute
for <<CC_Fields_xmlelements_request_card, card>>. Due to
<<CreditCard_PaymentFeatures_Tokenization_Introduction, PCI DSS>>
compliance, ``card`` data must not be sent in payment transactions. The _{payment-gateway}_ replaces ``card`` immediately with a token in the transaction response for the first use of a credit card.

include::include/fields/rest_cc/card-token.adoc[]

[#CC_Fields_xmlelements_request_cardtype]
.card-type

``card-type`` is a child of <<CC_Fields_xmlelements_request_paymentmethod, payment-methods.card-types>>. It provides a list of all supported card types. Please refer to the <<Appendic_Xml, Payment XSD>>
for the complete list of supported card types.

[#CC_Fields_xmlelements_request_creditsenderdata]
.credit-sender-data

``credit-sender-data`` is a child of
<<CC_Fields_xmlelements_request_payment, payment>>.

``credit-sender-data`` is used in OCT non gambling payment processes only.

With this element the merchant can send money to the consumer.
This can be the case, if the merchant is

- an insurance company and has to pay out money to the consumer (insurance case).
- the government and has to pay back taxes.

//-

include::include/fields/rest_cc/credit-sender-data.adoc[]

[#CC_Fields_xmlelements_request_cruiseindustry]
.cruise-industry

``cruise-industry`` is a child of
<<CC_Fields_xmlelements_request_payment, payment>>.

include::include/fields/rest_cc/cruise-industry.adoc[]


[#CC_Fields_xmlelements_request_customfield]
.custom-field

``custom-field`` is a child of  
<<CC_Fields_xmlelements_request_payment, payment.custom-fields>>.

In the <<CC_Fields_xmlelements_response_customfield, response > custom-field>> section you can find examples for ready-to-use ``custom-field``.

include::include/fields/rest_cc/custom-field.adoc[]

[#CC_Fields_xmlelements_request_device]
.device

``device`` is a child of
<<CC_Fields_xmlelements_request_payment, payment>>.

[cols="30,6,9,7,48a"]
|===
| Field | Cardinality | Datatype | Size | Description

| fingerprint |O |String |4096 |A device fingerprint is information collected about a remote computing device for the purpose of identification retrieved on merchants side. Fingerprints can be used to fully or partially identify individual users or devices even when cookies are turned off.
|===

//// 
[#CC_Fields_xmlelements_request_device]
.device

``device`` is a child of
<<CC_Fields_xmlelements_request_payment, payment>>.

The following fields are currently not part of the doc: 
(KKS: added from https://doc.wirecard.com/CreditCard.html#CreditCard_Fields)

| policy-score | O | Integer // Number or Decimal!| ?? | ??
| type | O | ?? | ?? | ??
| operating-system | O | ?? | ?? | ??
| render-options | O | ?? | ?? | ??
| sdk | O | ?? | ?? | ??
|===

////

[#CC_Fields_xmlelements_request_notification]
.notification

``notification`` is a child of 
<<CC_Fields_xmlelements_request_payment, payment.notifications>>.

``notification`` is used to set up <<GeneralPlatformFeatures_IPN, Instant Payment Notification (IPN)>>. It is highly recommended to use IPN. IPN informs you about the outcome of the individual payment processes. By including ``notification`` in the request
you can overwrite the <<GeneralPlatformFeatures_IPN_Configuration, merchant account configuration>>.

[cols="30,6,9,7,48a"]
|===
| Field | Cardinality | Datatype | Size | Description

a| transaction-state

(Attribute of ``notification``)
 |O |String |12 |This is the status of a transaction when IPN will be sent.
a| url

(Attribute of ``notification``)
 |O |String |256 |The URL to be used for the IPN. It overwrites the notification URL that is set up in the merchant configuration.

|===

[#CC_Fields_xmlelements_request_orderitem]
.order-item

``order-item`` is a child of
<<CC_Fields_xmlelements_request_payment, payment.order-items>>. This is a field
for order's items filled by the merchant. Order item amount always includes tax.
Tax can be specified either by tax-amount or by tax-rate.

[cols="30,6,9,7,48a"]
|===
| Field | Cardinality | Datatype | Size | Description

| name |O | String | |Name of the item in the basket.
| article-number |O | String | |EAN or other article identifier for merchant.
| amount |O |Number | |Item's price per unit.
| tax-rate |O |Number | |Item's tax rate per unit.
| quantity |O |Number | |Total count of items in the order.
|===

//// 
[#CC_Fields_xmlelements_request_orderitem]
.order-item

vhauss: Who enters the values? If filled by the merchant: Is ``order-items`` a request or response field?

The following fields are currently not part of the doc:

| description | O | String | ?? | ??
| tax-amount | O | String | ?? | ??
| type | O | Number | ?? | ??
| discount | O | Number | ?? | ??
|===

////

//// 
[#CC_Fields_xmlelements_request_payloadfield]
.payload-field

``payload-field`` is a child of
<<CC_Fields_xmlelements_request_paymentmethod, payment-methods.payload>>.

[cols="30,6,9,7,48a"]
|===
| Field | Cardinality | Datatype | Size | Description

| field-name | M | String | ?? | ??
| field-value | M | String | ?? | ??
|===

////

[#CC_Fields_xmlelements_request_paymentmethod]
.payment-method

``payment-method`` is a child of 
<<CC_Fields_xmlelements_request_payment, payment.payment-methods>>.

The element ``payment-method`` specifies the payment method used for a transaction.

[cols="30,6,9,7,48a"]
|===
| Field | Cardinality | Datatype | Size | Description

a| name 

(Attribute of ``payment-method``) | M |  String | 15 | This is the name of the payment method that that the consumer selected. The value is always ``creditcard``.
//vhauss: According to line 103 "name"'s data type should be "Enumeration"!

a| url 

(Attribute of ``payment-method``) | O | String | 256 | The URL to be used for proceeding with the payment process on provider side.

4+| card-types | ``card-types`` is the parent element of <<CC_Fields_xmlelements_request_cardtype, card-type>>. 

// 2+| payload 3+| ``payload`` is the parent element of <<CC_Fields_xmlelements_request_payload, payload-field>>.
//vhauss: Currently we don't need "payload" as it is not part of the current doc.
|===

//// 
vhauss: I designed this "periodic" table from information I gathered from our docu. The size for ``periodic-type`` and ``sequence-type`` must be verified!.

[#CC_Fields_xmlelements_request_periodic]
.periodic

``periodic`` is a child of
<<CC_Fields_xmlelements_request_payment, payment>>. +
``periodic`` is used, if the payment requires subsequent payments refering to each other such as payments of a subscription or an installment. 

The fields can be ignored if no recurring payment is inteded. For all recurring payments the ``periodic`` fields ``periodic-type`` and ``sequence-type`` are mandatory.

[cols="30,6,9,7,48a"]
|===
| Field | Cardinality | Datatype | Size | Description

| periodic-type | M/O | String | 9 a| Indicates the recurring payment type. This can be +
``recurring``: is used for the recurring payments of a subscription. +
``installment``: is used for the partial payments of an installment payment. +
``ucof``: (<<CreditCard_PaymentFeatures_RecurringTransaction_PeriodicTypes_ucof, Unscheduled Credential on File>>) is used to reference a regularly based transaction to an already successfully submitted transaction. +
``ci``: (Consumer Initiated) identifies the consumer as the initiator of the transaction.
//vhauss: According to line 103 "periodic-type"'s data type should be "Enumeration"!
| sequence-type | M/O | String | 9 a| Indicates the phase of a recurring transaction. This can be +
``first``: is used for the first payment of a recurring series.
``recurring``: is used for all the intermediate payments of a recurring series.
``final``: is used for the last payment of a recurring series.
//vhauss: According to line 103 "sequence-type"'s data type should be "Enumeration"!
| recurring-expire-date| M/O| Date | 10| Mandatory in 3DS2 recurring transactions. Date after which no further recurring payments using this card are allowed. {date-pattern}
| recurring-frequency| M/O | Number| 4| Mandatory in 3DS2 recurring transactions. The minimum number of days between individual payments.   
|===
////

[#CC_Fields_xmlelements_request_riskinfo]
.risk-info

``risk-info`` is a child of 
<<CC_Fields_xmlelements_request_payment, payment>>.

// Please provide a short explanation for ``risk-info``: Explicit fields for 3DS2? 

[cols="30,6,9,7,48a"]
|===
| Field | Cardinality | Datatype | Size | Description

| delivery-timeframe| O| String| 2| The approximate delivery time. +
 Accepted values are: +
 ``01`` = Electronic delivery +
 ``02`` = Same-day delivery +
 ``03`` = Overnight delivery +
 ``04`` = Two-day or more delivery
//vhauss: According to line 103 "delivery-timeframe"'s data type should be "Enumeration"!
| delivery-mail| O| String| 254| The consumer's email address used for electronic delivery of digital goods.
| reorder-items| O| String| 2| The consumer has previously ordered the same item.
 Accepted values are: +
 ``01`` = First-time order +
 ``02`` = Reorder
//vhauss: According to line 103 "reorder-items"'s data type should be "Enumeration"!
| availability| O| String| 2| The consumer is placing an order for merchandise that is not yet available and will be released in the future.
 Accepted values are: +
 ``01`` = Currently available +
 ``02`` = Future availability
//vhauss: According to line 103 "availability"'s data type should be "Enumeration"!
| preorder-date| O| Date| 10| Expected shipping date for pre-ordered goods. {date-pattern}
|===

[#CC_Fields_xmlelements_request_segment]
.segment

``segment`` is a child of
<<CC_Fields_xmlelements_request_airlineindustry, airline-industry.itinerary>> and <<CC_Fields_xmlelements_request_cruiseindustry, cruise-industry.itinerary>>. Itinerary segment data is used e.g. within airline industry and cruise industry to specify itineraries of the flight.

[cols="30,6,9,7,48a"]
|===
| Field | Cardinality | Datatype | Size | Description

| carrier-code | M/O |String	|3	|The 2-letter airline code (e.g. LH, BA, KL) supplied by IATA for each leg of a flight. Mandatory, if itinerary is provided.
// Follow up task: Clarify: Max. Size seems to be rather 2 (2-letter airline code obviously consists of 2 characters.)
| departure-airport-code | M/O |String	|3	|The departure airport code. IATA assigns the airport codes. Mandatory, if itinerary is provided.
| departure-city-code | M/O |String	|32	|The departure City Code of the Itinerary Segment. IATA assigns the airport codes. Mandatory, if itinerary is provided.
| arrival-airport-code | M/O |String	|3	|The arrival airport code of the Itinerary Segment. IATA assigns the airport codes. Mandatory, if itinerary is provided.
| arrival-city-code | M/O |String	|32	|The arrival city code of the Itinerary Segment. IATA assigns the airport codes. Mandatory, if itinerary is provided.
| departure-date | M/O |Date  |  |The departure date for a given leg. Mandatory, if itinerary is provided. {date-pattern}
| arrival-date | M/O |String | |The arrival date for a given leg. Mandatory, if itinerary is provided. {date-pattern}
| flight-number |O |String |6 |The flight number of the Itinerary Segment.
| fare-class |O |String |3 |Used to distinguish between First Class, Business Class and Economy Class, but also used to distinguish between different fares and booking
| fare-basis |O |String	|6 |Represents a specific fare and class of service with letters, numbers, or a combination of both.
| stop-over-code |O |String	|1 |0 = allowed, 1 = not allowed
// | tax-amount |O |Decimal | |The Value Added Tax Amount levied on the transaction amount.
// vhauss: Follow up task: I think "tax-amount" is a field that should be mentioned here (just as "requested-amount")
a| currency 

(Attribute of ``tax-amount``)
|O |String |3 |The currency of the Value Added Tax Amount levied on the transaction amount.
|===

[#CC_Fields_xmlelements_request_shipping]
.shipping

``shipping`` is a child of
<<CC_Fields_xmlelements_request_payment, payment>>.
The consumer provides ``shipping`` only, if they want to receive the ordered
goods or services at a different place than given in ``account-holder``. In case of 3DS2 transactions it is highly recommended to send ``shipping`` data in any case, as a complete set of ``shipping`` data reduces the necessity of a challenge test.

////
vhauss: Reviewer, please check: Is the above description correct?
////

[cols="30,6,9,7,48a"]
|===
| Field | Cardinality | Datatype | Size | Description

| first-name | M | String | 32 | This is first name from shipping information.
//KKS: better descriptions for shipping in 3DS2 field table.
//vhauss: cannot find "first-name" in "11-01-05-3-d-secure-2.adoc".
| last-name | M | String | 32 | This is last name from shipping information.
| phone | O | String | 3 | This is used to specify the phone from shipping information.
//Follow up task: Clarify > how can you specify a phone number with 3 characters?
| email | O | String | 64 | This is used to specify the email from shipping information.
| shipping-method | O | String | 36 a| The shipping method chosen by the consumer.
 Merchants must use the shipping indicator value that applies most accurately to the shipping method. +
 Accepted values are:
- ``home_delivery``: Ship to consumer's billing address. +
- ``verified_address_delivery``: Ship to another address known to and verified by the merchant. +
- ``other_address_delivery``: Ship to an address that differs from the consumer's billing address. +
- ``store_pick_up``: "Ship to Store" / Pick-up at local store (store address in shipping address fields). +
- ``digital_goods``: Digital goods (includes online services, electronic gift cards, and redemption codes). +
- ``digital_tickets``: Travel and event tickets, not shipped. +
- ``other_verified``: Other (e.g. gaming, digital services, e-media subscriptions)
//vhauss: According to line 103 "shipping-method"'s data type should be "Enumeration"!
// "11-01-05-3-d-secure-2.adoc" allows only a size of 2 characters. How can this be accomplished? Are there 2 character shortcuts for the different methods available? If so, please provide them.
| tracking-number | O | String | 64 | This is used to specify the tracking number from shipping information.
| tracking-url | O | String | 2000 | This is used to specify the tracking url from shipping information.
| shipping-company | O | String | 64 | This is used to specify the shipping company from shipping information.
| return-tracking-number | O | String | 64 | This is used to specify the return tracking number from shipping information.
| return-tracking-url | O | String | 2000 | This is used to specify the return tracking URL from shipping information.
| return-shipping-company | O | String | 36 | This is used to specify the return shipping company from shipping information.
4+| address | <<CC_Fields_xmlelements_request_address, address>> is a child element of ``shipping``.
|===

[#CC_Fields_xmlelements_request_submerchantinfo]
.sub-merchant-info

``sub-merchant-info`` is a child of
<<CC_Fields_xmlelements_request_payment, payment>>.

[cols="30,6,9,7,48a"]
|===
| Field | Cardinality | Datatype | Size | Description

| id | O | String |15 | If you want to use <sub-merchant-info> _id_ is mandatory in every initial step of a transaction. It is recommended to set the <sub-merchant-info> in all the transaction steps. Otherwise some transactions cannot be completed successfully.
| name	| O | String |22 | If you want to use <sub-merchant-info> _name_ is mandatory in every initial step of a transaction. It is recommended to set the <sub-merchant-info> in all the transaction steps. Otherwise some transactions cannot be completed successfully.
| country | O | String |2 | If you want to use <sub-merchant-info> _country_ is mandatory in every initial step of a transaction. It is recommended to set the <sub-merchant-info> in all the transaction steps. Otherwise some transactions cannot be completed successfully.
| state | M/O | String |3 | Mandatory, when _country_ =  US or CA. +
For all other countries _state_ is optional. If _country_ is neither US nor CA, do not send this field at all in the request.
| city | O | String |13 |If you want to use <sub-merchant-info> _city_ is mandatory in every initial step of a transaction. It is recommended to set the <sub-merchant-info> in all the transaction steps. Otherwise some transactions cannot be completed successfully.
| street | O | String |38 |If you want to use <sub-merchant-info> _street_ is mandatory in every initial step of a transaction. It is recommended to set the <sub-merchant-info> in all the transaction steps. Otherwise some transactions cannot be completed successfully.
| postal-code | O | String |10	|If you want to use <sub-merchant-info> _postal-code_ is mandatory in every initial step of a transaction. It is recommended to set the <sub-merchant-info> in all the transaction steps. Otherwise some transactions cannot be completed successfully.
|===

//// 
[#CC_Fields_xmlelements_request_submerchantinfo]
.sub-merchant-info

The following fields are currently not part of the doc:

| appid | O | String | ?? | ??
| category | O | String | ?? | ??
| store-id | O | String | ?? | ??
| store-name | O | String | ?? | ??
| payment-facilitator-id | O | String | ?? | ??
////

[#CC_Fields_xmlelements_request_threed]
.three-d

``three-d`` is a child of
<<CC_Fields_xmlelements_request_payment, payment>>.

Additional fields can be found in the
<<CC_Fields_xmlelements_response_threed, response > three-d>> section.

[cols="30,6,9,7,48a"]
|===
| Field | Cardinality | Datatype | Size | Description

| attempt-three-d | O |String |1 |Indicates that the Transaction Request should proceed with the 3D Secure workflow if the [Card Holder] is enrolled.  Otherwise, the transaction proceeds without 3D Secure. This field is used in conjunction with Hosted Payment Page.
|[[CreditCard_Fields_ThreeD_Pares]]
 pares | M/O |String |2048 | Mandatory in a 3D Secure transaction. This is the digitally signed, base64-encoded authentication response message received from the issuer.
| eci | M/O |String |2 | Mandatory in a 3D Secure transaction. This indicates the status of the VERes.
| xid | M/O |String |36 | Mandatory in a 3D Secure transaction. This is the unique transaction identifier.
| cardholder-authentication-value | M/O |String |1024 | Mandatory in a 3D Secure transaction. The CAVV is a cryptographic value generated by the Issuer. For Visa transaction it is called CAVV (Cardholder Authentication Verification Value) for MasterCard it is either called Accountholder Authentication Value (AAV) or Universal Cardholder Authentication Field (UCAF).
| cardholder-authentication-status | M/O |String |1 | Mandatory in a 3D Secure transaction. Status of 3D Secure check.
| pareq | M/O |String |16000 | Mandatory in a 3D Secure transaction. This is a base64-encoded request message created for cards participating in the 3D program. The PaReq is returned by the issuer's ACS via the VISA or MasterCard directory to the _{payment-gateway}_ and from here passed on to the merchant.
| acs-url | M/O |String |2048 | Mandatory in a 3D Secure transaction. The issuer URL to where the merchant must direct the enrolment check request via the cardholder's browser. It is returned only in case the cardholder is enrolled in 3D Secure program.
| ds-transaction-id | | String| 36| Universally unique transaction identifier assigned by the Directory Server to identify a single transaction. Required for external 3D Secure servers not provided by {payment-provider-name}.
//vhauss: Is "ds-transaction-id" a response field?
| riid | O | String |   a| Indicates the type of 3RI request. +
//vhauss: Is the size = 2? Please verify!
Accepted values are: +
01 = Recurring transaction +
02 = Installment transaction +
03 = Add card +
04 = Maintain card information +
05 = Account
//vhauss: According to line 103 "riid"'s data type should be "Enumeration"!
| server-transaction-id | O | String |   | 
//vhauss: any information about "Size" and "Description" available? Please provide.
| version | O | String | 5 a| Identifies the version of 3D Secure authentication used for the transaction. Accepted values are: ``1.0``, or ``2.1``. Uses default value ``1.0`` if the version is not provided in the request.
| ds-transaction-id | O | String | 36 a| Universally unique transaction identifier assigned by the Directory Server to identify a single transaction. Required for external 3D Secure servers not provided by {payment-provider-name}.
//KKS: Field description info from "riid" to "ds-transaction" taken from: https://doc.wirecard.com/CreditCard.html#CreditCard_3DS2_Fields

//KKS: Should this table also contain all 3DS fields (1 & 2)? Personally, I would think it would make sense to have it all in one place. See: https://doc.wirecard.com/CreditCard.html#CreditCard_3DS2_Fields - still pending updates!
|===

[#CC_Fields_xmlelements_response]
===== Response

[#CC_Fields_xmlelements_response_payment]
.payment

Here you can find the ``payment`` element fields which are sent in the response only.

[cols="30,9,7,48a"]
|===
|Field |Datatype |Size |Description

| transaction-id | String | 36 | This is the unique identifier for a transaction.
| transaction-state | String | 12 | This is the status of a transaction.
| completion-time-stamp | Timestamp |  | This is the timestamp of completion of request. {timestamp-pattern}
| avs-code | String | 24 | This is the result of address's validation.
| csc-code  | String | 12 | Code indicating Card Verification Value (CVC/CVV) verification results.
| consumer-id  | String | 50 | The id of the consumer.
| api-id | String | 36 | The api-id is always returned in the notification. ``api-id`` is a string with a pattern value. 
| signature  |  |  | The Signature info, consisting of ``SignedInfo``, ``SignatureValue`` and ``KeyInfo``.
//KKS:?? are SignedInfo etc. fields?
//vhauss: "Datatype" and "Size" are missing! Please provide correct values!
//vhauss: ``signature`` is a complex type, consists of the elements type, value and encoding. I don't know where the above values come from. 
// Follow up task: According to our new structure ``signature`` requires an own table.
| instrument-country | String | 256 | The instrument country retrieves the issuer country of a certain credit card. It returns a two-digit country code, such as +
``DE`` (Germany), +
``ES`` (Spain), +
``FR`` (France), or +
``IT`` (Italy).
//vhauss: Here I am not quite sure: Is "instrument-country" also, according to line 103, data type "Enumeration"?
3+| avs | <<CC_Fields_xmlelements_response_avs, avs>> is a child element of ``payment``.
3+| custom-fields | ``custom-fields`` is the parent element of  <<CC_Fields_xmlelements_response_customfield, custom-field>>.
3+| statuses | ``statuses`` is the parent element of <<CC_Fields_xmlelements_response_status, status>>.
3+| three-d | <<CC_Fields_xmlelements_response_threed, three-d>> is a child element of ``payment``.
|===

[#CC_Fields_xmlelements_response_avs]
.avs

``avs`` is a child of
<<CC_Fields_xmlelements_response_payment, payment>>.

The <<FraudPrevention_AVS, Address Verification System (AVS)>> is an
advanced level of credit card security that is built in to the {payment-provider-name}
credit card processing network to help thwart identity theft. When a user makes
an online purchase with a credit card their billing address is required. The
house number and postal code of the billing address the user enters is compared
to the billing address held on file by the card issuing bank. If the address
does not match then the transaction can be declined. AVS is an on-demand service
which is configured by {payment-provider-name}.

See the complete list of the
<<FraudPrevention_AVS_WirecardResponseCodes, {payment-provider-name} Response Codes>>.
//KKS: Here we need to think about white labeling > Modify ANCHOR!

[cols="30,9,7,48a"]
|===
|Field |Datatype |Size |Description

| result-code | String | 5 | AVS result code.
| result-message | String | 256 | AVS result message.
| provider-result-code | String | 5 | AVS provider result code.
| provider-result-message | String | 256 | AVS provider result message.
|===

[#CC_Fields_xmlelements_response_customfield]
.custom-field

``custom-field`` is a child of
<<CC_Fields_xmlelements_response_payment, payment.custom-fields>>.

{payment-provider-name} can configure ``custom-field`` for you.
For possible field values see the following selected examples. If you need the
values of other card products, please contact our <<ContactUs, Merchant Support>>.

NOTE: As the fields ─ shown here ─ are already defined, _Datatype_ and _Size_ information is not necessary. Please refer to <<CC_Fields_xmlelements_request_customfield, custom-field>> for details.


[cols="30,48a"]
|===
|Field | Description

|CardCategoryExt a|Possible field values are: +
``M`` (Consumer) +
``C`` (Commercial)

|CardProductID a| For possible field values see the following selected examples. If you need the values of other card products, please contact our <<ContactUs, Merchant Support>>.

VISA: + 
``A`` (VISA Traditional) +
``F`` (ViSA Classic) +
``G`` (VISA Business) +
``I`` (VISA Infinite) +

MasterCard: +
``MCC`` (MasterCard® Consumer) +
``MCD`` (Debit MasterCard® Card) +
``MCS`` (MasterCard® Consumer - Standard)

|CardCategory a|Possible field values are: +
``D`` (Debit) +
``C`` (Credit) +
``P`` (Prepaid)
|===

[#CC_Fields_xmlelements_response_status]
.status

``status`` is a child of <<CC_Fields_xmlelements_response_payment, payment.statuses>>.

``status`` informs merchants about the result of the previously sent
request. They can use this information to redirect consumers to the respective
response page (success page or failure page).

[cols="30,9,7,48a"]
|===
|Field |Datatype |Size |Description

a| code 

(Attribute of ``status``) | String | 12 | This is the <<StatusCodes_InDetail, code of the status>> of a transaction.

a| description 

(Attribute of ``status``)| String | 256 | This is the description of the status code of a transaction.

a| severity

(Attribute of ``status``) | String | 20 | This field gives information about the severity. It can be either ``warning``, ``error`` or ``information``.
|===

[#CC_Fields_xmlelements_response_threed]
.three-d

``three-d`` is a child of
<<CC_Fields_xmlelements_response_payment, payment>> .

[cols="30,9,7,48a"]
|===
|Field |Datatype |Size |Description

| liability-shift-indicator | String | 2048 | Liablilty shift can be enabled for 3D Secure consumers.
|===

//-