:payment-method-name: Klarna
//include::shortcuts.adoc[]

[#KlarnaV2_TransactionTypes_captureAuthorization]
===== capture-authorization

When the goods or services are ready to be delivered, you have to capture an authorized (=reserved) order fully or partially.

Depending on your merchant configuration, there are two options of invoice creation triggered by a _capture-authorization_:

- _{payment-method-name}_ sends an invoice to your consumer.
- _{payment-method-name}_ sends payment instructions to your consumer according to the
provided invoice delivery option:
  ** email
  ** mail
  ** It can be downloaded and enclosed in the delivered package. +
The download link is provided regardless of the invoice delivery
option within the response. The link is valid for 30 days and will be
removed afterwards. 

If _{payment-method-name}_ provides payment instructions, you are responsible to send the invoice to your consumer. The payment instructions show the _{payment-method-name}_ bank account requisites, where the payment should be provided to.

[NOTE]
====
*** You cannot add new articles.
    *** You cannot change the price of the ordered items,
otherwise the _capture-authorization_ transaction will be rejected.
    *** Every partial capture triggers the creation and sending of a new invoice/payment instruction.

//-
====

Once an _authorization_ is captured, the due date for payment is set. The
default invoice due date is 14 days after activation.

_{payment-method-name}_ pays the order amount to you according to the agreed billing period.

To unambiguously refer to a specific _authorization_, you need the ``parent-transaction-id``, which is the ``transaction-id`` of the preceding _authorization_ or _adjust-authorization_.

[#KlarnaV2_TransactionTypes_captureAuthorization_Workflow]
====== _capture-authorization_ Workflow

[mermaid,Klarnav2_workflow_captureAuthorization,svg,subs=attributes+]
----
sequenceDiagram
    participant M as Merchant
    participant W as WPG
    participant K as Klarna
note over M: activates order
M->>W: sends "capture-authorization" request
W->>+K: creates and sends<br/>"capture-authorization"
Note over K: captures order
K->>-W: sends capture response
W->>M: sends "capture-authorization" response
Note over M: processes<br/>"capture-authorization"<br/>response
----


. -> Send an _adjust-authorization_ request. This request must contain the ``parent-transaction-id``, which is the ``transaction-id`` of the preceding _authorization_ or _adjust-authorization_.

 ** If the _capture-authorization_
request does not contain order items, _{payment-gateway}_ captures the total order amount, i.e. all order items of the preceding _authorization_ transaction are captured and must be delivered.
  ** Multiple partial captures are possible by sending
_capture-authorization_ requests with order items to be captured.
. _{payment-gateway}_ forwards the request to _{payment-method-name}_. 
. _{payment-method-name}_ returns the capture result.
. _{payment-gateway}_ sends you the _capture-authorization_ response which contains the status code.
. -> Process the _capture-authorization_ response.

//-

[#KlarnaV2_TransactionTypes_captureAuthorization_Fields]
====== _capture-authorization_ Fields

The following fields are either mandatory (M) or optional (O) in the capture process.

[%autowidth]
[cols="e,,,,,"]
|===
|Field |Request |Response |Data Type |Size |Description

|merchant-account-id 
|O 
|M 
|Alphanumeric 
|36 
|A unique identifier assigned to every merchant account (by {payment-provider-name}).

|request-id 
|M
|M 
|Alphanumeric 
|36 
a|A unique identifier assigned by the merchant
to each request. Used when searching for or referencing it later.

As the request ID must be unique, ``{{$guid}}`` serves as a placeholder; Postman
uses it to generate a random ``request-id`` for testing.

Allowed characters:  ``[a-z0-9-\_]``.

|parent-transaction-id
|M
|M
|Alphanumeric 
|36
|Enter the ``transaction-id`` of the preceding _authorization_ or _adjust-authorization_.

|transaction-type 
|M 
|M 
|Alphanumeric
|30 
|The requested transaction type. Set this field to `capture-authorization`.

|requested-amount  
|M
|M
|Numeric
|18,3
a|Total order amount to be resered. The number of decimal places depends on the currency. 

[NOTE:]
====
* The requested amount must be equal to the amount sum of all order items.
* The sum of all _capture-authorization_ transactions must not exceed the amount of the preceding _authorization_ or _adjust-authorization_ transaction.
====

Use ``,`` (comma) as separator.

|[[KlarnaV2_Fields_requestedAmount_currency]]requested-amount@currency 
|M 
|M 
|Alphanumeric
|3 
a|The <<KlarnaV2_CountriesCurrencies, currency>> of the requested/contested
transaction amount. +
Format: 3-character abbreviation according to ISO 4217.

|order-detail
|O
|O
|Alphanumeric
|
|Message or other important information to the consumer on the
invoice/payment instructions. +
Requires a setting in your <<ContactUs, merchant configuration>>.

|payment-methods. +
payment-method@name
|O 
|M 
|Alphanumeric
|15 
a|The name of the payment method used for the transaction. 

Possible values: 

  - ``klarna-finance`` for payment in installments (Pay later)
  - ``klarna-debit`` for _{payment-method-name}_ direct debit (Pay now) 
  - ``klarna-transfer`` for _{payment-method-name}_ bank transfer (Pay now)
  - ``klarna-paylater`` for _{payment-method-name}_ payment on invoive (Pay later)
//-

|locale	
|- 
|M 
|Alphanumeric
|5 
|A 5-letter code which indicates what <<KlarnaV2_Locales, language>> the payment page is rendered in (RFC 1766).

|transaction-id 
|-
|M 
|Alphanumeric
|36
|A unique identifier assigned for every transaction. Generated by {payment-provider-name} Used when searching for or referencing it later.

|transaction-state 
|-
|M 
|Alphanumeric
|12
a|Transaction status. +
Possible values: 

  - ``success``
  - ``failed``

//-

|completion-time-stamp
|-
|M
|DateTime
|
|The timestamp documents the time and date when the transaction was completed.

|notifications. +
notification-url 
|O 
|O 
|Alphanumeric
|256
|The URL to which _{payment-gateway}_ sends an <<GeneralPlatformFeatures_IPN_NotificationExamples, Instant Payment Notification (IPN)>> for pending reservations or the transaction outcome. It overwrites the notification URL that is set up in your merchant configuration.

5+<.>s|order-items.order-item.
s|Description of a specific order item.

|name 
|M 
|M 
|Alphanumeric
|256 
|Name of the item in the shopping basket.

|description 
|O 
|O 
|Alphanumeric
|1024 
|Description of the item in the shopping basket.

|article-number 
|O 
|O 
|Alphanumeric
|256 
|EAN or other merchant-side article identifier.

|quantity 
|M
|M
|Numeric 
|n/a  
|Total number of this item in the shopping basket.

|amount 
|M 
|M 
|Numeric 
|18,3 
|Item’s price per unit.  +

Use ``,`` (comma) as separator.

|amount@currency 
|M 
|M 
|Alphanumeric
|3 
|<<KlarnaV2_CountriesCurrencies, Currency>> of this item's price. Must match the <<KlarnaV2_Fields_requestedAmount_currency, order currency (requested amount currency)>>. +
Format: 3-character abbreviation according to ISO 4217.

|type
|M 
|M
|Alphanumeric
|n/a
a|Order item type. +
Possible values: 

  - ``shipment_fee``
  - ``handling_fee``
  - ``discount``
  - ``physical``
  - ``sales_tax``
  - ``digital``
  - ``gift_card``
  - ``store_credit``

//-

|tax-rate 
|O 
|O 
|Numeric
|5,2 
a|Item’s tax rate per unit in percent. 

|tax-amount 
|O 
|O 
|Numeric
|5,2 
a|Item’s tax value per unit. 

|discount	
|O
|O
|Numeric
|18,3 
|The discount value for one order item.  +
Use ``,`` (comma) as separator.

5+<.>s|account-holder.
s|Contains consumer data.

|date-of-birth 
|-
|O 
|Date 
|
|Consumer's date of birth. +
Format: _{payment-method-name}_ accepts only ``dd-MM-YYYY`` or ``YYYY-MM-dd``. + 
If you provide a different format, __{payment-method-name}__ prompts the consumer to enter their birth date during the payment process.

|first-name 
|- 
|O 
|Alphanumeric
|32 
|Consumer's first name.

|last-name 
|- 
|O 
|Alphanumeric
|32 
|Consumer's last name.

|email 
|- 
|O 
|Alphanumeric
|64 
|Consumer's email address.

|gender 
|
|O 
|Alphanumeric
|1 
|Consumer's gender.

|phone 
|- 
|O 
|Alphanumeric
|32 
|Consumer's phone number. +
Phone numbers need to be validated. Click <<Klarna_phoneNumberValidation, here>> for details.

5+<.>s|account-holder.address.
s|Consumer's address.

|street1 
|- 
|O 
|Alphanumeric
|128 
|Street of the consumer's address.

|street2	
|- 
|O 
|Alphanumeric
|128 
|House number of the consumer's address.	 

|city 
|- 
|O 
|Alphanumeric
|32 
|City of the consumer's address.

|country 
|- 
|M 
|Alphanumeric
|3 
|<<KlarnaV2_CountriesCurrencies, Country code>> of the consumer's address.

|postal-code 
|- 
|O 
|Alphanumeric
|16 
|Postal/ZIP code of the consumer's address.

5+<.>s|shipping. 
s|Consumer's shipping information.

|first-name 
|- 
|O 
|Alphanumeric
|32 
|First name of the recipient.  

|last-name 
|- 
|O 
|Alphanumeric
|32 
|Last name of the recipient.

|email 
|- 
|O 
|Alphanumeric
|64 
|Email address of the recipient.	

|phone 
|- 
|O 
|Alphanumeric
|32 
|The phone number of the recipient. +
Phone numbers need to be validated. Click <<Klarna_phoneNumberValidation, here>> for details.

|tracking-number
|O
|O
|Alphanumeric
|64
|The delivery tracking number for this order.

5+<.>s|shipping.address.
s|Consumer's shipping address.

|street1 
|- 
|O 
|Alphanumeric
|128 
|Street of the recipient's address.

|street2 
|- 
|O 
|Alphanumeric
|128 
|House number of the recipient's address.	 

|house-extension 
|- 
|O 
|Alphanumeric
|32 
|House extension of the recipient's address.	 

|city 
|- 
|O 
|Alphanumeric
|32 
|City of the recipient's address.

|country 
|-
|O
|Alphanumeric
|3 
|Country code of the recipient's address.

|postal-code 
|- 
|O 
|Alphanumeric
|16 
|Postal/ZIP code of the recipient's address.

5+<.>s|statuses.status.
s|Contains information on the status of a specific transaction.

|code
|
|M
|Alphanumeric
|12
|Transaction status code.

|description
|
|M
|Alphanumeric
|256
|Transaction status message.

|severity
|
|M
|Alphanumeric
|20
a|The definition of the status message. Possible values:

- ``information``
- ``warning``
- ``error``

//-

|===

[#KlarnaV2_TransactionTypes_captureAuthorization_Samples]
====== _capture-authorization_ Samples

._capture-authorization_ Request
----
include::samples/xml/Klarnav2_captureAuthorization_request.xml[]
----

._capture-authorization_ Response
----
include::samples/xml/Klarnav2_captureAuthorization_response.xml[]
----
