:payment-method-name: Klarna

[#Klarnav2_TransactionTypes_authorization]
===== _authorization_/_pending-authorization_
_{payment-method-name}_ performs a risk check before accepting an order. Furthermore, _{payment-method-name}_ flags some orders for additional review and transmits ``fraud_status pending`` to _{payment-gateway}_. For this status, _{payment-gateway}_ uses the transaction type ``pending-authorization`` and creates the final authorization transaction once _{payment-method-name}_ has completed the risk check.

If _{payment-method-name}_ accepts the order, it guarantees the paymentonce the authorization has been captured.

[#KlarnaV2_TransactionTypes_authorization_Workflow]
====== _authorization_/_pending-authorization_ Workflow

[mermaid,Klarnav2_workflow_authorization,svg,subs=attributes+]
----
sequenceDiagram
    participant C as Consumer
    participant M as Merchant
    participant W as WPG
    participant K as Klarna
C->>M: proceeds to checkout
M->>W: sends "authorization" request
W->>K: sends "check-signature" and "get-url"
K->>W: creates and sends session token
W->>+K: creates and sends<br/>"pending-authorization"
Note over K: performs <br/> basic risk check
K->>-W: sends basic risk check result
Note over W: updates <br/>"pending-authorization"
    alt basic risk check result ok
        W->>M: sends "authorization" response
    else advanced risk check result pending
        W->>M: sends "pending-authorization" response
    end
M->>C: redirects to payment status page
    alt advanced risk check required
       Note over K: performs <br/>advanced risk check
       K->>W: sends risk check result notification
       W->>M: processes notification and <br/>sends "authorization" response
       M->>C: redirects to payment status page
    end
----

. Consumer checks out products.
. -> Send an _authorization_ request to _{payment-gateway}_. This request must contain order data (such as amount, order number, order items), consumer data (e.g. name, billing
and shipping address, client IP address).
. _{payment-gateway}_ forwards the request to _{payment-method-name}_.
. _{payment-method-name}_ creates a session token and sends it to _{payment-gateway}_.
. _{payment-gateway}_ creates a _pending-authorization_ transaction.
. _{payment-method-name}_ performs a basic risk check:
  - If _{payment-method-name}_ accepts the order, it guarantees the payment once the _authorization_ has been captured.
  - If _{payment-method-name}_ does not accept the order, the _authorization_ is
rejected with a corresponding error code.
  - In some cases, _{payment-method-name}_ performs an <<Klarnav2_TransactionTypes_authorization_advancedRiskCheck, advanced risk check>>.
. _{payment-gateway}_  forwards the risk check result (with the corresponding status code) to you:
  - Basic risk check ok: +
   _{payment-gateway}_ sends you an _authorization_ success response and an <<GeneralPlatformFeatures_IPN_NotificationExamples, Instant Payment Notification (IPN)>>.
  - Basic risk check failed: +
   _{payment-gateway}_ sends you an _authorization_ failure response and an <<GeneralPlatformFeatures_IPN_NotificationExamples, IPN>>.
  - Advanced risk check necessary: +
   The _authorization_ is pending during the advanced risk check. The payment cannot be immediately authorized.
  _{payment-gateway}_ sends you a _pending-authorization_ response and an <<GeneralPlatformFeatures_IPN_NotificationExamples, IPN>>.
. -> Inform your consumer on the payment process outcome.

. [[Klarnav2_TransactionTypes_authorization_advancedRiskCheck]]If _{payment-method-name}_ performs an advanced risk check: +
+
_{payment-gateway}_ retrieves the risk check result every 2 hours.
+
9.1 _{payment-method-name}_ sends the advanced risk check result to _{payment-gateway}_. +
9.2  _{payment-gateway}_ processes the advanced risk check result and sends you an _authorization_ response and an <<GeneralPlatformFeatures_IPN_NotificationExamples, IPN>>. 
+
[NOTE]
====
If you do not receive an IPN after 26 hours (e.g. due to
a technical error), you can check the status
of a _pending-authorization_ by using the feature <<GeneralPlatformFeatures_RetrieveTransaction_TransactionID, Retrieve Transaction by Request ID>>.

  ** If the advanced risk has been completed, _{payment-gateway}_ returns the new _authorization_ transaction with the response.
  ** Otherwise, _{payment-gateway}_ returns the HTTP code 404. Please <<ContactUs, contact Wirecard Customer Support>>
====
9.3 -> Inform your consumer on the payment process outcome.

//-

[#KlarnaV2_TransactionTypes_authorization_Fields]
====== _authorization_/_pending-authorization_ Fields

The following fields are either mandatory (M) or optional (O) in the authorization process.

[%autowidth]
[cols="e,,,,,"]
|===
|Field |Request |Response |Data Type |Size |Description

|merchant-account-id 
|M 
|M 
|Alphanumeric 
|36 
|A unique identifier assigned
to every merchant account (by {payment-provider-name}).

|request-id 
|M
|M 
|Alphanumeric 
|150 
a|A unique identifier assigned by the merchant
to each request. Used when searching for or referencing it later.

As the request ID must be unique, ``{{$guid}}`` serves as a placeholder; Postman
uses it to generate a random ``request-id`` for testing.

Allowed characters:  ``[a-z0-9-\_]``.

|transaction-type 
|M 
|M 
|Alphanumeric
|30 
|The requested transaction type. Set this field to `authorization`.

|requested-amount  
|M
|M
|Numeric
|18,3
|Total order amount to be resered. The number of decimal places depends on the currency. +
The requested amount must be equal to the amount sum of all order items.

Use ``,`` (comma) as separator.

|[[KlarnaV2_Fields_requestedAmount_currency]]requested-amount@currency 
|M 
|M 
|Alphanumeric
|3 
a|The <<KlarnaV2_CountriesCurrencies, currency>> of the requested/contested
transaction amount. +
Format: 3-character abbreviation according to ISO 4217.

|payment-methods. +
payment-method@name
|M 
|M 
|Alphanumeric
|15 
a|The name of the payment method used for the transaction. 

Possible values: 

  - ``klarna-finance`` for payment in installments (Pay later)
  - ``klarna-debit`` for _{payment-method-name}_ direct debit (Pay now) 
  - ``klarna-transfer`` for _{payment-method-name}_ bank transfer (Pay now)
  - ``klarna-paylater`` for _{payment-method-name}_ payment on invoive (Pay later)
//-

|order-number	
|O 
|O 
|Alphanumeric
|255 
|Order number of the merchant. +
If set, it shows as "order number" on _{payment-method-name}_'s payment confirmation page.

|locale	
|M 
|M 
|Alphanumeric
|5 
|A 5-letter code which indicates what <<KlarnaV2_Locales, language>> the payment page is rendered in (RFC 1766).

|transaction-id 
|-
|M 
|Alphanumeric
|36
|A unique identifier assigned for every transaction. Generated by {payment-provider-name} Used when searching for or referencing it later.

|transaction-state 
|-
|M 
|Alphanumeric
|12
a|Transaction status. +
Possible values: 

  - ``success``
  - ``failed``

//-

|completion-time-stamp
|-
|M
|DateTime
|
|The timestamp documents the time and date when the transaction was completed.

|notifications. +
notification-url 
|O 
|O 
|Alphanumeric
|256
|The URL to which _{payment-gateway}_ sends an <<GeneralPlatformFeatures_IPN_NotificationExamples, Instant Payment Notification (IPN)>> for pending reservations or the transaction outcome. It overwrites the notification URL that is set up in your merchant configuration.

5+<.>s|account-holder.
s|Contains consumer data.

|date-of-birth 
|O 
|O 
|Date 
|
|Consumer's date of birth. +
Format: _{payment-method-name}_ accepts only ``dd-MM-YYYY`` or ``YYYY-MM-dd``. + 
If you provide a different format, __{payment-method-name}__ prompts the consumer to enter their birth date during the payment process.

|first-name 
|O 
|O 
|Alphanumeric
|32 
|Consumer's first name.

|last-name 
|O 
|O 
|Alphanumeric
|32 
|Consumer's last name.

|email 
|O 
|O 
|Alphanumeric
|64 
|Consumer's email address.

|gender 
|O 
|O 
|Alphanumeric
|1 
|Consumer's gender.

|phone 
|O 
|O 
|Alphanumeric
|32 
|Consumer's phone number. +
Phone numbers need to be validated. Click <<Klarna_phoneNumberValidation, here>> for details.

5+<.>s|account-holder.address.
s|Consumer's address.

|street1 
|O 
|O 
|Alphanumeric
|128 
|Street of the consumer's address.

|street2	
|O 
|O 
|Alphanumeric
|128 
|House number of the consumer's address.	 

|city 
|O 
|O 
|Alphanumeric
|32 
|City of the consumer's address.

|country 
|M 
|M 
|Alphanumeric
|3 
|<<KlarnaV2_CountriesCurrencies, Country code>> of the consumer's address.

|postal-code 
|O 
|O 
|Alphanumeric
|16 
|Postal/ZIP code of the consumer's address.

5+<.>s|shipping. 
s|Consumer's shipping information.

|first-name 
|O 
|O 
|Alphanumeric
|32 
|First name of the recipient.  

|last-name 
|O 
|O 
|Alphanumeric
|32 
|Last name of the recipient.

|email 
|O 
|O 
|Alphanumeric
|64 
|Email address of the recipient.	

|phone 
|O 
|O 
|Alphanumeric
|32 
|The phone number of the recipient. +
Phone numbers need to be validated. Click <<Klarna_phoneNumberValidation, here>> for details.

5+<.>s|shipping.address.
s|Consumer's shipping address.

|street1 
|O 
|O 
|Alphanumeric
|128 
|Street of the recipient's address.

|street2 
|O 
|O 
|Alphanumeric
|128 
|House number of the recipient's address.	 

|house-extension 
|O 
|O 
|Alphanumeric
|32 
|House extension of the recipient's address.	 

|city 
|O 
|O 
|Alphanumeric
|32 
|City of the recipient's address.

|country 
|O
|O
|Alphanumeric
|3 
|Country code of the recipient's address.

|postal-code 
|O 
|O 
|Alphanumeric
|16 
|Postal/ZIP code of the recipient's address.

5+<.>s|order-items.order-item.
s|Description of a specific order item.

|quantity 
|M
|M
|Numeric 
|n/a  
|Total number of this item in the shopping basket.

|description 
|O 
|O 
|Alphanumeric
|1024 
|Description of the item in the shopping basket.

|article-number 
|O 
|O 
|Alphanumeric
|256 
|EAN or other merchant-side article identifier.

|name 
|M 
|M 
|Alphanumeric
|256 
|Name of the item in the shopping basket.

|amount 
|M 
|M 
|Numeric 
|18,3 
|Item’s price per unit.  +

Use ``,`` (comma) as separator.

|amount@currency 
|M 
|M 
|Alphanumeric
|3 
|<<KlarnaV2_CountriesCurrencies, Currency>> of this item's price. Must match the <<KlarnaV2_Fields_requestedAmount_currency, order currency (requested amount currency)>>. +
Format: 3-character abbreviation according to ISO 4217.

|tax-rate 
|O 
|O 
|Numeric
|5,2 
a|Item’s tax rate per unit in percent. +
*M* if ``tax-amount`` is specified.

|tax-amount 
|O 
|O 
|Numeric
|5,2 
a|Item’s tax value per unit. +
*M* if ``tax-rate`` is specified.

|discount	
|O
|O
|Numeric
|18,3 
|The discount value for one order item.  +
Use ``,`` (comma) as separator.

|type
|O 
|O
|Alphanumeric
|n/a
a|Order item type. +
Possible values: 

  - ``shipment_fee``
  - ``handling_fee``
  - ``discount``
  - ``physical``
  - ``sales_tax``
  - ``digital``
  - ``gift_card``
  - ``store_credit``

//-

If not specified, ``type`` is treated as a regular article.

5+<.>s|statuses.status.
s|Contains information on the status of a specific transaction.

|code
|-
|M
|Alphanumeric
|12
|Transaction status code.

|description
|-
|M
|Alphanumeric
|256
|Transaction status message.

|severity
|-
|M
|Alphanumeric
|20
a|The definition of the status message. Possible values:

- ``information``
- ``warning``
- ``error``

//-

|@provider-code
|-
|O
|Alphanumeric
|34
|Original _{payment-method-name}_ error code.

|@provider-message
|-
|O
|Alphanumeric
|
|Error message to be shown to the consumer as required by _{payment-method-name}_.

|@provider-transaction-id 
|-
|O
|Alphanumeric
|36
|_{payment-method-name}_ reservation number.

5+<.>s|additional-provider-data.provider-data
s|Contains one (max.) additional data item for _{payment-method-name}_.

|request
|O
|-
|Alphanumeric
|
|Content should be an object containing any of the keys and sub objects described in https://developers.klarna.com/api/#payments-api-create-a-new-credit-session serialised to JSON. +
E.g. +
 ``{"marketplace_seller_info":[{"product_category":"Women''s Fashion","product_name":"Women Sweatshirt"}]}`` +

|===

[#KlarnaV2_TransactionTypes_authorization_Samples]
====== _authorization_ Samples

._authorization_ Request
----
include::samples/xml/Klarnav2_authorization_request.xml[]
----

._authorization_ Response
----
include::samples/xml/Klarnav2_authorization_response.xml[]
----

NOTE: To proceed with a successful authorization transaction, take the URL from ``<payment-method url="http://...">`` from the response, replace ``\&amp;`` with ``&`` and redirect your consumer to this URL.

.Notification Request
----
include::samples/xml/Klarnav2_notification_request.xml[]
----