include::shortcuts.adoc[]

[#eNETS]
=== eNETS

_eNETS Direct Debit_ is a type of <<PaymentMethods_PaymentMode_OnlineBankTransfer, Online Bank Transfer>>.

NOTE: This payment method is available for integration with <<PP, {payment-page-v1}>> only.  

[#eNETS_GeneralInformation]
==== General Information

[#eNETS_GeneralInformation_Countries]
.Countries and Currencies

[cols="20h, 80"]
|===
| Countries | Singapore 
| Currencies | SGD
|===

[#eNETS_GeneralInformation_CommunicationFormats]
.Communication Formats

This table illustrates how _eNETS_ notifications are encoded and
which formats can be used for requests and responses.

|===
| *Requests/Responses* | NVP Format 
| *IPN Encodement*     | Please follow the instructions given at
<<GeneralPlatformFeatures_IPN, Instant Payment Notification>> to set up IPN.
|===

[#eNETS_TransactionTypes]
==== Transaction Types

{payment-page-v1} supports the transaction type _debit_ only.

[#eNETS_TestCredentials]
==== Test Credentials

[cols="35h,65"]
|===
| URL (Endpoint)
|``\https://test.{domain}.sg/engine/hpp/``
| Merchant Account ID (MAID)
| dd4ec05b-3d4e-46c3-a32c-d3bb6aa69c82
| Secret Key 
| f8de5ff0-1539-4a24-922e-9cfe9fe675a1
|===

[#eNETS_TestCredentials_Additional]
===== Additional Test Credentials on _eNETS_ Environment 
[cols="35h,65"]
|===
|Bank Selection 
|UAT BankSim (E3 UAT only)
|===

[#eNETS_Workflow]
==== Workflow

[mermaid, CC_Fields_intro_elements_parentchild,svg,subs=attributes+]
----
sequenceDiagram
    participant Consumer
    participant Merchant
    participant {payment-gateway-abbr}
    participant eNETS
Consumer->>Merchant: proceeds to checkout
Merchant->>{payment-gateway-abbr}: sends payment request to {payment-gateway-abbr}
{payment-gateway-abbr}->>Consumer: asks consumer to select a payment method
Consumer->>{payment-gateway-abbr}: selects eNETS
{payment-gateway-abbr}->> Consumer: shows {payment-page-v1-abbr} with available banks for eNETS
Consumer->>{payment-gateway-abbr}: selects bank
{payment-gateway-abbr}->>eNETS: initiates the transaction
eNETS->>Consumer: redirects consumer to bank page
Consumer->>eNETS: logs in on bank page and completes payment on bank page
eNETS->>{payment-gateway-abbr}: sends transaction status to {payment-gateway-abbr}
{payment-gateway-abbr}->>Merchant: sends notification to merchant
Merchant->>Consumer: redirects to status page
----

. Consumer adds items to shopping basket and proceeds to checkout.
. Merchant sends consumer's payment request to {payment-gateway-abbr} for processing.
. Consumer selects payment method _eNETS_.
. {payment-gateway-abbr} sends consumer to _eNETS_ page, providing the participating banks.
. Consumer selects the preferred bank.
. {payment-gateway-abbr} initiates the transaction.
. _eNETS_ sends consumer to desired bank page.
. Consumer logs in and completes payment.
. {payment-gateway-abbr} receives transaction status from _eNETS_.
. {payment-gateway-abbr} sends transaction status to merchant.
. Merchant receives the transaction's status and redirects the consumer to the status page of the payment process.

//-

[#eNETS_Fields]
==== Fields

The fields used for _eNETS_ requests, responses and notifications are the
same as for REST API and Payment Page. Please refer to: <<RestApi_Fields, REST API Fields>> or <<PaymentPageSolutions_Fields, Payment Page>>.

[#eNETS_Samples]
==== Sample

To test _eNETS,_ use the following JavaScript snippet.

NOTE: For details on hash-generation, go to our *{payment-page-v1-abbr} Security* section, see <<PP_Security_RequestSignature, Request Signature>> and <<PP_Security_SecretKeyExchange, Secret Key Exchange>>.


.debit Request (successful)

[source,javascript,subs=attributes+]
----
 var requestedData = {
    "request_time_stamp" : getTimeStamp(), //get current timestamp
    "request_id" : generateUid(), //generate unique ID
    "merchant_account_id" : "dd4ec05b-3d4e-46c3-a32c-d3bb6aa69c82",
    "transaction_type" : "debit",
    "requested_amount" : "1000",
    "requested_amount_currency" : "SGD",
    "success_redirect_url" : "https://{pp-redirect-url-success}",
    "cancel_redirect_url" : "https://{pp-redirect-url-cancel}",
    "fail_redirect_url" : "https://{pp-redirect-url-error}",
    "ip_address" : "127.0.0.1",
    "secret_key" : "f8de5ff0-1539-4a24-922e-9cfe9fe675a1",
    "psp_name" : "demo",
    "first_name" : "test_user",
    "last_name" : "test_user",
    "attempt_three_d" : "false",
    "request_signature" : "", //generate request signature 
    "payment_method" : "enets",
    "order_number" : "123445"
}
{payment-page-function}.hostedPay(requestData);
----

//-
