[#Imprint]
== Imprint

This document has been created by Wirecard AG. Its contents may be changed without prior notice. External web links are provided for information only. Wirecard does not claim liability for access to and correctness of the referenced content.

[#Imprint_Trademarks]
[discrete]
=== Trademarks

The Wirecard logo is a registered trademark of Wirecard AG. Other trademarks and service marks in this document are the sole property of the Wirecard AG or their respective owners.

[#Imprint_Heading]
[discrete]
=== Wirecard AG

Einsteinring 35 +
85609 Aschheim +
Germany

*Phone:* link:tel:+498944241400[+49 89 4424-1400]  +
*Fax:* link:tel:+498944241500[+49 89 4424-1500] +
*Email:* contact@wirecard.com +
*Website:* https://www.wirecard.com +

*Contact the documentation team:* docs@wirecard.com


*Notification of voting rights to:* +
*Fax:* link:tel:+498944241700[+49 89 4424-1700]

*CEO:* Dr. Markus Braun +
*Managing Board:* Alexander von Knoop, Jan Marsalek, Susanne Steidl +
*Chairman:* Wulf Matthias +

*Register Number:* HRB 169227 +
*Register Court:* Munich +
*VAT ID:* DE 201591202

[#Imprint_Copyright]
[discrete]
=== Copyright

The information contained in this document is intended only for the person or entity to which it is addressed and contains confidential and/or privileged material. Any review, retransmission, dissemination or other use of, or taking of any action in reliance upon, this information by persons or entities other than the intended recipient is prohibited. If you received this in error, please contact Wirecard AG and delete the material from any computer.

Copyright © 2019 Wirecard AG All rights reserved.
 
[#builddate]
.Last Updated: {systemtimestamp}

//-
