source 'https://rubygems.org'
gem 'asciidoctor', '~> 1.5.8'
gem 'asciidoctor-diagram', :github => 'asciidoctor/asciidoctor-diagram', :glob => '*.gemspec' # fix until released '~> 1.5.14'
gem 'asciidoctor-pdf', '~> 1.5.0.beta.5'
gem 'rouge'
gem 'concurrent-ruby'