[#CreditCard_PSD2_SCA_Exemptions]
== Exemptions to Strong Customer Authentication

Certain types of transactions may be exempted from Strong Customer
Authentication. It is up to your bank/acquirer to request these
exemptions for you.

[cols="30,70"]
|===
| [[CreditCard_PSD2_SCA_Exemptions_LowValue]] *Low Value Transactions*
a| - SCA does NOT apply to transactions below 30 EUR. +
  - SCA does NOT apply when the cumulative amount of previous transactions since the last Strong Customer Authentication does not exceed 100 EUR. +
  - SCA does NOT apply when five or less consecutive individual online transactions have been made (remember that in this case, none of those two-to-five payments have been over 30 EUR, and their total does not exceed 100 EUR). +
//  - The fraud rates for low value transactions must be the same as, or below the <<CreditCard_PSD2_Fraud, EU reference fraud rate>> for remote electronic card-based payments.

//-

| [[CreditCard_PSD2_SCA_Exemptions_Recurring]] *Recurring Transactions*
a| - SCA needs to apply when the consumer initiates the first in a series of recurring transactions with the same amount and the same merchant. +
  - SCA does NOT apply to all subsequent recurring transactions. +
//  - The fraud rates for recurring transactions must be the same as, or below the <<CreditCard_PSD2_Fraud, EU reference fraud rate>> for remote electronic card-based payments.

//- 

| [[CreditCard_PSD2_SCA_Exemptions_LowRisk]] *Low-Risk Transactions*
a| - SCA does NOT apply to low-risk transactions. +
  - To determine whether an online transaction is low-risk, acquirers and issuers may perform real-time risk analysis, to identify, for example, abnormal spending patterns, known fraud scenarios, and abnormal location of the consumer. +
//  - Low risk transactions can only be exempted if the fraud rates for these transactions are the same as, or below the <<CreditCard_PSD2_Fraud, EU reference fraud rate>> for remote electronic card-based payments.

//-

| [[CreditCard_PSD2_SCA_Exemptions_WhiteList]] *White-Listing*
a| - SCA does NOT apply to online payments from a consumer to a white-listed merchant. +
  - Consumers can white-list 'trusted beneficiaries' - merchants of their choice to be included on a list maintained by the consumer's bank. SCA is only required for the first online transaction. +
//  - White-listed transactions can only be exempted if the fraud rates for these transactions are the same as, or below the <<CreditCard_PSD2_Fraud, EU reference fraud rate>> for remote electronic card-based payments.

//-

| [[CreditCard_PSD2_SCA_Exemptions_Corporate]] *Secure Corporate Transactions*
a| - SCA does NOT apply to secure B2B payments via dedicated payment processes and protocols which are not available to consumers. +
// - Secure corporate transactions can only be exempted if the fraud rates for these transactions are the same as, or below the <<CreditCard_PSD2_Fraud, EU reference fraud rate>> for remote electronic card-based payments.

//-

|===


[WARNING]
====
These types of transactions can only be exempted from Strong Customer Authentication if the fraud rates for these transactions are the same as, or below the EU reference fraud rate for remote electronic card-based payments.
====

[#CreditCard_PSD2_Fraud]
.EU reference fraud rate for remote electronic card-based payments
[%autowidth]
|===
|Exemption Threshold Value (ETV) |Fraud Rate

| EUR 500 | 0.01 %
| EUR 250 | 0.06 %
| EUR 100 | 0.13 %
|===


// [NOTE]
// ====
// For a comprehensive list of cases exempted from or not within the scope of SCA, see https://www.wirecard.com/3d-secure-2/strong-customer-authentication/[Exemptions from using SCA processes].
// ====

//-
