[#CreditCard_3DS2]
== 3D Secure 2

The https://www.emvco.com/about/overview/[EMVCo] have devised a new
standard authentication method for payment card transactions: *3D Secure 2 (3DS2).*

This new protocol fulfills the Strong Customer
Authentication (SCA) requirements set by the <<CreditCard_PSD2, EU's Second Payment Service Directive>> for online payments within the
European Economic Area (EEA).

*3D Secure 2 is now available* and set to become the prime
authentication method for online card payments, thanks to a number of
updates that improve not only the security, but also the consumer
experience of 3D Secure 1 (3DS).

include::{root}/index/payment-processing/3-d-secure-2/11-01-06-psd-2.adoc[leveloffset=+1]

[#CreditCard_3DS2_Why]
[discrete]
=== Why Adopt 3D Secure 2?

When 3D Secure 1 was first introduced in 2001, it provided a
state-of-the-art fraud prevention system. But the face of e-commerce has
changed drastically in the past years. Mobile and in-app payment is
booming, a seamless shopping experience more important than ever, and
the demands on security growing. The 3D Secure 2 protocol has been
designed for this brave new world and offers the flexibility needed to
adapt to an ever-changing e-commerce landscape.

[#CreditCard_3DS2_Advantages]
[discrete]
=== 3D Secure 2 - The Advantages

- *No more static passwords:* The days of rummaging through your drawers
to find your 3DS password are over. Consumers will no longer have to
look for their passwords and are more likely to complete their
purchases.
- *Two-factor authentication:* 3DS2 implements two-factor authentication.
//<<CreditCard_PSD2, two-factor-authentication>>, as required by PSD2.
To make the experience more convenient for
consumers, authentication can be completed, for example, with a token
and a simple thumbprint.
- *Fewer false declines:* The new protocol provides ten times more
information to the issuers, which helps drastically reduce the number of
false declines. Consumers will retain their trust in 3DS2-secured
transactions.
- *Mobile-enabled security:* Consumers will no longer be redirected to
potentially non-mobile-ready authorization pages.
- *Less cart abandonment:* Overall greater convenience, a faster
checkout process, and a seamless shopping experience will reduce
shopping cart abandonment by 70%.
- *Merchant opt-out:* As a merchant, if you decide for 3DS2, you regain
the freedom to choose which transactions you send through the protocol
and which ones you don't. However, please keep in mind that issuers may
have to decline the transaction because SCA is required on their side.

//-

As with 3DS1, 3D Secure 2 also protects the merchant from liability in
cases of fraud.

[#CreditCard_3DS2_PMs]
=== Supported Card Brands

ifdef::env-wirecard[]
ifndef::env-nova[]
3D Secure 2 has been developed, and is supported, by Mastercard, VISA,
American Express, UPI, Diners Club, Discover, and JCB.
endif::[]
endif::[]
ifdef::env-po,env-nova[]
Currently we support Mastercard and VISA.
endif::[]

- <<CreditCard, Credit Card>>
- <<PPv2_CC, Credit Card with {payment-page-v2-abbr}>>

//ifdef::env-po[]
//- <<API_Masterpass, Masterpass>>
//- <<VISACheckout, Visa Checkout>>
//endif::[]

//-
