[#3DS2_IntegrationGuide]
== General Integration Guide

Processing 3D Secure transactions, both 3D Secure 2 and 3D Secure 1, differs from standard payment processing. 

3D Secure requires to include

- an additional transaction type in the payment flow: _check-enrollment._
- 3D-Secure-specific fields in the initial payment request.

//-

[#3DS2_checkenrollment]
._Check-enrollment_


_Check-enrollment_ is the first step in a 3D Secure transaction. It initiates the payment session and checks if the consumer's card is enrolled in the 3D Secure program. _Check-enrollment_ has two functions:

- Authenticate the consumer's identity.
- Confirm the cosnumer's willignes to pay the amount specified in the payment transaction.

//-

With 3D Secure 2, the amount of data collected with _check-enrollment_ is significantly higher than with 3D Secure 1. This allows a more comprehensive risk analysis. 

A  _check-enrollment_ request needs to contain a ``requested-amount``. As a general rule, the amount provided in consecutive payment requests, e.g. during an _authorization,_ should not exceed the amount provided in the referenced _check-enrollment_ by more than what a consumer could reasonably expect. The margin of what is considered reasonable varies from card scheme to card scheme and ranges from 15-20%.
As a merchant, you are always on the safe side when the originally ``requested-amount`` is not exceeded by 15%.

[NOTE]
====
If you exceed the original ``requested-amount``, the transaction may be declined.
However, not all transactions that exceed the original ``requested-amount`` will fail.
In those cases, chargeback liability protection will not apply to the same extent as for fully authenticated amounts.
==== 

For both, 3D Secure 2 and 3D Secure 1, the payment flow remains identical. 

[#3DS2_3DSecureFields]
.3D-Secure-specific fields

To process 3D Secure transactions, include 3D-Secure-specific fields in the initial payment request. With 3D Secure 2, additional fields are required. The whole of 3D-Secure-specific fields required to process 3D Secure transactions, vary per integration option.

Check out how to implement 3D Secure for different integration options:

- <<3DS2_IntegrationGuide_RESTAPI, REST API>>
- <<PPv2_CC_3DSecure, {payment-page-v2-abbr}>>
- <<PP_3DSecure, {payment-page-v1-abbr}>>

//-

j