[#CreditCard_3DS2_Exemption_Adviser]
== PSD2 SCA Exemptions
//== Exemption Adviser

Certain types of transactions may be exempted from SCA. It is up to your bank/acquirer to request these exemptions for you.

[cols="30,70"]
|===
| [[CreditCard_PSD2_SCA_Exemptions_LowValue]] *Low-Value Transactions*
a| - SCA does NOT apply to transactions below 30 EUR. +
  - SCA does NOT apply when the cumulative amount of previous transactions since the last Strong Customer Authentication does not exceed 100 EUR. +
  - SCA does NOT apply when five or less consecutive individual online transactions have been made. Remember that in this case, none of those two-to-five payments have been over 30 EUR, and their total does not exceed 100 EUR.

//-

| [[CreditCard_PSD2_SCA_Exemptions_Recurring]] *Recurring Transactions*
a| - SCA needs to apply when the consumer initiates the first in a series of recurring transactions with the same amount and the same merchant. +
  - SCA does NOT apply to all subsequent recurring transactions.

//- 

| [[CreditCard_PSD2_SCA_Exemptions_LowRisk]] *Low-Risk Transactions*
a| - SCA does NOT apply to low-risk transactions. +
  - To determine whether an online transaction is low-risk, acquirers and issuers may perform real-time risk analysis, to identify, for example, abnormal spending patterns, known fraud scenarios, and abnormal location of the consumer.

//-

| [[CreditCard_PSD2_SCA_Exemptions_WhiteList]] *White-Listing*
a| - SCA does NOT apply to online payments from a consumer to a white-listed merchant. +
  - Consumers can white-list 'trusted beneficiaries' - merchants of their choice to be included on a list maintained by the consumer's bank. SCA is only required for the first online transaction.

//-

| [[CreditCard_PSD2_SCA_Exemptions_Corporate]] *Secure Corporate Transactions*
a| - SCA does NOT apply to secure B2B payments via dedicated payment processes and protocols which are not available to consumers.

//-

|===


[WARNING]
====
These types of transactions can only be exempted from Strong Customer Authentication if the fraud rates for these transactions are the same as, or below the EU reference fraud rate for remote electronic card-based payments.
====

[#CreditCard_PSD2_Fraud]
.EU reference fraud rate for remote electronic card-based payments
[%autowidth]
|===
|Exemption Threshold Value (ETV) |Fraud Rate

| EUR 500 | 0.01 %
| EUR 250 | 0.06 %
| EUR 100 | 0.13 %
|===


[#CreditCard_PSD2_SCA_Exemptions_OutOfScope]
=== Transactions not within the scope of SCA

- Merchant-initiated transactions (MITs)
- Card payments taken via mail (e.g. email, fax, order form) or phone (MOTO transactions)
- "One-leg out transactions", i.e. transactions where either the issuer or the acquirer is not located within the European Economic Area (EEA)
- Transactions using anonymous prepaid cards

//-

[#3DSecureLiabilityShift]
[discrete]
== Liability Shift

3D Secure protects merchants from fraudulent losses by allowing for liability shift after successful cardholder authentication.

Generally, the liability shift rules for 3D Secure 2 are comparable with those for 3D Secure 1: Whenever a merchant successfully requests authentication from an issuer, the chargeback liability shifts to the issuer.

There are, however, some exceptions applicable within the European Economic Area (EEA):

- If an <<CreditCard_PSD2_SCA_Exemptions, exemption>> is applied by merchants and their acquirer (e.g. the merchant decides to avoid a challenge), the liability generally remains with the merchant.

- If an issuer does not support 3D Secure 2 after SCA requirements have come into effect in September 2019, there are cases where only attempting to apply 3D Secure 2 will lead to a shift in liability.

//-


[#3DSecureLiabilityShiftRules]
.Liability Shift Rules
[cols=",,,"]
|===
| *Merchant*               
| *Applied Exemption*       
| *Issuer*                                
| *Liability*

.5+| 3D Secure implemented 

| No exemption            
| Does not support 3D Secure            
| Issuer

| <<CreditCard_PSD2_SCA_Exemptions_LowValue, Low-value transactions>>  
| Checks if number of transactions < or =5 and accepts exemption    
| Acquirer

| <<CreditCard_PSD2_SCA_Exemptions_LowRisk, Low-risk transactions>>   
| Accepts exemption                     
| Acquirer

| No exemption
| Performs transaction risk analysis / Requests challenge (if preceeding number of low-value transactions =5)
| Issuer

| Merchant-initiated transaction (First)
| Requests challenge
| Issuer
|===


//-