[#CreditCard_3DS2_Exemption_Adviser]
== Exemption Adviser

//[#CreditCard_PSD2_SCA_Exemptions]
//== Exemptions to Strong Customer Authentication

Certain types of transactions may be exempted from SCA. It is up to your bank/acquirer to request these exemptions for you.

[cols="30,70"]
|===
| [[CreditCard_PSD2_SCA_Exemptions_LowValue]] *Low Value Transactions*
a| - SCA does NOT apply to transactions below 30 EUR. +
  - SCA does NOT apply when the cumulative amount of previous transactions since the last Strong Customer Authentication does not exceed 100 EUR. +
  - SCA does NOT apply when five or less consecutive individual online transactions have been made. Remember that in this case, none of those two-to-five payments have been over 30 EUR, and their total does not exceed 100 EUR.

//-

| [[CreditCard_PSD2_SCA_Exemptions_Recurring]] *Recurring Transactions*
a| - SCA needs to apply when the consumer initiates the first in a series of recurring transactions with the same amount and the same merchant. +
  - SCA does NOT apply to all subsequent recurring transactions.

//- 

| [[CreditCard_PSD2_SCA_Exemptions_LowRisk]] *Low-Risk Transactions*
a| - SCA does NOT apply to low-risk transactions. +
  - To determine whether an online transaction is low-risk, acquirers and issuers may perform real-time risk analysis, to identify, for example, abnormal spending patterns, known fraud scenarios, and abnormal location of the consumer.

//-

| [[CreditCard_PSD2_SCA_Exemptions_WhiteList]] *White-Listing*
a| - SCA does NOT apply to online payments from a consumer to a white-listed merchant. +
  - Consumers can white-list 'trusted beneficiaries' - merchants of their choice to be included on a list maintained by the consumer's bank. SCA is only required for the first online transaction.

//-

| [[CreditCard_PSD2_SCA_Exemptions_Corporate]] *Secure Corporate Transactions*
a| - SCA does NOT apply to secure B2B payments via dedicated payment processes and protocols which are not available to consumers.

//-

|===


[WARNING]
====
These types of transactions can only be exempted from Strong Customer Authentication if the fraud rates for these transactions are the same as, or below the EU reference fraud rate for remote electronic card-based payments.
====

[#CreditCard_PSD2_Fraud]
.EU reference fraud rate for remote electronic card-based payments
[%autowidth]
|===
|Exemption Threshold Value (ETV) |Fraud Rate

| EUR 500 | 0.01 %
| EUR 250 | 0.06 %
| EUR 100 | 0.13 %
|===


[#CreditCard_PSD2_SCA_Exemptions_OutOfScope]
=== Transactions not within the scope of SCA

- Merchant-initiated transactions (MITs)
- Card payments taken via mail (e.g. email, fax, order form) or phone (MOTO transactions)
- "One-leg out transactions", i.e. transactions where either the issuer or the acquirer is not located within the European Economic Area (EEA)
- Transactions using anonymous prepaid cards

//-


//-