[#3DS2_IntegrationGuide_REST]
== 3D Secure 2 for REST API
====
_To integrate 3D Secure 2 for REST API,_

. Send a request with check-enrollment.
. Redirect the consumer to the Access Control Server (ACS) URL.
. Send a check-payer-response request for validation of the authentication result (optional).
. Complete the payment transaction.

//-
====

.1. Send a request with check-enrollment
-placeholder include file


.2. Redirect the consumer to the ACS URL
-placeholder-

.3. Send a _check-payer-repsonse_ request for validation of the authentication result (optional)
-placeholder-

.4. Complete the payment transaction 
Proceed with the payment ransaction with the relevant transaction-type (e.g. authorization, purchase, authorization-only).

NOTE: For detailed payment flows of specific use cases, head to our 3D Secure 2 Use Cases section. 

[#3DS2_IntegrationGuide_REST_example]
=== Payment-Processing Example

To show how to integrate 3D Secure 2 with REST API, we provide a postman collection containing ready-made XML samples for each step of a one-time payment transaction. 

The 3D Secure 2 payment-processing example is *designed for the testing environment* and *does not use real information.*

Download the link:resources/3-d-secure-2/3-d-secure-2_postman-collection.zip[3DS2 postman collection for a one-time payment]. 

NOTE: 3D Secure fields can be found in the 3D Secure field table fo REST API. They are also inclued in the REST API payment XSD. For the full postman collection, containing samples for all use cases documented in our 3D Secure 2 Use Cases section, head to our 3D Secure 2 Testing page.

[#3DS2_IntegrationGuide_REST_PostmanCollection]
==== Run the Samples

Use https://www.postman.com/postman[Postman] to run the collection.


.Test Credentials
[%autowidth, cols="h,", stripes="none"]
|===
| URL (Endpoint)           
| ``\{rest-api-test-endpoint}``

| Merchant Account ID (MAID) 
| 33f6d473-3036-4ca5-acb5-8c64dac862d1

| Username                   
| 70000-APILUHN-CARD

| Password                   
| 8mhwavKVb91T

2+h|Test Card
|Card number 
|5413330300201218

|Expiration date 
|01/23

|CVV 
|218
|===

NOTE: The test credentials are already included in the postman collection and are provided reference only. You do not need to enter them manually.

.Webhook
ddd
//-


