:cc-exp-year: 2023
:cc-exp-month: 01

[#3DS2_IntegrationGuide_REST]
== 3D Secure 2 for REST API

[NOTE] 
====
The <<3DS2_Worfklows, 3D Secure 2 workflow>> remains identical to the 3D Secure 1 workflow.
====

[#3DS2_IntegrationGuide_REST_integration]
=== Step-by-Step Integration

|===
a|_How to integrate 3D Secure 2 for REST API:_

. Send a request with check-enrollment.
. Redirect the consumer to the Access Control Server (ACS) URL.
. Check-payer-response (optional).
. Complete the payment transaction.

//-
|===

. *Send a request with check-enrollment* +
include::{root}/include/3-d-secure/3-d-secure-2-authentication-transactions-check-enrollment.adoc[]
+
include::{root}/include/3-d-secure/3-d-secure-2-authentication-transactions-check-enrollment-response.adoc[]
+

. *Redirect the consumer to the ACS URL* +
include::{root}/include/3-d-secure/3-d-secure-2-authentication-transactions-acs-url-redirect.adoc[]
+

. *Check-payer-response (optional)* +
include::{root}/include/3-d-secure/3-d-secure-2-authentication-transactions-check-payer-response.adoc[]
+
. *Complete the payment transaction* +
Proceed with the respective transaction-type (e.g. authorization, purchase, authorization-only).
+
You must reference either the previous-check-enrollment or the check-payer-response, depending on whether the check-payer-response has been executed or not.
+

--
.. Following check-enrollment: Enter the transaction ID from the check-payer-response in the ``parent-transaction-id`` field.

.. Following (optional) check-payer-response: Enter the transaction ID from the check-payer-response in the ``parent-transaction-id`` field.

//-
--
+
If the check-payer-response was not executed, use instead the ``PARes`` received via ``TermURL`` as part of the response to the <<3DS2_IntegrationGuide_REST_AutoSubmission, ACS HTTPS POST request>>.

//-


[NOTE]
====
Make sure to distinguish between the terms authentication and authorization. Authentication confirms the cardholder's identity.
Authorization checks whether the cardholder's account holds sufficient funds and reserves the respective amount for later payment. 
====

For more detailed payment flows of typical use cases, go to our <<CreditCard_3DS2_UseCases, 3D Secure 2 Use Cases section>>. Need more information on the general 3D Secure 2 Workflows?  Check out the <<3DS2_worfklow, 3D Secure 2 Workflows section>>.

[#3DS2_IntegrationGuide_REST_example]
=== Payment-Processing Example

We provide a postman collection containing ready-made JSON samples for each step of a one-time payment transaction.

The 3D Secure 2 payment-processing example is *designed for the testing environment* and *does not use real information.*

[%autowidth, cols="70,30"]
|===
s|Get the 3D Secure 2 postman collection for a one-time payment transaction: a|pass:[<a href="resources/3-d-secure-2/usecase_pm-collection/one-time-payment.postman_collection.json" target="_blank" rel="noreferrer noopener" download>Download</a>]
|===

////
NOTE: Download a 3D Secure 2 postmann collection for all use cases <<3DS2_Testing_Samples, here>>.
////

[#3DS2_IntegrationGuide_REST_example_credentials]
==== Test Credentials

The postman collection is preconfigred with the following test credentials:

[%autowidth, cols="h,", stripes="none"]
|===
| URL (Endpoint)           
| ``\{rest-api-test-endpoint}``

| Merchant Account ID (MAID) 
| 33f6d473-3036-4ca5-acb5-8c64dac862d1

| Username                   
| 70000-APILUHN-CARD

| Password                   
| 8mhwavKVb91T

2+h|Test Card
|Card Number 
|5413330300201218

|Expiration Date 
|{cc-exp-month}/{cc-exp-year}

|CVV 
|218
|===

You can find further test credentials and test card types in our <<3DS2_Testing, 3D Secure 2 Testing section>>.

[#3DS2_IntegrationGuide_REST_example_run]
==== Run the Collection

Import an run the collection with https://www.postman.com/postman[Postman].

To import the collection in Postman,

. Download the collection.

. Open Postman and click *Import* in the header bar.

. Click *Choose Files* and select the respective collection file. 

You can now run the collection.

[NOTE]
====
More details on 3D Secure fields included in the sample requests can be found in the <<3DS2_Fields, 3D Secure 2 field table>>. 
ifdef::env-wirecard[]
ifndef::env-nova[]
They are also included in the <<Appendix_Xml, REST API payment XSD>>.
endif::[]
endif::[]
====


Our samples work with https://webhook.site[Webhook.site] to simulate the ACS URL where the consumer will be redirected to for authentication. This allows you to obtain the PARes.


To manually integrate Webhook.site in a test setup:

. Send a check-enrollment request. +
A check-enrollment response containing the ``PAReq``, the ``TermUrl`` and ``MD`` is returned.

. Open https://webhook.site[Webhook.site].

. Click *Edit* in the header bar. +
A pop-up window opens.

. Copy paste the HTTPS POST request in the field *Response Body*. 
+

[#3DS2_IntegrationGuide_REST_AutoSubmission]
.HTTPS POST Request
[source,html]
----
<html>
   <head>
      <meta HTTP-EQUIV="Content-Type" content="text/html; charset=UTF-8" />
      <meta HTTP-EQUIV="Cache-Control" CONTENT="no cache" />
      <meta HTTP-EQUIV="Pragma" CONTENT="no cache" />
      <meta HTTP-EQUIV="Expires" CONTENT="0" />
   </head>
   <body OnLoad="AutoSubmitForm();">
      <form name="downloadForm" action="AcsUrl" method="POST">
         <input type="hidden" name="PaReq" value="PaReq" />
         <input type="hidden" name="TermUrl" value="TermUrl" />
         <input type="hidden" name="MD" value="optionalValue" />
         <SCRIPT LANGUAGE="Javascript">
            <!--function AutoSubmitForm() { document.downloadForm.submit();}//-->
         </SCRIPT>
         <input type="submit" name="continue" value="Continue" />
      </form>
   </body>
</html>
----
+

[NOTE] 
====
*Default status code* = 200 +
*Content type* = text/html +
*Timeout before response* = 0
====

. In the HTTPS POST request 
.. replace the value ``PaReq`` and the action ``AcsUrl`` with the values  from the check-enrollment response.
.. replace the value ``TermUrl`` with *your randomly generated URL* from the webhook site.

. Click *Save*. +
The pop-up window closes.
. Next to your randomly generated URL, click *Open in a new tab.* +
. In the new tab, click *Continue.*
. Enter the password ``{three-d-s-pw}`` and click *Submit* (if required).
. Return to the previous webhook tab. +
You can find the ``PARes`` in the Form Values section.
. Copy the ``PARes`` and return to Postman.
. Enter the ``PARes`` and the ``transaction-id`` of the check-enrollment response in the check-payer-response request.
. Send the check-payer-response request.
. Complete the payment transaction.

//-





