[#CreditCard_3DS2_Exemption_Adviser]
== PSD 2 SCA Exemptions
//== Exemption Adviser

Certain types of transactions may be exempted from Strong Customer Authentication (SCA) even if they fall within the scope of PSD 2. It is up to your bank/acquirer to request these exemptions for you.

Indicate in the transaction if an exemption is desired and {payment-provider-name} can request for the most applicable SCA exemption.

[WARNING]
// ====
// If the exemption is granted, the <<3DSecureLiabilityShift, liability>> remains with the merchant (acquirer) in cases of chargebacks.
// ====
====
If the exemption is granted, liability protection is not offered, and the <<3DSecureLiabilityShift, liability>> remains with you, the merchant (acquirer), in cases of chargebacks. 
====

The following SCA exemptions can be applied:

[cols=""]
|===
| [[CreditCard_PSD2_SCA_Exemptions_LowValue]] *Low-Value Transactions* 
a| - SCA does NOT apply to transactions below 30 EUR. +
- SCA does NOT apply when the cumulative amount of previous transactions since the last Strong Customer Authentication does not exceed 100 EUR. +
- SCA does NOT apply when five or less consecutive individual online transactions have been made. Remember that in this case, none of those two-to-five payments have been over 30 EUR, and their total does not exceed 100 EUR. 

//-

_The issuer keeps track of the number of transactions or the cumulative transaction amount._

[NOTE]
====
The issuer can apply this exemption even if you and your acquirer did not request for it. In such cases the chargeback liability shifts to the issuer.
====

|===

[cols=""]
|===
| [[CreditCard_PSD2_SCA_Exemptions_Recurring]] *Recurring Transactions*
a| - SCA needs to apply when the consumer initiates the first in a series of recurring transactions with the same amount and the same merchant. +
- SCA does NOT apply to all subsequent recurring transactions.

//-

|===

[cols=""]
|===
| [[CreditCard_PSD2_SCA_Exemptions_LowRisk]] *Low-Risk Transactions*
a| - SCA does NOT apply to low-risk transactions. +
  - To determine whether an online transaction is low-risk, acquirers and issuers may perform real-time risk analysis, to identify, for example, abnormal spending patterns, known fraud scenarios, and abnormal location of the consumer.

//-

_The transaction amount for which a low-risk exemption can be requested varies depending on the acquirer fraud rate._

[NOTE]
====
The issuer can apply this exemption even if you and your acquirer did not request for it. In such cases the chargeback liability shifts to the issuer.
====

|===

[cols=""]
|===
| [[CreditCard_PSD2_SCA_Exemptions_WhiteList]] *White-Listing*
a| - SCA does NOT apply to online payments from a consumer to a white-listed merchant. +
- Consumers can white-list 'trusted beneficiaries' - merchants of their choice to be included on a list maintained by the consumer's bank. SCA is only required for the first online transaction.

//-

|===

[cols=""]
|===
| [[CreditCard_PSD2_SCA_Exemptions_Corporate]] *Secure Corporate Transactions*
a| - SCA does NOT apply to secure B2B payments via dedicated payment processes and protocols which are not available to consumers.

//-

|===


[WARNING]
====
These types of transactions can only be exempted from Strong Customer Authentication if the fraud rates for these transactions are the same as, or below the EU reference fraud rate for remote electronic card-based payments.
====

[#CreditCard_PSD2_Fraud]
.EU reference fraud rate for remote electronic card-based payments
[%autowidth]
|===
|Exemption Threshold Value (ETV) |Fraud Rate

| EUR 500 | 0.01 %
| EUR 250 | 0.06 %
| EUR 100 | 0.13 %
|===


[#CreditCard_PSD2_SCA_Exemptions_OutOfScope]
=== Transactions not within the scope of SCA

- Merchant-initiated transactions (MITs)
- Card payments taken via mail (e.g. email, fax, order form) or phone (MOTO transactions)
- "One-leg out transactions", i.e. transactions where either the issuer or the acquirer is not located within the European Economic Area (EEA)
- Transactions using anonymous prepaid cards

//-


[#CreditCard_PSD2_SCA_Exemptions_Grandfathering] 
=== Grandfathering

Since 14 September 2019, the PSD 2 Regulatory Technical Standard requires SCA for 3D Secure 2 payment processes. This also applies to recurring payments (https://ec.europa.eu/transparency/regdoc/rep/3/2017/EN/C-2017-7782-F1-EN-MAIN-PART-1.PDF[see Article 14 RTS]). From that day on, each first transaction of a recurring Merchant Initiated Transaction (MIT) must meet the standards of PSD 2. +

A special status applies to ongoing recurring MITs whose first transaction was processed before 14 September 2019. Recurring MITs of that kind are "grandfathered". +

If your acquirer is {payment-provider-name}, the {payment-gateway-abbr} can "grandfather" a recurring MIT if you provide the referencing ``transaction-id`` from the *first transaction* ``authorization`` or ``purchase``. 
// (``sequence-type`` = ``first`` and ``periodic-type`` = ``recurring``|``installment``|``UCOF``) of this payment process. This ``transaction-id`` must be used as the ``parent-transaction-id`` in the subsequent payments after 14 September 2019. +

.Conditions to grandfather a recurring MIT
[cols="h,,,,,,"]
|===

|                        | Transaction Date           | ``transaction-type`` | ``transaction-id`` | ``sequence-type``| ``periodic-type``| ``parent-transaction-id``
| First Transaction      | *Before* 14 September 2019 | ``authorization`` or +
                                                      ``purchase``           | e.g. ``12345``     | ``first``        | ``recurring`` or +
                                                                                                                       ``installment`` or +
                                                                                                                       ``UCOF`` +       | none
| Recurring Transactions | *After* 14 September 2019  | ``capture-authorization`` or +
                                                        ``purchase``         | e.g. ``56789``     | ``recurring`` or +
                                                                                                    ``final``       | ``recurring``or +
                                                                                                                      ``installment`` or +
                                                                                                                      ``UCOF`` +       | e.g. ``12345``

|===

{payment-provider-name} will then identify the correct Trace ID (MasterCard) or Transaction Identifier (Visa) of this recurring MIT and send it to the issuer.


[#3DSecureLiabilityShift]
[discrete]
== Liability Shift

3D Secure protects merchants from fraudulent losses by allowing for liability shift after successful cardholder authentication.

Generally, the liability shift rules for 3D Secure 2 are comparable with those for 3D Secure 1: Whenever a merchant successfully requests authentication from an issuer, the chargeback liability shifts to the issuer.

There are, however, some exceptions applicable within the European Economic Area (EEA):

- If an exemption is granted after it was requested by you and your acquirer (e.g. you decide to avoid a challenge), liability protection is not offered, and the liability generally remains with you, the merchant (acquirer). 

- If an issuer does not support 3D Secure 2 after SCA requirements have come into effect, there are cases where only attempting to apply 3D Secure 2 will lead to a shift in liability. Nonetheless, the issuers may decline the authorization in case they refuse to take the liability.

//-


[#3DSecureLiabilityShiftRules]
.Liability Shift Rules Overview
[cols=",,,"]
|===
| *Merchant*               
| *Applied Exemption*       
| *Issuer*                                
| *Liability*

.7+| 3D Secure implemented 

| No exemption            
| Does not support 3D Secure            
| Issuer

| <<CreditCard_PSD2_SCA_Exemptions_LowValue, Low-value transactions>>  
| Checks if number of transactions < or =5 and accepts exemption    
| Acquirer

| No exemption
| Applies <<CreditCard_PSD2_SCA_Exemptions_LowValue, low-value transactions>> exemption
| Issuer

| <<CreditCard_PSD2_SCA_Exemptions_LowRisk, Low-risk transactions>>   
| Accepts exemption                     
| Acquirer

| No exemption
| Applies <<CreditCard_PSD2_SCA_Exemptions_LowRisk, low-risk transactions>> exemption
| Issuer

| No exemption
| Performs transaction risk analysis / Requests challenge (if preceeding number of low-value transactions =5)
| Issuer

| Merchant-initiated transaction (First)
| Requests challenge
| Issuer
|===


//-