[#3DS2_IntegrationGuide]
== General Integration Guide

Processing 3D Secure transactions, both 3D Secure 2 and 3D Secure 1, differs from standard payment processing.

3D Secure requires to include

- an additional transaction type in the payment flow: _check-enrollment._
- additional 3D-Secure-specific fields in the initial payment request.

//-

[#3DS2_checkenrollment]
._Check-enrollment_

_Check-enrollment_ is the first step in a 3D Secure transaction. Its purpose is to authenticate the consumer's identity and confirm the consumer's willingness to pay the amount specified in the payment transaction. With 3D Secure 2, the amount of data collected with _check-enrollment_ is significantly higher than with 3D Secure 1. This allows a more comprehensive risk analysis. 

For both, 3D Secure 2 and 3D Secure 1, the general payment flow remains identical. 

[#3DS2_3DSecureFields]
.3D-Secure-specific fields

To process 3D Secure transactions, include additional 3D-Secure-specific fields in the initial payment request. 3D-Secure-specific fields required, vary per version as well as integration option. 


Check out how to implement 3D Secure for different integration options:

- <<3DS2_IntegrationGuide_RESTAPI, REST API>>
- <<PPv2_CC_3DSecure, {payment-page-v2-abbr}>>
- <<PP_3DSecure, {payment-page-v1-abbr}>>

//-
