[#Home]
== Home

[#Home_{payment-provider-name}PaymentGateway]
[discrete]
=== {payment-provider-name} Online Documentation

[NOTE]
====
<<GeneralPlatformFeatures_ReferencingTransaction, *Referenced Transactions*>> +
Referenced transactions (e.g. refund, <<GeneralPlatformFeatures_Transactions_Recurring, recurring>>) have a limited transaction lifecycle in _{payment-gateway-abbr}._ Starting on 1 February 2020 only transactions processed within the last two years can be referenced.
====

[.startpage-block]
--
[.signpost]
[cols=","]
|===
.3+a|
<<GeneralIntegrationOptions, *Choose your Integration Journey*>>

[.icon-large]
image::images/icons/signpost.svg[streetsign_icon]

|You want full payment processing functionality without the hazzle of backend-integration? 

<<PPv2, Go with {payment-page-v2}>>

|Using a shop system?

<<ShopSystems, Get our {payment-provider-name} Shop Extensions>>

|You want full integration control - backend and frontend?

<<RestApi, Direct Integration of our REST API>>
|===

[.demoshop]
[cols=",,"]
|===
a|
[.icon]
image::images/icons/demoshop.svg[demoshop]

2.+a|
https://demoshop-test.wirecard.com/demoshop/#/cart?merchant_account_id=ab62ea6e-ba97-48ef-b3bc-bf0319e09d78[Try our Demoshop for {payment-page-abbr} Integrations]
|===

[.guides]
[cols=",,"]
|===
a|
[.icon]
image::images/icons/compass.svg[compass]

2.+a|<<IntegrationGuides, *Integration Guides*>>

* <<IntegrationGuides_WPP_v2, {payment-page-v2}>>
* <<MobilePaymentSDK_IntegrationGuides, Mobile Payment SDK>>

//-
|===

[.fragezeichen]
[cols=","]
|===
a|
[.icon]
image::images/icons/payments.svg[altpayment_icon] 
<<PaymentMethods, *Payment Methods*>>

* <<CC_Main, Card Payments>>
* <<PaymentMethods, Alternative Payment Methods>>

a|
[.icon]
image::images/icons/gear.svg[gear_icon]
<<PaymentProcessing, *Payment Processing*>>

* <<CreditCard_3DS2, 3D Secure 2>>
* <<GeneralPlatformFeatures, Features of our REST API>>

//-
|===

[.center]
[cols=",,"]

|===
a|
[.icon]
image::images/icons/contactus.svg[callcenter_icon]

2.+|<<ContactUs, *Contact Us*>>
|===
--
