[#Home]
== Home

[#Home_{payment-provider-name}PaymentGateway]
[discrete]
=== {payment-provider-name} Online Documentation

[NOTE]
====
<<GeneralPlatformFeatures_ReferencingTransaction, *Referenced Transactions*>> +
Referenced transactions (e.g. refund, <<GeneralPlatformFeatures_Transactions_Recurring, recurring>>) have a limited transaction lifecycle in _{payment-gateway-abbr}._ Starting on 1 February 2020 only transactions processed within the last two years can be referenced.
====


[.startpage-block]
--
[.signpost]
[cols=","]
|===
.3+a|
<<GeneralIntegrationOptions, *Choose your Integration Journey*>>

[.icon-large]
image::images/icons/signpost.svg[streetsign_icon]

Choose from our three most popular integration options and get started right away.

Looking for <<GeneralIntegrationOptions, more>>?

|You want full payment-processing functionality without the need for backend-integration? 

<<PPv2, Go with {payment-page-v2}>>

https://demoshop-test.wirecard.com/demoshop/#/cart?merchant_account_id=ab62ea6e-ba97-48ef-b3bc-bf0319e09d78[Give it a try in our Demoshop]


|Using a shop system?

<<ShopSystems, Get our {payment-provider-name} Shop Extensions>>

|You want full control - backend and frontend? 

<<RestApi, Integrate our REST API>>
|===

[.demoshop]
[cols=",,"]
|===
a|
[.icon]
image::images/icons/demoshop.svg[demoshop]

2.+a|
https://demoshop-test.wirecard.com/demoshop/#/cart?merchant_account_id=ab62ea6e-ba97-48ef-b3bc-bf0319e09d78[Try our Demoshop for {payment-page-abbr} Integrations]
|===

[.guides]
|===
a|
[.icon]
image::images/icons/compass.svg[compass]
<<IntegrationGuides, *Stay on Track with our Integration Guides*>>

Follow our step-by-step <<IntegrationGuides_WPP_v2, {payment-page-v2} Integration Guides>> for our {payment-page-v2-abbr} <<PaymentPageSolutions_PPv2_HPP_Integration, Hosted Payment Page>>, <<PaymentPageSolutions_PPv2_EPP_Integration, Embedded Payment Page>>, and <<PPv2_Seamless_Integration, Seamless Integration>>.
|===

[.fragezeichen]
[cols=","]
|===
a|
[.icon]
image::images/icons/payments.svg[altpayment_icon] 
<<PaymentMethods, *Offer the Payment Methods you Want*>>

Equip your shop with the payment methods that are right for you and your consumers.

* <<CC_Main, Card Payments>>
* <<PaymentMethods, Alternative Payment Methods>>

//-

a|
[.icon]
image::images/icons/gear.svg[gear_icon]
<<PaymentProcessing, *Personalize the Way you Process Payments*>>

If you are an EU merchant and want to process card payments, check out 
<<CreditCard_3DS2, 3D Secure 2>>.

Looking for installment payment? Need information about cross-referencing and referencing transactions? Head to <<GeneralPlatformFeatures, Features for REST API>> for all your payment-processing needs.
|===

[cols=",,"]
|===
a|
[.icon]
image::images/icons/contactus.svg[callcenter_icon]

2.+| Any questions? Need help? Just want to get in touch?
<<ContactUs, *Contact Us*>>
|===
--
