The Address Verification System (AVS) verifies credit card data. It compares the billing address sent in the transaction with the issuer's billing information of the cardholder. +
{payment-provider-name} Fraud Prevention Suite (FPS), then, offers the possibility to react to specific AVS return codes.

[#AVS_and_FPS_AVS]
==  AVS and FPS 

If you want to use AVS your {payment-provider-name} provider account must be configured ``connector.avs.data.store=true``. +
For details contact our <<ContactUs, Merchant Support>>.

NOTE: AVS applies to cardholder addresses from the U.S., the U.K., and Canada.

The consumer must provide the <<CC_Fields_xmlelements_request_address, full billing address>>. Otherwise AVS cannot be performed.

While a complete address is provided for an address verification, only the numeric portion of the address is verified by the issuer. Typically, only the house number and ZIP/postal code are compared.

====
Let's assume the consumer sends this billing address: 

121 W Houston St +
New York City +
NY +
10012 +
U.S. 

//-

AVS compares 121 and 10012 from the transaction with the issuer's billing information of the cardholder.
====

[#AVS_and_FPS_FPS]
===  AVS and FPS Interaction

With a post-authorization check FPS either accepts the transaction or rejects it in case AVS does not match. 

In case of rejection FPS initiates a ``void-authorization``.

// (+++Add Flow: Cardholder-> Merchant-> Wirecard Payment Gateway-> Wirecard Risk Engine with Fraud Prevention Suite pre-auth check-> Wirecard Gateway authorization request-> Issuer authorization and AVS response > Wirecard Gateway → Wirecard Risk Engine with Fraud Prevention Suite postauth check → -- Wirecard Gateway-> Merchant→ Cardholder +++)
// Flow shall be integrated via TikZ

If you are based in the United States, we recommend to use the default FPS setting. This setting declines a transaction, if the AVS response does not contain an exact match.

Contact our <<ContactUs, Merchant Support>>, if you want to customize your AVS setting with different logics. 

[#AVS_and_FPS_IssuerCargeback]
=== Card Scheme's Chargeback Rules

Visa and Mastercard have specific AVS rules and guidelines for chargeback processing in the United States.

.Mastercard grants liability shift, if

* the ``authorization`` response message includes a positive AVS response of X or Y.
* the address to which the merchandise was sent was the same as the AVS-confirmed address.

.Visa grants liability shift, if

* AVS sends you a positive “Y” response in the ``authorization`` message if billing and shipping addresses are the same. You will need to submit proof of the shipping address and signed proof of delivery.
* you submit an AVS query during authorization and receive a “U” response from a card issuer. This response means the card issuer is unavailable or does not support AVS.

Look at the complete list of the <<FraudPrevention_AVS_ProviderResponseCode, Provider Response Codes>> and their {payment-provider-name} mapped values.

//-
