[#avs_and_fps]
== AVS and Fraud Prevention Suite

[#avs_and_fps_avs]
=== Address Verification System (AVS)

AVS verifies credit card data. It compares the billing address sent in the transaction with the issuer's billing information of the cardholder. 

NOTE: AVS applies to cardholder addresses from the U.S., the U.K., and Canada.

The consumer must provide the full billing address. Otherwise AVS cannot be performed.

[%autowidth]
[cols="m,,,,a"]
|===
| Field | <<APIRef_FieldDefs_Cardinality, M/O>> | Datatype | Size | Description

include::{root}/include/fields/rest_cc/request/req-address.adoc[]

|===

//-

By default, AVS only compares the house number and ZIP/postal code. 

====
Let's assume the consumer sends this billing address: 

121 W Houston St +
New York City +
NY +
10012 +
U.S. 

//-

AVS compares 121 and 10012 from the transaction with the issuer's billing information of the cardholder.
====

[#avs_and_fps_fps]
=== AVS and {payment-provider-name} Fraud Prevention Suite (FPS)

FPS reacts to the specific AVS return codes. A post-authorization check either accepts the transaction or rejects it in case AVS does not match. 

In case of rejection FPS initiates a ``void-authorization``.

(+++Add Flow: Cardholder-> Merchant-> Wirecard Payment Gateway-> Wirecard Risk Engine with Fraud Prevention Suite pre-auth check-> Wirecard Gateway authorization request-> Issuer authorization and AVS response > Wirecard Gateway → Wirecard Risk Engine with Fraud Prevention Suite postauth check → -- Wirecard Gateway-> Merchant→ Cardholder +++)

If you are based in the United States, we recommend to use the default FPS setting. This setting declines a transaction, if the AVS response does not contain an exact match.

Contact our <<ContactUs, Merchant Support>>, if you want to customize your AVS settings. 

[#avs_and_fps_IssuerCargeback]
=== Issuer's Chargeback Rules

Visa and Mastercard have specific AVS rules and guidelines for chargeback processing in the United States.

.Mastercard grants liability shift, if

* the ``authorization`` response message includes a positive AVS response of X or Y.
* the shipping address and the AVS-confirmed address are identical. 

.Visa grants liability shift, if

* AVS sends you a positive “Y” response in the ``authorization`` message and billing and shipping addresses are the same. You must submit proof of the shipping address and signed proof of delivery.
* you submit an AVS query during authorization and receive a “U” response from a card issuer. This response means the card issuer is unavailable or does not support AVS.

Look at the <<FraudPrevention_AVS_ProviderResponseCode, complete list>> of the Provider Response Codes and their {payment-provider-name} mapped values.

// link must be checked after merge of PSPDOC-1562!

//-