[#Feature_PurchaseReturnAuthorization]
== Update of Refund Transactions for Mastercard and Visa

====
.Advantages
* Faster, easier refund processing.
* No changes in the refund-request (<<CreditCard_TransactionTypes_CaptureAuthorization_SendingData_RefundCapture, refund-capture>>, <<CreditCard_TransactionTypes_Purchase_SendingData_RefundPurchase, refund-purchase>>).
* Enhanced consumer experience: Successful refunds show up immediately in your consumers' bank statements.
====

We are updating refund transactions for credit card (Mastercard and Visa). 

With the update, the response to a refund-request returns the ``authorization-code`` as follows:


* If your refund-request is successful, the ``authorization-code`` contains a 6-digit value.
* If the issuer declines the refund-request, the ``authorization-code`` does not contain a value. Please refer to <<StatusCodes_InDetail, ``statuses.status.code``>> for more details.

//-

[IMPORTANT]
====
In Wirecard Gateways, we are enabling the feature on 

- **04 May 2020 for eCommerce.**
- **25 May 2020 for POS and MOTO.** 

//-

The ``authorization-code`` does not contain a value prior to that date. +

Mastercard and Visa intended to release this feature on 17 July 2020 for all merchants except airlines. +
Due to the current COVID-19 situation, the effective date for merchants for this mandate had to be postponed to **17 July 2020**.


====
//-