Send an HTTPS POST request including the ACS URL, the ``PAReq``, ``TermUrl`` and ``MD``.
+
[cols="15,85"]
|===
| ``three-d/pareq`` | Base64-encoded request message created for cards enrolled in the 3D Secure program. + 
The ``PAReq`` is returned by the issuer's ACS via the VISA or Mastercard directory to the {payment-gateway} and from there passed on to the merchant.
| ``TermUrl`` | Web address of your server to receive the ``PARes``, i.e. the Payment Authentication response.
| ``MD`` | Field reserved for specific merchant data. +
It may be useful for retrieving transaction data from the database or recalling a transaction.
|===
+
WARNING: The ``MD`` field is _mandatory._ Make sure to include it in the request. You do not need to enter a value. +
If you omit this field, however, an authentication error occurs and the payment process is aborted.
+
.Example: HTTPS POST Request
[source,html]
----
 <html>
    <head>
       <meta HTTP-EQUIV="Content-Type" content="text/html; charset=UTF-8" />
       <meta HTTP-EQUIV="Cache-Control" CONTENT="no cache" />
       <meta HTTP-EQUIV="Pragma" CONTENT="no cache" />
       <meta HTTP-EQUIV="Expires" CONTENT="0" />
    </head>
    <body OnLoad="AutoSubmitForm();">
       <form name="downloadForm" action="AcsUrl" method="POST">
          <input type="hidden" name="PaReq" value="PaReq" />
          <input type="hidden" name="TermUrl" value="TermUrl" />
          <input type="hidden" name="MD" value="optionalValue" />
          <SCRIPT LANGUAGE="Javascript">
             <!--function AutoSubmitForm() { document.downloadForm.submit();}//-->
          </SCRIPT>
          <input type="submit" name="continue" value="Continue" />
       </form>
    </body>
 </html>
----
+
Once the consumer has been redirected, they receive an authentication prompt. The consumer enters their data.
+
After successful authentication, the SSL-encrypted and digitally signed ``PARes`` is posted to the ``TermURL`` via the consumer's browser.
