[#API_CC_3DS2_UC_Overview]
=== 3D Secure 2 Use Cases

[cols="v,,"]
|===
| Use Case (incl. Link)  | Options | Example

2+a| <<, One Time Payment>> | Consumer fills his shopping cart, checks out and pays with his credit card. +
This payment process happens once and is fully independent of any other payment processes.
.2+a|Delayed Shipment | <<API_CC_3DS2_UC_delayed-shipment_expect, Expected Delay>> a| NOTE: This use case can be used only if the expected delay does not exceed 90 days. 

Some product in the merchant's online shop may have become more popular than the merchant expected and he runs out of stock way too fast. He needs a reorder for new supply much earlier than expected. +
The merchant knows that he is out of stock but keeps the product on display. +
He informs the consumer that he can order but has to wait an extra period of time. 
| <<API_CC_3DS2_UC_delayed-shipment_unexpect, Unexpected Delay>> | The product is on stock but some unforeseeable side effects (e.g. strike in the delivery chain) cause a delay of delivery.
.4+a| Partial/Split Shipment | <<, Without Delay>>| 
| <<, With Delay>> |
| <<, Multiple Authorizations>> |
| <<, Multiple Authorizations (No Goods Ready)>> |
.2+a| Recurring Payments (Same Amount) | <<, Due at Signup>>| 
| <<, Not Due at Signup>> |
2+a| <<, General Multi-Party Commerce>> | 
2+a| <<, Payment Facilitators>> | 
.3+a| Open Orders | <<, Initial Order Amount>>| 
| <<, Estimated Max Amount>> |
| <<, Amount +15% from AuthE>> |
2+a| <<, Adding a Card on File>> | 
.2+a| Account Funding Transaction | <<, Account to Account>>| 
| <<, Peer2Peer>> |
2+a| <<, Third-Party MPI>> | 
|===

//-