[#API_CC_3DS2_UC_Overview]
=== 3D Secure 2 Use Cases

[cols=".^v,.^,.^"]
|===
| Use Case  | Options (incl. Link) | Example

2+a| <<, One Time Payment>> | Consumer fills his shopping cart, checks out and pays with his credit card. +
This payment process happens once and is fully independent of any other payment processes.
.2+a|Delayed Shipment | <<API_CC_3DS2_UC_delayed-shipment_expect, Expected Delay>> a| NOTE: Use this use case only if the expected delay does not exceed 90 days. 

Some product in your online shop may have become more popular than you expected and you run out of stock way too fast. You need to reorder new supply much earlier than expected. +
You know that you are out of stock but keep the product on display. +
You inform the consumer that he can order but has to wait an extra period of time. 
| <<API_CC_3DS2_UC_delayed-shipment_unexpect, Unexpected Delay>> | The product is on stock but some unforeseeable side effects (e.g. strike in the delivery chain) cause a delay of delivery.
.4+a| Partial/Split Shipment | <<, Without Delay>>| 
| <<, With Delay>> |
| <<, Multiple Authorizations>> |
| <<, Multiple Authorizations (No Goods Ready)>> |
.2+a| Recurring Payments (Same Amount) | <<, Due at Signup>>| 
| <<, Not Due at Signup>> |
2+a| <<, General Multi-Party Commerce>> | 
2+a| <<, Payment Facilitators>> | 
.3+a| Open Orders | <<, Initial Order Amount>>| 
| <<, Estimated Max Amount>> |
| <<, Amount +15% from AuthE>> |
2+a| <<, Adding a Card on File>> | 
.2+a| Account Funding Transaction | <<, Account to Account>>| 
| <<, Peer2Peer>> |
2+a| <<, Third-Party MPI>> | 
|===

//-