[#PaymentPageDesigner_UsingThemes]
== Using Themes

You can select any theme you have saved in Payment Page Designer as the default one. Each time the payment page loads, it will show that particular theme.
If you want to use a different theme for a payment (other than your default), you need to specify this in the request.

[%autowidth]
|===
| Field (NVP) | Field (JSON) | Data Type | JSON Parent | Description

| wpp_options_theme | theme | String | options ({ }) | The name of the Designer theme used for the payment.
|===

[NOTE]
====
The value of `theme` is the name under which you saved the theme you want to use in Payment Page Designer.

You can access default theme settings in Payment Page Designer. If you do not send this field in the request, the default theme is used.
====

If you customize & save a theme in PPD under the name `test-theme` and
then use it for a payment, the request looks like this:

.An Example Request w/ Theme

[source,json,subs=attributes+]
----
include::{BASEDIR}/samples/json/PaymentPageDesignerUsingThemes_AnExampleRequestWTheme.json[]
----
