[.sample-tabs]

=== payolution Invoice: Authorization
[.tab-content.tab-nvp]
==== NVP

[.r-details]
.Request Details
[cols="1v,2"]
|===
2+| API Endpoint

e| Method | POST
e| URI    | ``\https://api-test.wirecard.com/engine/rest/paymentmethods/``

2+h| Headers
e| Content-Type | `application/x-www-form-urlencoded;charset=UTF-8`
e| Accept       | `text/plain`
|===

//.Request payolution Invoice: Authorization (NVP)
[source,nvp]
----
include::nvp/Payolution_Invoice_Authorization_request.nvp[]
----

[.r-details]
.Response Details
[cols="1v,2"]
|===
2+h| Headers

e| Content-Type | `application/x-www-form-urlencoded;charset=UTF-8`
2+h| Status
e| Code        | ``201.0000``
e| Severity    | ``information``
e| Description | ``The resource was successfully created.``

|===

//.Response payolution Invoice: Authorization (NVP)
[source,nvp]
----
include::nvp/Payolution_Invoice_Authorization_response.nvp[]
----

[.tab-content.tab-xml]
==== XML

[.r-details]
.Request Details
[cols="1v,2"]
|===
2+| API Endpoint

e| Method | POST
e| URI    | ``\https://api-test.wirecard.com/engine/rest/paymentmethods/``

2+h| Headers
e| Content-Type | `application/xml`
e| Accept       | `application/xml`
|===

//.Request payolution Invoice: Authorization (XML)
[source,xml]
----
include::xml/Payolution_Invoice_Authorization_request.xml[]
----

[.r-details]
.Response Details
[cols="1v,2"]
|===
2+h| Headers

e| Content-Type | `application/xml`
2+h| Status
e| Code        | ``201.0000``
e| Severity    | ``information``
e| Description | ``The resource was successfully created.``

|===

//.Response payolution Invoice: Authorization (XML)
[source,xml]
----
include::xml/Payolution_Invoice_Authorization_response.xml[]
----

