[.sample-tabs]

=== Przelewy24: Debit
[.tab-content.tab-json]
==== JSON

[.r-details]
.Request Details
[cols="1v,2"]
|===
2+| API Endpoint

e| Method | POST
e| URI    | ``\https://api-test.wirecard.com/engine/rest/paymentmethods/``

2+h| Headers
e| Content-Type | `application/json`
e| Accept       | `application/json`
|===

//.Request Przelewy24: Debit (JSON)
[source,json]
----
include::json/Przelewy24_Debit_request.json[]
----

[.r-details]
.Response Details
[cols="1v,2"]
|===
2+h| Headers

e| Content-Type | `application/json`
2+h| Status
e| Code        | ``201.0000``
e| Severity    | ``information``
e| Description | ``The resource was successfully created.``

|===

//.Response Przelewy24: Debit (JSON)
[source,json]
----
include::json/Przelewy24_Debit_response.json[]
----

[.tab-content.tab-nvp]
==== NVP

[.r-details]
.Request Details
[cols="1v,2"]
|===
2+| API Endpoint

e| Method | POST
e| URI    | ``\https://api-test.wirecard.com/engine/rest/paymentmethods/``

2+h| Headers
e| Content-Type | `application/x-www-form-urlencoded;charset=UTF-8`
e| Accept       | `text/plain`
|===

//.Request Przelewy24: Debit (NVP)
[source,nvp]
----
include::nvp/Przelewy24_Debit_request.nvp[]
----

[.r-details]
.Response Details
[cols="1v,2"]
|===
2+h| Headers

e| Content-Type | `application/x-www-form-urlencoded;charset=UTF-8`
2+h| Status
e| Code        | ``201.0000``
e| Severity    | ``information``
e| Description | ``The resource was successfully created.``

|===

//.Response Przelewy24: Debit (NVP)
[source,nvp]
----
include::nvp/Przelewy24_Debit_response.nvp[]
----

[.tab-content.tab-xml]
==== XML

[.r-details]
.Request Details
[cols="1v,2"]
|===
2+| API Endpoint

e| Method | POST
e| URI    | ``\https://api-test.wirecard.com/engine/rest/paymentmethods/``

2+h| Headers
e| Content-Type | `application/xml`
e| Accept       | `application/xml`
|===

//.Request Przelewy24: Debit (XML)
[source,xml]
----
include::xml/Przelewy24_Debit_request.xml[]
----

[.r-details]
.Response Details
[cols="1v,2"]
|===
2+h| Headers

e| Content-Type | `application/xml`
2+h| Status
e| Code        | ``201.0000``
e| Severity    | ``information``
e| Description | ``The resource was successfully created.``

|===

//.Response Przelewy24: Debit (XML)
[source,xml]
----
include::xml/Przelewy24_Debit_response.xml[]
----

