[#PPv2_Features_SortFilter]
===== Sort or Filter Payment Methods

The _Sort or Filter_ option allows the merchant to sort or filter the available payment methods in an individual way.
The _Sort or Filter_ option requires either an <<PaymentPageSolutions_PPv2_HPP_Integration, HPP>> integration, <<PaymentPageSolutions_PPv2_EPP_Integration, EPP>> integration or <<PPv2_Seamless_Integration, Seamless>> integration.

[TIP]
.An example situation:
====
The merchant wants to guide the consumer to use a preferred payment method. +
In that case the merchant can use the _Sort or Filter_ option to provide an individual list of payment methods on {payment-page-v2-abbr}.
====

[NOTE]
.Use the _Sort or Filter_ option with a transaction:
====
Add the ``payment-method-order-and-filter`` field to the payment request and list the payment methods. +
Misspellings or unavailable payment methods are ignored. {payment-page-v2-abbr} will display the full list of available payment methods instead.
====

[cols="v,,,"]
[%autowidth]
|===
| Field | Data Type | Parent |Description

| payment-method-order-and-filter | Array | options (\{ }) | Displays the available payment methods in {payment-page-v2-abbr} in the order specified in this field.
|===

[#PPv2_Features_SortFilter_Configure]
[discrete]
====== Configure the _Sort or Filter_ option

Rules to configure the _Sort or Filter_ option:

* The _Sort or Filter_ option is available in JSON only
* Send the _Sort or Filter_ option with each request
* Create a Java Script Array
** List the payment method names in the array in the desired order
** Separate the payment methods names with a comma
** Use an asterisk (*) as a place holder (the asterisk will list all the available payment methods)
** Combine payment method names and an asterisk (list your most popular payment methods by name and add an asterisk for the remaining ones)

//-

[#PPv2_Features_SortFilter_TestTransaction]
[discrete]
====== Send a test transaction

If you want to send a request with the _Sort or Filter_ option you can use the test credentials below and combine them with a sample we provide for <<PPv2_CC_TestCredentials, _Credit Card_>>.

All you have to do, add the "options" element from the example below to your sample request.

[#PPv2_Features_SortFilter_TestTransaction_TestCredentials]
.Test Credentials

[%autowidth.strech,stripes=none,cols="h, "]
|===
| URLs (Endpoints) | ``\https://{pp-test-endpoint}``
| Merchant Account ID (MAID) | ab62ea6e-ba97-48ef-b3bc-bf0319e09d78
| Username   | 70000-APITEST-AP
| Password   | qD2wzQ_hrc!8
| Secret Key | c50a8e09-0648-4d2c-b638-2c14fc7606bc
|===


.Example Request w/ the _Sort or Filter_ option
[source,json,subs=attributes+]
----
include::{root}/samples/json/WPP_FeaturesSortFilterConfiguringSortFilter_ExampleRequestSortFilter.json[]
----
