[#PPv2_Features_SortFilter]
== Sort or Filter Payment Methods

The _Sort or Filter_ option is available for all of our _{payment-page-v2}_ integration options:

* the <<PaymentPageSolutions_PPv2_HPP, _Hosted Payment Page_>> (HPP), 
* the <<PaymentPageSolutions_PPv2_EPP, _Embedded Payment Page_>> (EPP)  or
* the <<PPv2_Seamless, Seamless>> integration. 

//-

This feature allows you to show the available payment methods in your preferred order. +
If you use this feature only the payment methods you define in the array will be shown - in your preferred order.

.An example situation

You want the consumer to use a preferred payment method. +
Use the _Sort or Filter_ option to show the payment methods in your preferred order.

.Rules to configure the _Sort or Filter_ option

. Send the _Sort or Filter_ option with each request. The _Sort or Filter_ option is available in JSON only.
. Create a JavaScript array.
.. Add the ``payment-method-order-and-filter`` field to the payment request.
.. List the payment method names in the array in your preferred order.
.. Separate the payment method names with a comma.
.. Optional: Use the asterisk (*) as a placeholder for available payment methods you don't want to list explicitly.
... List your preferred payment methods by name followed by the asterisk for the other available ones.

//-

[NOTE]
====
Misspellings or unavailable payment methods are ignored. {payment-page-v2-abbr} will display the full list of available payment methods instead.
====

[#PPv2_Features_SortFilter_TestTransaction_TestCredentials]
.Test Credentials

Use the following credentials to test the _Sort or Filter_ option:

[%autowidth.strech,stripes=none,cols="h, "]
|===
| URLs (Endpoints) | ``\https://{pp-test-endpoint}``
| Merchant Account ID (MAID) | ab62ea6e-ba97-48ef-b3bc-bf0319e09d78
| Username   | 70000-APITEST-AP
| Password   | qD2wzQ_hrc!8
| Secret Key | c50a8e09-0648-4d2c-b638-2c14fc7606bc
|===

//-

[#PPv2_Features_SortFilter_ExampleRequest]
.Example Request

[cols="v,,,"]
[%autowidth]
|===
| Field | Data Type | Parent |Description

| payment-method-order-and-filter | Array | options (\{ }) | Displays the available payment methods in {payment-page-v2-abbr} in the order specified in this field.
|===

//-

[source,json,subs=attributes+]
----
include::{root}/samples/json/WPP_FeaturesSortFilterConfiguringSortFilter_ExampleRequestSortFilter.json[]
----

//-