[#PPv2_Features_LimitCardBrands]
== Limit Credit Card Brands

The _Limit Card Brand_ option is available for all of our _{payment-page-v2}_ integration options:

* the <<PaymentPageSolutions_PPv2_HPP, _Hosted Payment Page_>> (HPP), 
* the <<PaymentPageSolutions_PPv2_EPP, _Embedded Payment Page_>> (EPP) or 
* the <<PPv2_Seamless, Seamless>> integration. 

//-

This feature allows you to show only those credit card brands which you prefer to charge. 

.An example situation:

You want to show only those credit card brands which are popular in a certain region. +
Use the _Limit Card Brand_ option to show your preferred credit card brands.

.Configure the _Limit Card Brand_ option:

* Send the _Limit Card Brand_ option with each request. The _Limit Card Brand_ option is available in JSON only.
* Create a JavaScript array.
** List the card brand names in the array. For details, see our supported <<AppendixD, card brands>>.
** Separate the card brand names with a comma.

//-

[cols="v,,,"]
[%autowidth]
|===
| Field | Data Type | Parent |Description

| credit-card-brand-filter | Array | options (\{ }) | Shows the credit card brands, specified in this field.
|===

//-

.Example Request

Use the test credentials and samples we provide for <<PPv2_CC_TestCredentials, _Credit Card_>>. +
Add the ``options`` element from the example below to your sample request.

[source,json,subs=attributes+]
----
include::{root}/samples/json/WPP_FeaturesLimitCardbrandConfiguringLimitCardbrand_ExampleRequestLimitCardbrand.json[]
----

//-