[#PPv2_Features_LimitCardBrands]
== Limit Credit Card Brands

The _Limit Card Brand_ option allows the merchant to display only those credit card brands which he prefers to charge. The _Limit Card Brand_ option can be used with <<PaymentPageSolutions_PPv2_HPP_Integration, HPP>> integration, <<PaymentPageSolutions_PPv2_EPP_Integration, EPP>> integration or <<PPv2_Seamless_Integration, Seamless>> integration.

[TIP]
.An example situation:
====
The merchant wants to display only those credit card brands to the consumer which are locally popular. +
In that case the merchant can use the _Limit Card Brand_ option to provide an individual list of credit card brands on {payment-page-v2-abbr}.
====

[NOTE]
.Use the _Limit Card Brand_ option with a transaction:
====
Add the ``credit-card-brand-filter`` field to the payment request and list the credit card brands. +
Please have a look at the supported <<AppendixD, card brands>> you can choose from. +
If you use the _Limit Card Brand_ option, you must list all the card brands you want to display. The asterisk (*) cannot be used as a shortcut.
====

[cols="v,,,"]
[%autowidth]
|===
| Field | Data Type | Parent |Description

| credit-card-brand-filter | Array | options (\{ }) | Displays the credit card brands, specified in this field, in the {payment-page-v2-abbr}.
|===

[#PPv2_Features_LimitCardBrands_Configure]
=== Configure the _Limit Card Brand_ option

Rules to configure the _Limit Card Brand_ option:

* The _Limit Card Brand_ option is available in JSON only.
* Send the _Limit Card Brand_ option with each request.
* Create a Java Script Array.
** List the card brand names in the array.
** Separate the card brand names with a comma.

//-

[#PPv2_Features_LimitCardBrands_TestTransaction]
=== Send a test transaction

If you want to send a request with the _Limit Card Brand_ option you can use the test credentials and samples we provide for <<PPv2_CC_TestCredentials, _Credit Card_>>.

All you have to do is add the ``options`` element from the example below to your sample request.

.Example Request w/ the _Limit Card Brand_ option
[source,json,subs=attributes+]
----
include::{root}/samples/json/WPP_FeaturesLimitCardbrandConfiguringLimitCardbrand_ExampleRequestLimitCardbrand.json[]
----
