[#PPv2_Features_SortFilter]
== Sort or Filter Payment Methods

The _Sort or Filter_ option is available for all of our _{payment-page-v2}_ integration options:

* the <<PaymentPageSolutions_PPv2_HPP_Integration, _Hosted Payment Page_>> (HPP)
* the <<PaymentPageSolutions_PPv2_EPP_Integration, _Embedded Payment Page_>> (EPP)
* the <<PPv2_Seamless_Integration, Seamless>> integration

This feature allows you to present the available payment methods in a desired order to the consumer.

.An example situation

You want the consumer to use a preferred payment method. +
Send the consumer a personalized list of payment methods on {payment-page-v2-abbr} via the _Sort or Filter_ option.

.Rules to configure the _Sort or Filter_ option

NOTE: Misspellings of payment method names or unavailable payment methods are ignored. {payment-page-v2-abbr} will display the full list of available payment methods instead.

* The _Sort or Filter_ option is available in JSON only.
* Send the _Sort or Filter_ option with each request.
* Create a Java Script Array.
** Add the ``payment-method-order-and-filter`` field to the payment request
** List the payment method names in the array in the desired order.
** Separate the payment method names with a comma.
** Use the asterisk (*) as a place holder. 
*** A single asterisk in the array will list all the available payment methods.
*** Combine payment method names with the asterisk: List your most popular payment methods by name and add the asterisk for the remaining ones.

//-

[#PPv2_Features_SortFilter_TestTransaction_TestCredentials]
.Test Credentials

Use the following credentials to test the _Sort or Filter_ option:

[%autowidth.strech,stripes=none,cols="h, "]
|===
| URLs (Endpoints) | ``\https://{pp-test-endpoint}``
| Merchant Account ID (MAID) | ab62ea6e-ba97-48ef-b3bc-bf0319e09d78
| Username   | 70000-APITEST-AP
| Password   | qD2wzQ_hrc!8
| Secret Key | c50a8e09-0648-4d2c-b638-2c14fc7606bc
|===

[#PPv2_Features_SortFilter_ExampleRequest]
=== Example Request

[cols="v,,,"]
[%autowidth]
|===
| Field | Data Type | Parent |Description

| payment-method-order-and-filter | Array | options (\{ }) | Displays the available payment methods in {payment-page-v2-abbr} in the order specified in this field.
|===

.Example Request w/ the _Sort or Filter_ option
[source,json,subs=attributes+]
----
include::{root}/samples/json/WPP_FeaturesSortFilterConfiguringSortFilter_ExampleRequestSortFilter.json[]
----
