[#PPv2_Features_LimitCardBrands]
== Limit Credit Card Brands

The _Limit Card Brand_ option is available for all of our _{payment-page-v2}_ integration options:

* the <<PaymentPageSolutions_PPv2_HPP, _Hosted Payment Page_>> (HPP), 
* the <<PaymentPageSolutions_PPv2_EPP, _Embedded Payment Page_>> (EPP) or 
* the <<PPv2_Seamless, Seamless>> integration. 

//-

The _Limit Card Brand_ option is available in JSON only. +
Use this option to display only those credit card brands which you prefer to charge. 
You can, for example, display a different set of credit card brands for consumers in different regions in the world.

.Configure the _Limit Card Brand_ Option

* Send the _Limit Card Brand_ option with each request. 
* Create a JavaScript array.
* Add the ``credit-card-brand-filter`` field to the payment request.
* Enter the credit card brand names in the array in your preferred order. For details, see our supported <<AppendixD, credit card brands>>.
* Separate the credit card brand names with a comma.

//-

[cols="v,,,"]
[%autowidth]
|===
| Field | Data Type | Parent |Description

| credit-card-brand-filter | Array | options (\{ }) | Displays the credit card brands, specified in this field.
|===

//-

.Example Request

Use the test credentials we provide for <<PPv2_CC_TestCredentials, _Credit Card_>> and send the sample below. +

[source,json,subs=attributes+]
----
include::{root}/samples/json/WPP_FeaturesLimitCardbrandConfiguringLimitCardbrand_ExampleRequestLimitCardbrand.json[]
----

//-