[#PPv2_Features_OrderFilter]
== Order and Filter Payment Methods

The _Order and Filter_ option is available for all of our _{payment-page-v2}_ integration options:

* the <<PaymentPageSolutions_PPv2_HPP, _Hosted Payment Page_>> (HPP), 
* the <<PaymentPageSolutions_PPv2_EPP, _Embedded Payment Page_>> (EPP)  or
* the <<PPv2_Seamless, Seamless>> integration. 

//-

The _Order and Filter_ option is available in JSON only. +
This option allows you to display the available payment methods in your preferred order. +
If you use this option, only the payment methods defined are displayed. All the other payment methods are ignored.

//-

.Configure the _Order and Filter_ option

* Send the _Order and Filter_ option with each request. 
* Create a JavaScript array.
* Add the ``payment-method-order-and-filter`` field to the payment request.
* Enter the payment method names in the array in your preferred order.
* Separate the payment method names with a comma.

//-

Optionally you can use the asterisk (*) as a placeholder for available payment methods you do not want to order explicitly. +
Enter your preferred payment method names followed by an asterisk. +
As a result you display all the payment methods you offer, with your preferred ones first.

[NOTE]
====
Misspellings or unavailable payment methods are ignored. {payment-page-v2-abbr} will display the full list of available payment methods instead.
====

[#PPv2_Features_OrderFilter_TestTransaction_TestCredentials]
.Test Credentials

Use the following credentials to test the _Order and Filter_ option:

[%autowidth.strech,stripes=none,cols="h, "]
|===
| URLs (Endpoints) | ``\https://{pp-test-endpoint}``
| Merchant Account ID (MAID) | ab62ea6e-ba97-48ef-b3bc-bf0319e09d78
| Username   | 70000-APITEST-AP
| Password   | qD2wzQ_hrc!8
| Secret Key | c50a8e09-0648-4d2c-b638-2c14fc7606bc
|===

//-

[#PPv2_Features_OrderFilter_ExampleRequest]
.Example Request

[cols="v,,,"]
[%autowidth]
|===
| Field | Data Type | Parent |Description

| payment-method-order-and-filter | Array | options (\{ }) | Displays the available payment methods in {payment-page-v2-abbr} in the order specified in this field.
|===

//-

[source,json,subs=attributes+]
----
include::{root}/samples/json/WPP_FeaturesOrderFilterConfiguringOrderFilter_ExampleRequestOrderFilter.json[]
----

//-