[#KlarnaV2_TransactionTypes_authorizationRecurring]
==== Recurring _authorization_

Klarna Payments support <<GeneralPlatformFeatures_Transactions_Recurring, Recurring>> transactions. +

If you send appropriate values for ``periodic-type`` and ``sequence-type``, {payment-gateway} generates a consumer token that can be used for recurring payments.



[#KlarnaV2_TransactionTypes_authorizationRecurring_Fields]
===== Recurring _authorization_ Fields

Fields can be **M**andatory or **O**ptional.

[%autowidth,stripes=none]
[cols="m,,,,"]
|===
|Field |<<APIRef_FieldDefs_Cardinality, M/O>> |Data Type |Size |Description

|merchant-account-id 
|M 
|String 
|36 
|A unique identifier assigned
to every merchant account (by {payment-provider-name}).

|request-id 
|M
|String 
|150 
a|A unique identifier assigned by the merchant
to each request. Used when searching for or referencing it later.

As the request ID must be unique, ``{{$guid}}`` serves as a placeholder; Postman
uses it to generate a random ``request-id`` for testing.

Allowed characters:  ``[a-z0-9-\_]``.

|transaction-type 
|M  
|String
|30 
|The requested transaction type. Set this field to `authorization`.

|requested-amount  
|M
|Numeric
|18,3
|Total order amount to be reserved. The number of decimal places depends on the currency. +
The requested amount must be equal to the amount sum of all order items.

Use ``.`` (decimal point) as separator.

|[[KlarnaV2_TransactionTypes_authorization_Fields_requestedAmount_currency]]requested-amount@currency 
|M  
|String
|3 
a|The <<KlarnaV2_CountriesCurrencies, currency>> of the requested/contested
transaction amount. +
Format: 3-character abbreviation according to ISO 4217.

|order-number	
|O 
|String
|255 
|Order number of the merchant. +
If set, it shows as "order number" on _Klarna_'s payment confirmation page.

|locale	
|M 
|String
|5 
|A 5-letter code which indicates what <<KlarnaV2_Locales, language>> the payment page is rendered in (RFC 1766).

|parent-transaction-id
|M/O 
|String	
|36	
a|Enter the ``transaction-id`` of a preceding _authorization_. This can be either the first (``initial``) or any other previous (``recurring``) authorization. +
**Mandatory** for recurring authorizations with sequence type ``recurring`` or ``final`.`

5+<.>h|``periodic``

|periodic-type
|M
|String
|24	
a|Periodic type of recurring/periodic purchase: +

* ``recurring``
* ``installment``
//-

Both values are equivalent.

|sequence-type
|M
|String
|10	
a|Sequence type of recurring/periodic purchase: +

* ``first`: For initial authorization request. is send to engine/rest/paymentmethods endpoint.`
* ``recurring``: For recurring authorization requests that follow the initial recurring purchase or other recurring purchase(s). Authorization request is send to engine/rest/payments endpoint.
* ``final``: For the last recurring authorization. Authorization request is send to engine/rest/payments endpoint.
//-

|transaction-id 
|Response only
|String
|36
|A unique identifier assigned for every transaction. Generated by {payment-provider-name}. Used when searching for or referencing it later.

|transaction-state 
|Response only
|String
|12
a|Transaction status. +
Possible values: 

  - ``success``
  - ``failed``

//-

|completion-time-stamp
|Response only
|DateTime
|
|The timestamp documents the time and date when the transaction was completed.

include::{root}/include/klarna-payments/fields/klarnaPayments_fields_paymentMethod.adoc[tags=**;!txTypes]

include::{root}/include/klarna-payments/fields/klarnaPayments_fields_notifications.adoc[]

include::{root}/include/klarna-payments/fields/klarnaPayments_fields_accountHolder.adoc[]

include::{root}/include/klarna-payments/fields/klarnaPayments_fields_accountHolderAddress.adoc[]

include::{root}/include/klarna-payments/fields/klarnaPayments_fields_shipping.adoc[]

include::{root}/include/klarna-payments/fields/klarnaPayments_fields_orderItems.adoc[]

include::{root}/include/klarna-payments/fields/klarnaPayments_fields_status.adoc[]

|@provider-code
|Response only
|String
|34
|Original _Klarna_ error code.

|@provider-message
|Response only
|String
|
|Error message to be shown to the consumer as required by _Klarna_.

|@provider-transaction-id 
|Response only
|String
|36
|_Klarna_ reservation number.

4+<.>s|``additional-provider-data.provider-data``
s|Contains max. 1 additional data item for _Klarna_.

|request
|O
|String
|
|Content should be an object containing any of the keys and sub objects described in https://developers.klarna.com/api/#payments-api-create-a-new-credit-session serialised to JSON. +
E.g. +
 ``{"marketplace_seller_info":[{"product_category":"Women''s Fashion","product_name":"Women Sweatshirt"}]}`` +

|===

[#KlarnaV2_TransactionTypes_authorizationRecurring_Samples]
===== _authorization_ Samples

._authorization_ Request
[source,xml,subs=attributes+]
----
include::{root}/samples/xml/Klarnav2_authorization_request.xml[]
----

._authorization_ Response
[source,xml,subs=attributes+]
----
include::{root}/samples/xml/Klarnav2_authorization_response.xml[]
----

NOTE: To proceed with a successful authorization transaction, take the URL from ``<payment-method url="http://...">`` from the response, replace ``\&amp;`` with ``&`` and redirect your consumer to this URL.

._authorization_ Notification XML
[source,xml,subs=attributes+]
----
include::{root}/samples/xml/Klarnav2_authorization_notification.xml[]
----

//-

