[#CreditCard]
== REST API & {payment-page-v1}

[#CreditCard_PaymentModeCountriesandCurrencies]
=== Payment Mode, Countries and Currencies

[width=75%,stripes=none,cols="1,2"]
|===
h| Payment Mode a|
ifdef::env-wirecard[]
<<PaymentMethods_PaymentMode_OnlineBankTransfer, Online Bank Transfer>>, <<PaymentMethods_PaymentMode_OfflineBankTransfer, Offline Bank Transfer>>
endif::[]

ifdef::env-po[]
Online Bank Transfer, Offline Bank Transfer
endif::[]
h| Countries | Depends on the licensed area of the financial institution/acquirer.
ifdef::env-wirecard[]
Wirecard Bank, for example, is licensed to process payments globally.
endif::[]

h| Currencies a|
ifdef::env-wirecard[]
ifndef::env-nova[]
VISA and MC support basically all currencies. For more information, go to their respective manuals. JCB and UPI require an explicit setup of transaction currencies as part of the acquirer license agreement.
endif::[]
endif::[]

ifdef::env-nova,env-po[]
VISA and MC support basically all currencies. For more information, go to their respective manuals.
endif::[]
|===

[discrete]
[#CreditCard_CommunicationFormats]
=== Communication Formats

This table illustrates how _credit card_ notifications are encoded and which formats and methods can be used for requests and responses.

[width=75%,stripes=none]
|===
.2+h| Requests | Format | XML
                | Methods | POST
.2+h| Responses | Format | XML
                 | Methods | POST
h| IPN Encodement 2+| Please follow the instructions given at <<GeneralPlatformFeatures_IPN_NotificationExamples, Instant Payment Notification>> to set up IPN.
|===

//-
