[#PPv2_APM_JSONNVPFields]
====== JSON/NVP Field Reference

In the following samples we present lists of fields you can send with alternative payment methods, divided between request fields and pure response fields.
The samples already are structured according to the request's requirement. You can use these fields to extend your requests with any of the Alternative Payment Methods. The field names are accompanied by the data type. In most of the cases it is sufficient that you replace the data type with corresponing data.

//// 

Karin, if we provide optional fields to let the merchant use them for extended requests why should we list response fields as well? I mean, the response fields come back depending on the fields you provide in the request. So I'd suggest that we only list fields the merchant can definitely use...

////

//-

[#PPv2_APM_JSONNVPSample_request]
.JSON Structure of an Alternative Payment Method Request

[source,json,subs=attributes+]
----
{
	"payment":{
		"merchant-account-id":{
			"value":"String"
		},
		"request-id":"String",
		"transaction-type":"String",
		"requested-amount":{
			"value":"Numeric",
			"currency":"String"
		},
		"parent-transaction-id":"String",
		"account-holder":{
			"first-name":"String",
			"last-name":"String"
			"email": "String",
			"phone": "String"
			"address":{
				"city": "String",
				"country": "String",
				"postal-code": "String",
				"state": "String",
				"street1": "String",
				"street2": "String"
			}
		},
		"shipping": {
			"first-name": "String",
			"last-name": "String",
			"phone": "String",
			"address": {
				"city": "String",
				"country": "String",
				"postal-code": "String",
				"state": "String",
				"street1": "String",
				"street2": "String"
			}
		},
		"payment-methods":{
			"payment-method":[
				{
					"name":"String"
				},
			],
		},
		"bank-account": {
			"iban":"String"
		},
		"mandate": {
			"mandate-id":"String",
			"signed-date":"String"
		},
		"creditor-id":"String",
		"periodic":{
			"periodic-type":"String",
			"sequence-type":"String"
		},
		"descriptor": "String",
		"order-number": "String",
		"success-redirect-url": "String",
		"fail-redirect-url": "String",
		"cancel-redirect-url": "String",
		"b2-b":true
	}
}
----



[#PPv2_APM_JSON_NVPSample_Response]
.Response-Only Fields in an Alternative Payment Method Response

[source,json]
----
{
  "payment": {
    "api-id": "String",
    "wallet": {
      "account-id": "String"
    },
    "transaction-id": "String",
    "completion-time-stamp": "Date",
    "statuses": {
      "status": [
        {
          "code": "String",
          "description": "String",
          "severity": "String"
        }
      ]
    },
    "provider-transaction-reference-id": "String",
    "instrument-country": "String",
    "transaction-state": "String"
  }
}
----

//-