[#PPv2_APM_JSONNVPFields]
====== JSON/NVP Field Reference

Here you can find the NVP equivalents for JSON fields (for migrating merchants).

In the following tables and samples we present lists of fields, divided between request fields and pure response fields.
The samples are representative request and response samples for Alternative Payment Methods indicating the data type of each field.
The lists show all the mandatory fields and a large variety of optional fields. In the tables the fields are sorted alphabetically.

//-

[#PPv2_APM_JSONNVPSample_request]
.JSON Structure of an Alternative Payment Method Request

[source,json,subs=attributes+]
----
{
	"payment":{
		"merchant-account-id":{
			"value":"String"
		},
		"request-id":"String",
		"transaction-type":"String",
		"requested-amount":{
			"value":"Numeric",
			"currency":"String"
		},
		"parent-transaction-id":"String",
		"account-holder":{
			"first-name":"String",
			"last-name":"String"
			"email": "String",
			"phone": "String"
			"address":{
				"city": "String",
				"country": "String",
				"postal-code": "String",
				"state": "String",
				"street1": "String",
				"street2": "String"
			}
		},
		"shipping": {
			"first-name": "String",
			"last-name": "String",
			"phone": "String",
			"address": {
				"city": "String",
				"country": "String",
				"postal-code": "String",
				"state": "String",
				"street1": "String",
				"street2": "String"
			}
		},
		"payment-methods":{
			"payment-method":[
				{
					"name":"String"
				},
			],
		},
		"bank-account": {
			"iban":"String"
		},
		"mandate": {
			"mandate-id":"String",
			"signed-date":"String"
		},
		"creditor-id":"String",
		"periodic":{
			"periodic-type":"String",
			"sequence-type":"String"
		},
		"descriptor": "String",
		"order-number": "String",
		"success-redirect-url": "String",
		"fail-redirect-url": "String",
		"cancel-redirect-url": "String",
		"b2-b":true
	}
}
----

[#PPv2_APM_JSON_NVPFields_Request]
[cols="e,e,e"]
|===
| Field (NVP) | Field (JSON) | JSON Parent

| b2b | b2-b | payment ({ })
| bank_account_iban | iban | bank-account ({ })
| cancel_redirect_url | cancel-redirect-url | payment ({ })
| city | address ({ })/ city | account-holder ({ })
| country | address ({ })/ country | account-holder ({ })
| creditor_id | creditor-id | payment ({ })
| descriptor | descriptor | payment ({ })
| email | email | account-holder ({ })
| fail_redirect_url | fail-redirect-url | payment ({ })
| first_name | first-name | account-holder ({ })
| last_name | last-name | account-holder ({ })
| mandate_mandate_id | mandate-id | mandate ({ })
| mandate_signed_date | signed-date | mandate ({ })
| merchant_account_id | value | merchant-account-id ({ })
| order_number | order-number | payment ({ })
| payment_method | payment-method ([ ])/name | payment-methods ({ })
| periodic_type | periodic-type | periodic ({ })
| phone | phone | account-holder ({ })
| postal_code | address ({ })/ postal-code | account-holder ({ })
| request_id | request-id | payment ({ })
| requested_amount | value | requested-amount ({ })
| requested_amount_currency | currency | requested-amount ({ })
| sequence_type | sequence-type | periodic ({ })
| shipping_city | address ({ })/ city | shipping ({ })
| shipping_country | address ({ })/ country | shipping ({ })
| shipping_first_name | first-name | shipping ({ })
| shipping_last_name | last-name | shipping ({ })
| shipping_phone | phone | shipping ({ })
| shipping_postal_code | address ({ })/ postal-code | shipping ({ })
| shipping_state | address ({ })/ state | shipping ({ })
| shipping_street1 | address ({ })/ street1 | shipping ({ })
| shipping_street2 | address ({ })/ street2 | shipping ({ })
| state | address ({ })/ state | account-holder ({ })
| street1 | address ({ })/ street1 | account-holder ({ })
| street2 | address ({ })/ street2 | account-holder ({ })
| success_redirect_url | success-redirect-url | payment ({ })
| transaction_type | transaction-type | payment ({ })
|===

[#PPv2_APM_JSON_NVPSample_Response]
.Response-Only Fields in an Alternative Payment Method Response

[source,json]
----
{
  "payment": {
    "api-id": "String",
    "wallet": {
      "account-id": "String"
    },
    "transaction-id": "String",
    "completion-time-stamp": "Date",
    "statuses": {
      "status": [
        {
          "code": "String",
          "description": "String",
          "severity": "String"
        }
      ]
    },
    "provider-transaction-reference-id": "String",
    "instrument-country": "String",
    "transaction-state": "String"
  }
}
----


[#PPv2_APM_JSON_NVPFields_Response]
[cols="e,e,e"]
|===
| Field (NVP) | Field (JSON) | JSON Parent

| api_id | api-id | payment ({ })
| completion_time_stamp | completion-time-stamp | payment ({ })
| instrument_country | instrument-country | payment ({ })
| provider_transaction_id_n | status ([ { } ])/ provider-transaction-id | statuses ({ })
| provider_transaction_reference_id | provider-transaction-reference-id | payment ({ })
| status_code_n | status ([ { } ])/ code | statuses ({ })
| status_description_n | status ([ {} ])/ description | statuses ({ })
| status_severity_n | status ([ { } ])/ severity | statuses ({ })
| transaction_id | transaction-id | payment ({ })
| transaction_state | transaction-state | payment ({ })
| wallet_account_id | account-id | wallet ({ })
|===