[#PPv2_APM_JSONNVPFields]
====== JSON/NVP Field Reference

Here you can find the NVP equivalents for JSON fields (for migrating merchants).

In the following tables and samples we present lists of fields devided between request fields and pure response fields.
The lists show all the mandatory fields and a large variety of optional fields. In the tables the fields are sorted alphabetically.

//-

[#PPv2_PayPal_JSONNVPFields_request]
.JSON Structure of a _PayPal_ Request

[source,json,subs=attributes+]
----
{
	"payment":{
		"merchant-account-id":{
			"value":"string"
		},
		"request-id":"string",
		"transaction-type":"string",
		"requested-amount":{
			"value":0,
			"currency":"string"
		},
		"parent-transaction-id":"string",
		"account-holder":{
			"first-name":"string",
			"last-name":"string"
			"email": "string",
			"phone": "string"
			"address":{
				"city": "string",
				"country": "string",
				"postal-code": "string",
				"state": "string",
				"street1": "string",
				"street2": "string"
			},
		},
		"shipping": {
			"first-name": "string",
			"last-name": "string",
			"phone": "string"
			"address": {
				"city": "string",
				"country": "string",
				"postal-code": "string",
				"state": "string",
				"street1": "string",
				"street2": "string"
			},
		},
		"payment-methods":{
			"payment-method":[
				{
					"name":"string"
				},
			],
		},
		"bank-account": {
			"iban":"string"
		},
		"mandate": {
			"mandate-id":"string",
			"signed-date":"string"
		},
		"creditor-id":"string",
		"periodic":{
			"periodic-type":"string",
			"sequence-type":"string"
		},
		"descriptor": "string",
		"order-number": "string",
		"success-redirect-url": "string",
		"fail-redirect-url": "string",
		"cancel-redirect-url": "string",
		"b2-b":true
	}
}
----

[cols="e,e,e"]
|===
|Field (NVP) |Field (JSON) |JSON Parent

| b2b | b2-b | payment ({ })
| bank_account_iban | iban | bank-account ({ })
| cancel_redirect_url | cancel-redirect-url | payment ({ })
| city | address ({ })/ city | account-holder ({ })
| country | address ({ })/ country | account-holder ({ })
| creditor_id | creditor-id | payment ({ })
| descriptor | descriptor | payment ({ })
| email | email | account-holder ({ })
| fail_redirect_url | fail-redirect-url | payment ({ })
| first_name | first-name | account-holder ({ })
| last_name | last-name | account-holder ({ })
| mandate_mandate_id | mandate-id | mandate ({ })
| mandate_signed_date | signed-date | mandate ({ })
| merchant_account_id | value | merchant-account-id ({ })
| order_number | order-number | payment ({ })
| payment_method | payment-method ([ ])/name | payment-methods ({ })
| periodic_type | periodic-type | periodic ({ })
| phone | phone | account-holder ({ })
| postal_code | address ({ })/ postal-code | account-holder ({ })
| request_id | request-id | payment ({ })
| requested_amount | value | requested-amount ({ })
| requested_amount_currency | currency | requested-amount ({ })
| sequence_type | sequence-type | periodic ({ })
| shipping_city | address ({ })/ city | shipping ({ })
| shipping_country | address ({ })/ country | shipping ({ })
| shipping_first_name | first-name | shipping ({ })
| shipping_last_name | last-name | shipping ({ })
| shipping_phone | phone | shipping ({ })
| shipping_postal_code | address ({ })/ postal-code | shipping ({ })
| shipping_state | address ({ })/ state | shipping ({ })
| shipping_street1 | address ({ })/ street1 | shipping ({ })
| shipping_street2 | address ({ })/ street2 | shipping ({ })
| state | address ({ })/ state | account-holder ({ })
| street1 | address ({ })/ street1 | account-holder ({ })
| street2 | address ({ })/ street2 | account-holder ({ })
| success_redirect_url | success-redirect-url | payment ({ })
| transaction_type | transaction-type | payment ({ })

|===

[#PPv2_PayPal_JSONNVPField_response]
.JSON Structure of a _PayPal_ Response

[source,json]
----
{
  "payment": {
    "api-id": "string",
    "wallet": {
      "account-id": "string"
    },
    "transaction-id": "string",
    "completion-time-stamp": "2019-02-21T09:38:57.645Z",
    "statuses": {
      "status": [
        {
          "code": "string",
          "description": "string",
          "severity": "string"
        }
      ]
    },
    "provider-transaction-reference-id": "string",
    "instrument-country": "string",
    "transaction-state": "string"
  }
}
----

[cols="e,e,e"]
|===
|Field (NVP) |Field (JSON) |JSON Parent

| api_id | api-id | payment ({ })
| completion_time_stamp | completion-time-stamp | payment ({ })
| instrument_country | instrument-country | payment ({ })
| provider_transaction_id_n | status ([ { } ])/ provider-transaction-id | statuses ({ })
| provider_transaction_reference_id | provider-transaction-reference-id | payment ({ })
| status_code_n | status ([ { } ])/ code | statuses ({ })
| status_description_n | status ([ {} ])/ description | statuses ({ })
| status_severity_n | status ([ { } ])/ severity | statuses ({ })
| transaction_id | transaction-id | payment ({ })
| transaction_state | transaction-state | payment ({ })
| wallet_account_id | account-id | wallet ({ })
|===
