[discrete.sample-tabs]

=== Klarna SE Invoice: Partial Capture
[discrete.tab-content.tab-json]
==== JSON

[.r-details]
.Request Details
[cols="1v,2"]
|===
2+| API Endpoint

e| Method | POST
e| URI    | ``\https://api-test.wirecard.com/engine/rest/payments/``

2+h| Headers
e| Content-Type | `application/json`
e| Accept       | `application/json`
|===

//.Request Klarna SE Invoice: Partial Capture (JSON)
[source,json]
----
include::json/Klarna_SE_Invoice_PartialCapture_request.json[]
include::nvp/CarrierBilling_Debit_request_tbl.adoc[]

----

[.r-details]
.Response Details
[cols="1v,2"]
|===
2+h| Headers

e| Content-Type | `application/json`
2+h| Status
e| Code        | ``500.1999``
e| Severity    | ``error``
e| Description | ``guaranteed:The acquirer returned an unknown response.  Contact Technical Support.``
2+|
e| Code        | ``201.0000``
e| Severity    | ``information``
e| Description | ``The resource was successfully created.``

|===

//.Response Klarna SE Invoice: Partial Capture (JSON)
[source,json]
----
include::json/Klarna_SE_Invoice_PartialCapture_response.json[]
----

include::nvp/CarrierBilling_Debit_response_tbl.adoc[]

[discrete.tab-content.tab-xml]
==== XML

[.r-details]
.Request Details
[cols="1v,2"]
|===
2+| API Endpoint

e| Method | POST
e| URI    | ``\https://api-test.wirecard.com/engine/rest/payments/``

2+h| Headers
e| Content-Type | `application/xml`
e| Accept       | `application/xml`
|===

//.Request Klarna SE Invoice: Partial Capture (XML)
[source,xml]
----
include::xml/Klarna_SE_Invoice_PartialCapture_request.xml[]
include::nvp/CarrierBilling_Debit_request_tbl.adoc[]

----

[.r-details]
.Response Details
[cols="1v,2"]
|===
2+h| Headers

e| Content-Type | `application/xml`
2+h| Status
e| Code        | ``500.1999``
e| Severity    | ``error``
e| Description | ``guaranteed:The acquirer returned an unknown response.  Contact Technical Support.``
2+|
e| Code        | ``201.0000``
e| Severity    | ``information``
e| Description | ``The resource was successfully created.``

|===

//.Response Klarna SE Invoice: Partial Capture (XML)
[source,xml]
----
include::xml/Klarna_SE_Invoice_PartialCapture_response.xml[]
----

include::nvp/CarrierBilling_Debit_response_tbl.adoc[]

