[discrete.sample-tabs]

=== Klarna DE Invoice: Authorization for Partial Capture
[discrete.tab-content.tab-json]
==== JSON

[.r-details]
.Request Details
[cols="1v,2"]
|===
2+| API Endpoint

e| Method | POST
e| URI    | ``\https://api-test.wirecard.com/engine/rest/paymentmethods/``

2+h| Headers
e| Content-Type | `application/json`
e| Accept       | `application/json`
|===

//.Request Klarna DE Invoice: Authorization for Partial Capture (JSON)
[source,json]
----
include::json/Klarna_DE_Invoice_AuthorizationForPartialCapture_request.json[]
include::nvp/CarrierBilling_Debit_request_tbl.adoc[]

----

[.r-details]
.Response Details
[cols="1v,2"]
|===
2+h| Headers

e| Content-Type | `application/json`
2+h| Status
e| Code        | ``201.0000``
e| Severity    | ``information``
e| Description | ``The resource was successfully created.``

|===

//.Response Klarna DE Invoice: Authorization for Partial Capture (JSON)
[source,json]
----
include::json/Klarna_DE_Invoice_AuthorizationForPartialCapture_response.json[]
----

include::nvp/CarrierBilling_Debit_response_tbl.adoc[]

[discrete.tab-content.tab-xml]
==== XML

[.r-details]
.Request Details
[cols="1v,2"]
|===
2+| API Endpoint

e| Method | POST
e| URI    | ``\https://api-test.wirecard.com/engine/rest/paymentmethods/``

2+h| Headers
e| Content-Type | `application/xml`
e| Accept       | `application/xml`
|===

//.Request Klarna DE Invoice: Authorization for Partial Capture (XML)
[source,xml]
----
include::xml/Klarna_DE_Invoice_AuthorizationForPartialCapture_request.xml[]
include::nvp/CarrierBilling_Debit_request_tbl.adoc[]

----

[.r-details]
.Response Details
[cols="1v,2"]
|===
2+h| Headers

e| Content-Type | `application/xml`
2+h| Status
e| Code        | ``201.0000``
e| Severity    | ``information``
e| Description | ``The resource was successfully created.``

|===

//.Response Klarna DE Invoice: Authorization for Partial Capture (XML)
[source,xml]
----
include::xml/Klarna_DE_Invoice_AuthorizationForPartialCapture_response.xml[]
----

include::nvp/CarrierBilling_Debit_response_tbl.adoc[]

