[discrete.sample-tabs]

=== paysafecard: Capture Authorization
[discrete.tab-content.tab-json]
==== JSON

[.r-details]
.Request Details
[cols="1v,2"]
|===
2+| API Endpoint

e| Method | POST
e| URI    | ``\https://api-test.wirecard.com/engine/rest/payments/``

2+h| Headers
e| Content-Type | `application/json`
e| Accept       | `application/json`
|===

//.Request paysafecard: Capture Authorization (JSON)
[source,json]
----
include::json/Paysafecard_CaptureAuthorization_request.json[]
include::nvp/Paysafecard_Authorization_request_tbl.adoc[]

----

[.r-details]
.Response Details
[cols="1v,2"]
|===
2+h| Headers

e| Content-Type | `application/json`
2+h| Status
e| Code        | ``201.0000``
e| Severity    | ``information``
e| Description | ``paysafecard:The resource was successfully created.``

|===

//.Response paysafecard: Capture Authorization (JSON)
[source,json]
----
include::json/Paysafecard_CaptureAuthorization_response.json[]
----

include::nvp/Paysafecard_Authorization_response_tbl.adoc[]

[discrete.tab-content.tab-xml]
==== XML

[.r-details]
.Request Details
[cols="1v,2"]
|===
2+| API Endpoint

e| Method | POST
e| URI    | ``\https://api-test.wirecard.com/engine/rest/payments/``

2+h| Headers
e| Content-Type | `application/xml`
e| Accept       | `application/xml`
|===

//.Request paysafecard: Capture Authorization (XML)
[source,xml]
----
include::xml/Paysafecard_CaptureAuthorization_request.xml[]
include::nvp/Paysafecard_Authorization_request_tbl.adoc[]

----

[.r-details]
.Response Details
[cols="1v,2"]
|===
2+h| Headers

e| Content-Type | `application/xml`
2+h| Status
e| Code        | ``201.0000``
e| Severity    | ``information``
e| Description | ``paysafecard:The resource was successfully created.``

|===

//.Response paysafecard: Capture Authorization (XML)
[source,xml]
----
include::xml/Paysafecard_CaptureAuthorization_response.xml[]
----

include::nvp/Paysafecard_Authorization_response_tbl.adoc[]

