[discrete.sample-tabs]

=== POI/PIA: Authorization
[discrete.tab-content.tab-json]
==== JSON

[.r-details]
.Request Details
[cols="1v,2"]
|===
2+| API Endpoint

e| Method | POST
e| URI    | ``\https://api-test.wirecard.com/engine/rest/paymentmethods/``

2+h| Headers
e| Content-Type | `application/json`
e| Accept       | `application/json`
|===

//.Request POI/PIA: Authorization (JSON)
[source,json]
----
include::json/POIPIA_Authorization_request.json[]
include::nvp/CarrierBilling_Debit_request_tbl.adoc[]

----

[.r-details]
.Response Details
[cols="1v,2"]
|===
2+h| Headers

e| Content-Type | `application/json`
2+h| Status
e| Code        | ``201.0000``
e| Severity    | ``information``
e| Description | ``The resource was successfully created.``
2+|
e| Code        | ``100.0000``
e| Severity    | ``information``
e| Description | ``Transaction Processing has begun, and the outcome of the Transaction is not yet known.``

|===

//.Response POI/PIA: Authorization (JSON)
[source,json]
----
include::json/POIPIA_Authorization_response.json[]
----

include::nvp/CarrierBilling_Debit_response_tbl.adoc[]

[discrete.tab-content.tab-xml]
==== XML

[.r-details]
.Request Details
[cols="1v,2"]
|===
2+| API Endpoint

e| Method | POST
e| URI    | ``\https://api-test.wirecard.com/engine/rest/paymentmethods/``

2+h| Headers
e| Content-Type | `application/xml`
e| Accept       | `application/xml`
|===

//.Request POI/PIA: Authorization (XML)
[source,xml]
----
include::xml/POIPIA_Authorization_request.xml[]
include::nvp/CarrierBilling_Debit_request_tbl.adoc[]

----

[.r-details]
.Response Details
[cols="1v,2"]
|===
2+h| Headers

e| Content-Type | `application/xml`
2+h| Status
e| Code        | ``201.0000``
e| Severity    | ``information``
e| Description | ``The resource was successfully created.``
2+|
e| Code        | ``100.0000``
e| Severity    | ``information``
e| Description | ``Transaction Processing has begun, and the outcome of the Transaction is not yet known.``

|===

//.Response POI/PIA: Authorization (XML)
[source,xml]
----
include::xml/POIPIA_Authorization_response.xml[]
----

include::nvp/CarrierBilling_Debit_response_tbl.adoc[]

