[discrete.sample-tabs]

=== SEPA Direct Debit: authorization
[discrete.tab-content.tab-json]
==== JSON

[.r-details]
.Request Details
[cols="1v,2"]
|===
2+| API Endpoint

e| Method | POST
e| URI    | ``\https://api-test.wirecard.com/engine/rest/paymentmethods/``

2+h| Headers
e| Content-Type | `application/json`
e| Accept       | `application/json`
|===

//.Request SEPA Direct Debit: authorization (JSON)
[source,json]
----
include::json/SEPA_DirectDebit_Authorization_request.json[]
include::nvp/Paysafecard_AuthorizationForVoid_request_tbl.adoc[]

----

[.r-details]
.Response Details
[cols="1v,2"]
|===
2+h| Headers

e| Content-Type | `application/json`
2+h| Status
e| Code        | ``201.0000``
e| Severity    | ``information``
e| Description | ``The resource was successfully created.``

|===

//.Response SEPA Direct Debit: authorization (JSON)
[source,json]
----
include::json/SEPA_DirectDebit_Authorization_response.json[]
----

include::nvp/Paysafecard_AuthorizationForVoid_response_tbl.adoc[]

[discrete.tab-content.tab-xml]
==== XML

[.r-details]
.Request Details
[cols="1v,2"]
|===
2+| API Endpoint

e| Method | POST
e| URI    | ``\https://api-test.wirecard.com/engine/rest/paymentmethods/``

2+h| Headers
e| Content-Type | `application/xml`
e| Accept       | `application/xml`
|===

//.Request SEPA Direct Debit: authorization (XML)
[source,xml]
----
include::xml/SEPA_DirectDebit_Authorization_request.xml[]
include::nvp/Paysafecard_AuthorizationForVoid_request_tbl.adoc[]

----

[.r-details]
.Response Details
[cols="1v,2"]
|===
2+h| Headers

e| Content-Type | `application/xml`
2+h| Status
e| Code        | ``201.0000``
e| Severity    | ``information``
e| Description | ``The resource was successfully created.``

|===

//.Response SEPA Direct Debit: authorization (XML)
[source,xml]
----
include::xml/SEPA_DirectDebit_Authorization_response.xml[]
----

include::nvp/Paysafecard_AuthorizationForVoid_response_tbl.adoc[]

