[discrete.sample-tabs]

=== Sofort.: Debit
[discrete.tab-content.tab-json]
==== JSON

[.r-details]
.Request Details
[cols="1v,2"]
|===
2+| API Endpoint

e| Method | POST
e| URI    | ``\https://api-test.wirecard.com/engine/rest/paymentmethods/``

2+h| Headers
e| Content-Type | `application/json`
e| Accept       | `application/json`
|===

//.Request Sofort.: Debit (JSON)
[source,json]
----
include::json/Sofort_Debit_request.json[]
include::nvp/Paysafecard_AuthorizationForVoid_request_tbl.adoc[]

----

[.r-details]
.Response Details
[cols="1v,2"]
|===
2+h| Headers

e| Content-Type | `application/json`
2+h| Status
e| Code        | ``201.0000``
e| Severity    | ``information``
e| Description | ``The resource was successfully created.``

|===

//.Response Sofort.: Debit (JSON)
[source,json]
----
include::json/Sofort_Debit_response.json[]
----

include::nvp/Paysafecard_AuthorizationForVoid_response_tbl.adoc[]

[discrete.tab-content.tab-nvp]
==== NVP

[.r-details]
.Request Details
[cols="1v,2"]
|===
2+| API Endpoint

e| Method | POST
e| URI    | ``\https://api-test.wirecard.com/engine/rest/paymentmethods/``

2+h| Headers
e| Content-Type | `application/x-www-form-urlencoded;charset=UTF-8`
e| Accept       | `text/plain`
|===

//.Request Sofort.: Debit (NVP)
[source,nvp]
----
include::nvp/Sofort_Debit_request.nvp[]
include::nvp/Sofort_Debit_request_tbl.adoc[]

----

[.r-details]
.Response Details
[cols="1v,2"]
|===
2+h| Headers

e| Content-Type | `application/x-www-form-urlencoded;charset=UTF-8`
2+h| Status
e| Code        | ``201.0000``
e| Severity    | ``information``
e| Description | ``The resource was successfully created.``

|===

//.Response Sofort.: Debit (NVP)
[source,nvp]
----
include::nvp/Sofort_Debit_response.nvp[]
----

include::nvp/Sofort_Debit_response_tbl.adoc[]

[discrete.tab-content.tab-xml]
==== XML

[.r-details]
.Request Details
[cols="1v,2"]
|===
2+| API Endpoint

e| Method | POST
e| URI    | ``\https://api-test.wirecard.com/engine/rest/paymentmethods/``

2+h| Headers
e| Content-Type | `application/xml`
e| Accept       | `application/xml`
|===

//.Request Sofort.: Debit (XML)
[source,xml]
----
include::xml/Sofort_Debit_request.xml[]
include::nvp/Sofort_Debit_request_tbl.adoc[]

----

[.r-details]
.Response Details
[cols="1v,2"]
|===
2+h| Headers

e| Content-Type | `application/xml`
2+h| Status
e| Code        | ``201.0000``
e| Severity    | ``information``
e| Description | ``The resource was successfully created.``

|===

//.Response Sofort.: Debit (XML)
[source,xml]
----
include::xml/Sofort_Debit_response.xml[]
----

include::nvp/Sofort_Debit_response_tbl.adoc[]

