[discrete.sample-tabs]

=== Wirecard Voucher: redeem
[discrete.tab-content.tab-json]
==== JSON

[.r-details]
.Request Details
[cols="1v,2"]
|===
2+| API Endpoint

e| Method | POST
e| URI    | ``\https://api-test.wirecard.com/engine/rest/payments/``

2+h| Headers
e| Content-Type | `application/json`
e| Accept       | `application/json`
|===

//.Request Wirecard Voucher: redeem (JSON)
[source,json]
----
include::json/WirecardVoucher_Redeem_request.json[]
include::nvp/Sofort_Debit_request_tbl.adoc[]

----

[.r-details]
.Response Details
[cols="1v,2"]
|===
2+h| Headers

e| Content-Type | `application/json`
2+h| Status
e| Code        | ``201.0000``
e| Severity    | ``information``
e| Description | ``voucher:The resource was successfully created.``

|===

//.Response Wirecard Voucher: redeem (JSON)
[source,json]
----
include::json/WirecardVoucher_Redeem_response.json[]
----

include::nvp/Sofort_Debit_response_tbl.adoc[]

[discrete.tab-content.tab-xml]
==== XML

[.r-details]
.Request Details
[cols="1v,2"]
|===
2+| API Endpoint

e| Method | POST
e| URI    | ``\https://api-test.wirecard.com/engine/rest/payments/``

2+h| Headers
e| Content-Type | `application/xml`
e| Accept       | `application/xml`
|===

//.Request Wirecard Voucher: redeem (XML)
[source,xml]
----
include::xml/WirecardVoucher_Redeem_request.xml[]
include::nvp/Sofort_Debit_request_tbl.adoc[]

----

[.r-details]
.Response Details
[cols="1v,2"]
|===
2+h| Headers

e| Content-Type | `application/xml`
2+h| Status
e| Code        | ``201.0000``
e| Severity    | ``information``
e| Description | ``voucher:The resource was successfully created.``

|===

//.Response Wirecard Voucher: redeem (XML)
[source,xml]
----
include::xml/WirecardVoucher_Redeem_response.xml[]
----

include::nvp/Sofort_Debit_response_tbl.adoc[]

