// This include file requires the shortcut {listname} in the link, as this include file is used in different environments.
// The shortcut guarantees that the target of the link remains in the current environment.

``address`` is a child of
<<CC_Fields_{listname}_request_accountholder, payment.account-holder>> and <<CC_Fields_{listname}_request_shipping, payment.shipping>>. It is used to specify the consumer's address and can refer to

- the consumer (for ``account-holder``). The account holder's address is used as the billing address.
- the consumer's shipping address (for ``shipping``). 

//-

[NOTE]
====
. We strongly recommend sending *all* optional ``address`` fields for ``account-holder`` as well as ``shipping``. If you do, it is less likely that the issuer authenticates the consumer with a <<CreditCard_PSD2_SCA, Strong Customer Authentication>>.
. For the fields ``city``, ``country``, ``postal-code``, ``state`` and ``street1`` the following applies: +
If you want to have a 3D Secure 2 payment process, 
** you must provide a value in either *all* of these fields or in *none* of them.
** for ``state`` you also must meet the ISO 3166-2 standard.
====
