// This include file requires the shortcut {listname} in the link, as this include file is used in different environments.
// The shortcut guarantees that the target of the link remains in the current environment.

``address`` is a child of
<<CC_Fields_{listname}_request_accountholder, payment.account-holder>> and <<CC_Fields_{listname}_request_shipping, payment.shipping>>. It is used to specify the consumer's address and can refer to

- the consumer (for ``account-holder``). The account holder's address is used as the billing address.
- the consumer's shipping address (for ``shipping``). For 3D Secure 2 transactions it is highly recommended to send ``shipping.address`` data in any case, as a complete set of ``shipping.address`` data reduces the likelihood of a challenge test.

//-

[NOTE]
====
* Data can be provided optionally but it helps with fraud checks, if ``address`` is complete.
* For the fields ``city``, ``country``, ``postal-code``, ``state`` and ``street1`` applies the following: +
If you want to be 3D Secure 2 compliant, 
** you must provide a value in *all* of these fields.
** For ``state`` you also must meet the ISO 3166-2 standard.
====
